# Copyright (c) 2018 - 2023 Marcel Walter
# Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

"""Operational analysis of SiDB logic."""

import datetime
import enum
from collections.abc import Callable, Iterator, Sequence
from typing import overload

from typing_extensions import Self

import mnt.pyfiction.sidb
import mnt.pyfiction.sidb.model
import mnt.pyfiction.sidb.simulation
import mnt.pyfiction.synthesis

class input_bdl_configuration(enum.Enum):
    PERTURBER_ABSENCE_ENCODED = 1
    """
    A perturber is used to set the input to `1`, while the absence of a
    perturber represents a `0` (as described in
    https://ieeexplore.ieee.org/abstract/document/8963859).
    """

    PERTURBER_DISTANCE_ENCODED = 0
    """
    An input of `1` is generated by placing a perturber closer to the BDL
    wire, whereas a `0` is produced by positioning the perturber farther
    away (as described in https://dl.acm.org/doi/10.1145/3489517.3530525).
    """

class bdl_input_iterator_params:
    """Parameters for the BDL input iterator."""

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def bdl_wire_params(self) -> detect_bdl_wires_params:
        """Parameters to detect BDL wires."""

    @bdl_wire_params.setter
    def bdl_wire_params(self, arg: detect_bdl_wires_params, /) -> None: ...
    @property
    def input_bdl_config(self) -> input_bdl_configuration:
        """
        The `input_bdl_config` member allows selection between different modes
        for handling input BDLs.
        """

    @input_bdl_config.setter
    def input_bdl_config(self, arg: input_bdl_configuration, /) -> None: ...

class bdl_input_iterator:
    """
    Iterator that assigns the input patterns to the input BDL pairs of an
    SiDB layout. Incrementing the iterator advances the input pattern;
    dereferencing it yields the layout with that pattern applied. Every
    input BDL pair encodes one bit: a `1` keeps the SiDB closer to the
    wire's end, a `0` keeps the other one (perturber-distance encoding) or
    none (perturber-absence encoding). Bit `i` of the pattern belongs to
    the `i`-th input pair in layout order, with the first pair as the most
    significant bit.
    """

    @overload
    def __init__(self, lyt: mnt.pyfiction.sidb.sidb_layout, params: bdl_input_iterator_params = ...) -> None:
        """
        Detects the input BDL pairs and wires of `source_layout` and applies
        input pattern `0`.

        Args:
            source_layout: The layout to iterate over.
            ps: Parameters for the BDL pair and wire detection and the input
                encoding.
        """

    @overload
    def __init__(
        self, lyt: mnt.pyfiction.sidb.sidb_layout, params: bdl_input_iterator_params, input_wires: Sequence[bdl_wire]
    ) -> None:
        """
        Like the constructor above but with input wires that are already
        known.

        Args:
            source_layout: The layout to iterate over.
            ps: Parameters for the BDL pair detection and the input encoding.
            source_input_wires: The input wires of `source_layout`.
        """

    def __iter__(self) -> bdl_input_iterator: ...
    def __next__(self) -> mnt.pyfiction.sidb.sidb_layout:
        """
        The layout with the current input pattern applied.

        Returns:
            The layout.
        """

    def __eq__(self, m: int) -> bool:
        """
        Whether the current input pattern is `m`.

        Args:
            m: The pattern to compare with.

        Returns:
            `true` if the patterns are equal.
        """

    def __ne__(self, m: int) -> bool: ...
    def __lt__(self, m: int) -> bool: ...
    def __le__(self, m: int) -> bool: ...
    def __gt__(self, m: int) -> bool: ...
    def __ge__(self, m: int) -> bool: ...
    def __add__(self, m: int) -> bdl_input_iterator:
        """
        Returns an iterator `m` patterns ahead.

        Args:
            m: The number of patterns to advance.

        Returns:
            The advanced iterator.
        """

    def __iadd__(self, m: int) -> Self:
        """
        Advances by `m` patterns.

        Args:
            m: The number of patterns to advance.

        Returns:
            Reference to `this`.
        """

    def __sub__(self, m: int) -> bdl_input_iterator:
        """
        Returns an iterator `m` patterns behind.

        Args:
            m: The number of patterns to go back.

        Returns:
            The iterator.
        """

    def __isub__(self, m: int) -> Self:
        """
        Goes back by `m` patterns.

        Args:
            m: The number of patterns to go back.

        Returns:
            Reference to `this`.
        """

    def __getitem__(self, m: int) -> bdl_input_iterator:
        """
        Returns an iterator `m` patterns ahead.

        Args:
            m: The number of patterns to advance.

        Returns:
            The advanced iterator.
        """

    def num_input_pairs(self) -> int:
        """
        Number of input BDL pairs.

        Returns:
            The number of input pairs.
        """

    def get_current_input_index(self) -> int:
        """
        The current input pattern.

        Returns:
            The pattern.
        """

    def get_layout(self) -> mnt.pyfiction.sidb.sidb_layout:
        """
        Returns the layout that represents the current input state, equivalent to dereferencing the iterator.
        """

@overload
def generate_bdl_input_pattern_layouts(
    lyt: mnt.pyfiction.sidb.sidb_layout, params: bdl_input_iterator_params = ...
) -> list[mnt.pyfiction.sidb.sidb_layout]:
    """
    Applies every input pattern to the input BDL pairs of a layout and
    returns the resulting layouts, pattern `0` first; the input wires are
    detected first.

    Args:
        lyt: The layout.
        ps: Parameters for the BDL detection and the input encoding.

    Returns:
        One layout per input pattern.
    """

@overload
def generate_bdl_input_pattern_layouts(
    lyt: mnt.pyfiction.sidb.sidb_layout, params: bdl_input_iterator_params, input_wires: Sequence[bdl_wire]
) -> list[mnt.pyfiction.sidb.sidb_layout]:
    """
    Applies every input pattern to the input BDL pairs of a layout and
    returns the resulting layouts, pattern `0` first, with the input wires
    given by the caller.

    Args:
        lyt: The layout.
        ps: Parameters for the BDL pair detection and the input encoding.
        input_wires: The input wires of `lyt`.

    Returns:
        One layout per input pattern.
    """

class bdl_pair:
    """
    A Binary-dot Logic (BDL) pair is a pair of SiDBs that are close to
    each other and, thus, most likely share a charge.
    """

    @overload
    def __init__(self) -> None:
        """Standard constructor for empty BDL pairs."""

    @overload
    def __init__(
        self, t: mnt.pyfiction.sidb.sidb_dot_tag, u: mnt.pyfiction.sidb.lattice_site, l: mnt.pyfiction.sidb.lattice_site
    ) -> None:
        """
        Constructor for BDL pairs.

        Args:
            t: Type of the SiDBs in the pair.
            u: The upper SiDB of the pair.
            l: The lower SiDB of the pair.
        """

    @property
    def type(self) -> mnt.pyfiction.sidb.sidb_dot_tag:
        """
        The type of the SiDBs in the pair. BDL SiDBs must be of the same type.
        They can either be normal, input, or output SiDBs.
        """

    @property
    def upper(self) -> mnt.pyfiction.sidb.lattice_site:
        """
        The upper SiDB of the pair. Upper and lower are defined relative to
        each other via the `operator<` overload.
        """

    @property
    def lower(self) -> mnt.pyfiction.sidb.lattice_site:
        """
        The lower SiDB of the pair. Upper and lower are defined relative to
        each other via the `operator<` overload.
        """

    def __eq__(self, arg: bdl_pair, /) -> bool:
        """
        Equality operator. Also provides `operator!=` via `= default`.

        Args:
            other: The other BDL pair to compare with.

        Returns:
            `true` if this BDL pair is equal to the other, `false` otherwise.
        """

    def __ne__(self, arg: bdl_pair, /) -> bool: ...
    def __lt__(self, arg: bdl_pair, /) -> bool:
        """
        Less than operator.

        Args:
            other: The other BDL pair to compare with.

        Returns:
            `true` if this BDL pair is less than the other, `false` otherwise.
        """

    def __hash__(self) -> int: ...

class detect_bdl_pairs_params:
    """Parameters for the BDL pair detection algorithms."""

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def minimum_distance(self) -> float:
        """
        The minimum distance between two SiDBs to be considered a BDL pair.
        This is useful to prevent, e.g., SiDBs of atomic wires to be
        considered BDL pairs. (unit: nm).
        """

    @minimum_distance.setter
    def minimum_distance(self, arg: float, /) -> None: ...
    @property
    def maximum_distance(self) -> float:
        """
        The maximum distance between two dots to be considered a BDL pair.
        This is useful to prevent unlikely pairings of SiDBs that are far
        apart and to improve performance of the matching algorithm. (unit:
        nm).
        """

    @maximum_distance.setter
    def maximum_distance(self, arg: float, /) -> None: ...

def detect_bdl_pairs(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    type: mnt.pyfiction.sidb.sidb_dot_tag | None = None,
    params: detect_bdl_pairs_params = ...,
) -> list[bdl_pair]:
    """
    Detects the BDL pairs of an SiDB layout. Dots with the given tag are
    uniquely paired in increasing distance. The closest unpaired dots
    within `[params.minimum_distance, params.maximum_distance]` (defaults
    of 0.75 nm and 1.5 nm) form a pair. The lower bound keeps, e.g., the
    SiDBs of an atomic wire from being paired; the upper bound prevents
    unlikely pairings and bounds the work. Distances follow the layout's
    lattice. The pairs are returned sorted.

    Args:
        lyt: The layout to detect BDL pairs in.
        type: Optional dot tag to restrict the detection to (`INPUT`,
              `OUTPUT`, `NORMAL`, ...). If omitted, the BDL pairs of the
              input, output, and normal SiDBs are detected and returned in
              that order.
        params: Parameters for the BDL pair detection.

    Returns:
        The detected BDL pairs.
    """

class bdl_wire_selection(enum.Enum):
    """An enumeration of the selection of different types of wires."""

    ALL = 0
    """Select all BDL wires."""

    INPUT = 1
    """Select only BDL wires that start with input dots."""

    OUTPUT = 2
    """Select only BDL wires that end with output dots."""

ALL: bdl_wire_selection = ...

INPUT: bdl_wire_selection = ...

OUTPUT: bdl_wire_selection = ...

class detect_bdl_wires_params:
    """This struct encapsulates parameters used for detecting BDL wires."""

    def __init__(self) -> None:
        """This struct encapsulates parameters used for detecting BDL wires."""

    @property
    def threshold_bdl_interdistance(self) -> float:
        """
        A distance threshold, which is used to determine if two pairs of BDLs
        are part of the same wire. (unit: nm).
        """

    @threshold_bdl_interdistance.setter
    def threshold_bdl_interdistance(self, arg: float, /) -> None: ...
    @property
    def bdl_pairs_params(self) -> detect_bdl_pairs_params:
        """Parameters for the `detect_bdl_pairs` algorithm."""

    @bdl_pairs_params.setter
    def bdl_pairs_params(self, arg: detect_bdl_pairs_params, /) -> None: ...

class bdl_wire:
    """
    A BDL wire is a chain of BDL pairs. Wires with fewer than two pairs or
    only NORMAL pairs have no port; direction updates leave their end
    pairs unchanged. The vector constructor initializes the end pairs from
    the first and last supplied pairs. Adding only NORMAL pairs to a
    default-constructed wire leaves both unset.

    For other wires, input and output pairs form the endpoints where
    present. An input-only wire ends at the farthest pair from its input;
    an output-only wire starts at the farthest pair from its output.
    """

    @overload
    def __init__(self) -> None:
        """Constructs an empty wire."""

    @overload
    def __init__(self, p: Sequence[bdl_pair]) -> None:
        """
        Constructs a wire from BDL pairs and determines its direction.

        Args:
            p: The BDL pairs of the wire.
        """

    @property
    def pairs(self) -> list[bdl_pair]:
        """The BDL pairs of the wire."""

    @pairs.setter
    def pairs(self, arg: Sequence[bdl_pair], /) -> None: ...
    @property
    def direction(self) -> "fiction::fcn::port_direction":
        """Port direction of the wire."""

    @direction.setter
    def direction(self, arg: "fiction::fcn::port_direction", /) -> None: ...
    @property
    def first_bdl_pair(self) -> bdl_pair | None:
        """First BDL pair of the wire."""

    @first_bdl_pair.setter
    def first_bdl_pair(self, arg: bdl_pair | None, /) -> None: ...
    @property
    def last_bdl_pair(self) -> bdl_pair | None:
        """Last BDL pair of the wire."""

    @last_bdl_pair.setter
    def last_bdl_pair(self, arg: bdl_pair | None, /) -> None: ...
    def add_bdl_pair(self, pair: bdl_pair) -> None:
        """
        Adds a BDL pair to the wire, keeps the pairs sorted, and updates the
        direction.

        Args:
            pair: The BDL pair to add.
        """

    def erase_bdl_pair(self, pair: bdl_pair) -> None:
        """
        Removes a BDL pair from the wire and updates the direction if it was
        present.

        Args:
            pair: The BDL pair to remove.
        """

    def find_bdl_pair_by_type(self, t: mnt.pyfiction.sidb.sidb_dot_tag) -> bdl_pair | None:
        """
        Finds the first BDL pair of the given type.

        Args:
            t: The SiDB type to look for.

        Returns:
            The first BDL pair of type `t`, or `std::nullopt` if the wire has
            none.
        """

    def __eq__(self, arg: bdl_wire, /) -> bool:
        """
        Equality operator. Also provides `operator!=` via `= default`.

        Args:
            other: The other wire to compare with.

        Returns:
            `true` if both wires hold the same pairs, port, and end pairs.
        """

    def __ne__(self, arg: bdl_wire, /) -> bool: ...

def detect_bdl_wires(
    lyt: mnt.pyfiction.sidb.sidb_layout, params: detect_bdl_wires_params = ..., wire_selection: bdl_wire_selection = ...
) -> list[bdl_wire]:
    """
    Detects the BDL wires of an SiDB layout: the BDL pairs of all types
    are chained into wires along the layout's lattice whenever two pairs
    lie within `params.threshold_bdl_interdistance` of each other.

    Args:
        lyt: The layout.
        params: Parameters for the BDL pair and wire detection.
        wire_selection: Which wires to return: all, input, or output
                        wires.

    Returns:
        The detected wires.
    """

class operational_status(enum.Enum):
    """Possible operational status of a layout."""

    OPERATIONAL = 0
    """The layout is operational."""

    NON_OPERATIONAL = 1
    """The layout is non-operational."""

class operational_condition(enum.Enum):
    """
    Condition to decide whether a layout is operational or non-
    operational.
    """

    TOLERATE_KINKS = 0
    """
    Even if the I/O pins show kinks, the layout is still considered as
    operational.
    """

    REJECT_KINKS = 1
    """
    The I/O pins are not allowed to show kinks. If kinks exist, the layout
    is considered non-operational.
    """

class operational_analysis_strategy(enum.Enum):
    """
    Simulation method to determine if the layout is operational or non-
    operational. There are three possible
    strategies:

    - `SIMULATION_ONLY`: This setting does not apply any filtering
      strategies to determine if the layout is
    operational. Instead, it relies solely on physical simulation to make
    this determination.
    - `FILTER_ONLY`: This setting does only apply filtering strategies to
      determine if the layout is
    non-operational. If the layout passes all filtering strategies, it is
    considered operational. This is only an approximation. It may be
    possible that the layout is non-operational, but the filtering
    strategies do not detect it. Sweeping a parameter space this way is
    called the operational domain sketch. The filtering steps are only
    defined when kinks are rejected, and they enumerate the charge
    configurations of the canvas that the layout's `LOGIC` dots define, so
    this setting is only effective with `REJECT_KINKS` on a layout that
    has such dots.
    - `FILTER_THEN_SIMULATION`: Before a physical simulation is conducted,
      the algorithm checks if filtering
    strategies have detected whether the layout is non-operational. This
    only provides any runtime benefits if kinks are rejected.
    """

    SIMULATION_ONLY = 0
    """
    Do not apply filter strategies to determine whether the layout is
    operational. Instead, rely solely on physical simulation.
    """

    FILTER_ONLY = 1
    """
    Apply filtering exclusively to determine whether the layout is non-
    operational. If the layout passes all filter steps, it is considered
    operational. Sweeping a parameter space this way is called the
    operational domain sketch.

    Note:
        This is an extremely fast approximation that may sometimes lead to
        false positives. It requires `REJECT_KINKS` and a layout with
        `LOGIC` dots; without either, no filter step runs.
    """

    FILTER_THEN_SIMULATION = 2
    """
    Before a physical simulation is conducted, the algorithm checks if
    filter strategies can determine that the layout is non-operational.
    This only provides any runtime benefits if kinks are rejected.
    """

class is_operational_params:
    """Parameters for the `is_operational` algorithm."""

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def timeout(self) -> int:
        """
        Millisecond budget for the complete operation. Gate design, domains,
        and critical-temperature calculations share this budget across all
        nested checks. The maximum value means unlimited; zero expires
        immediately. Expiration throws `utils::timeout_error` without
        returning a partial result.
        """

    @timeout.setter
    def timeout(self, arg: int, /) -> None: ...
    @property
    def simulation_parameters(self) -> mnt.pyfiction.sidb.model.sidb_simulation_parameters:
        """
        The simulation parameters for the physical simulation of the ground
        state.
        """

    @simulation_parameters.setter
    def simulation_parameters(self, arg: mnt.pyfiction.sidb.model.sidb_simulation_parameters, /) -> None: ...
    @property
    def sim_engine(self) -> mnt.pyfiction.sidb.simulation.sidb_simulation_engine:
        """
        The simulation engine to be used for the operational domain
        computation.
        """

    @sim_engine.setter
    def sim_engine(self, arg: mnt.pyfiction.sidb.simulation.sidb_simulation_engine, /) -> None: ...
    @property
    def input_bdl_iterator_params(self) -> bdl_input_iterator_params:
        """Parameters for the BDL input iterator."""

    @input_bdl_iterator_params.setter
    def input_bdl_iterator_params(self, arg: bdl_input_iterator_params, /) -> None: ...
    @property
    def op_condition(self) -> operational_condition:
        """
        Condition to decide whether a layout is operational or non-
        operational.
        """

    @op_condition.setter
    def op_condition(self, arg: operational_condition, /) -> None: ...
    @property
    def strategy_to_analyze_operational_status(self) -> operational_analysis_strategy:
        """
        Strategy to determine whether a layout is operational or non-
        operational.
        """

    @strategy_to_analyze_operational_status.setter
    def strategy_to_analyze_operational_status(self, arg: operational_analysis_strategy, /) -> None: ...

@overload
def is_operational(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: is_operational_params = ...,
) -> tuple[operational_status, int]:
    """
    Determines whether an SiDB layout implements the given Boolean
    function(s). Every input pattern is applied to the input BDL pairs,
    the ground states are simulated with the configured engine, and the
    charge states of the output BDL pairs are compared with the expected
    truth-table entries. If the layout carries logic dots, they form the
    canvas of the pruning filters that run before any simulation whenever
    the parameters ask for filtering and reject kinks.

    Args:
        lyt: The layout to check.
        spec: The Boolean function(s) it has to implement.
        params: Parameters.

    Returns:
        The operational status and the number of simulator invocations.
    """

@overload
def is_operational(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: is_operational_params,
    input_bdl_wire: Sequence[bdl_wire],
    output_bdl_wire: Sequence[bdl_wire],
    canvas_lyt: mnt.pyfiction.sidb.sidb_layout | None = None,
) -> tuple[operational_status, int]:
    """
    Like the overload above, with the BDL wires and, optionally, the
    canvas given by the caller.

    Args:
        lyt: The layout to check.
        spec: The Boolean function(s) it has to implement.
        params: Parameters.
        input_bdl_wire: The input BDL wires of `lyt`.
        output_bdl_wire: The output BDL wires of `lyt`.
        canvas_lyt: The canvas; defaults to the logic dots of `lyt`.

    Returns:
        The operational status and the number of simulator invocations.
    """

@overload
def is_operational(
    input_pattern_layouts: Sequence[mnt.pyfiction.sidb.sidb_layout],
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: is_operational_params,
    input_bdl_wire: Sequence[bdl_wire],
    output_bdl_wire: Sequence[bdl_wire],
    canvas_lyt: mnt.pyfiction.sidb.sidb_layout | None = None,
) -> tuple[operational_status, int]:
    """
    Like the overloads above, but with one layout per input pattern given
    by the caller instead of applying the patterns to the input BDL pairs.

    Args:
        input_pattern_layouts: One layout per input pattern, pattern `0`
                               first.
        spec: The Boolean function(s) to implement.
        params: Parameters.
        input_bdl_wire: The input BDL wires.
        output_bdl_wire: The output BDL wires.
        canvas_lyt: The canvas; defaults to the logic dots of the first
                    layout.

    Returns:
        The operational status and the number of simulator invocations.

    Raises:
        std::invalid_argument: if `spec` is empty or the number of layouts
                               does not match the number of patterns.
    """

@overload
def operational_input_patterns(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: is_operational_params = ...,
) -> set[int]:
    """
    Determines the input patterns for which the layout is operational.

    Args:
        lyt: The layout to check.
        spec: The Boolean function(s) it has to implement.
        params: Parameters.

    Returns:
        The operational input patterns.
    """

@overload
def operational_input_patterns(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: is_operational_params,
    input_bdl_wire: Sequence[bdl_wire],
    output_bdl_wire: Sequence[bdl_wire],
    canvas_lyt: mnt.pyfiction.sidb.sidb_layout | None = None,
) -> set[int]:
    """
    Like the overload above, with the BDL wires and, optionally, the
    canvas given by the caller.

    Args:
        lyt: The layout to check.
        spec: The Boolean function(s) it has to implement.
        params: Parameters.
        input_bdl_wire: The input BDL wires of `lyt`.
        output_bdl_wire: The output BDL wires of `lyt`.
        canvas_lyt: The canvas; defaults to none.

    Returns:
        The operational input patterns.
    """

@overload
def kink_induced_non_operational_input_patterns(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: is_operational_params = ...,
) -> set[int]:
    """
    Determines the input patterns for which kinks render the layout non-
    operational.

    Args:
        lyt: The layout to check.
        spec: The Boolean function(s) it has to implement.
        params: Parameters; kinks are rejected regardless of
                `params.op_condition`.

    Returns:
        The kink-induced non-operational input patterns.
    """

@overload
def kink_induced_non_operational_input_patterns(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: is_operational_params,
    input_bdl_wire: Sequence[bdl_wire],
    output_bdl_wire: Sequence[bdl_wire],
    canvas_lyt: mnt.pyfiction.sidb.sidb_layout | None = None,
) -> set[int]:
    """
    Like the overload above, with the BDL wires and, optionally, the
    canvas given by the caller.

    Args:
        lyt: The layout to check.
        spec: The Boolean function(s) it has to implement.
        params: Parameters; kinks are rejected regardless of
                `params.op_condition`.
        input_bdl_wire: The input BDL wires of `lyt`.
        output_bdl_wire: The output BDL wires of `lyt`.
        canvas_lyt: The canvas; defaults to none.

    Returns:
        The kink-induced non-operational input patterns.
    """

@overload
def is_kink_induced_non_operational(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: is_operational_params = ...,
) -> bool:
    """
    Determines whether kinks are the reason the layout is non-operational.

    Args:
        lyt: The layout to check.
        spec: The Boolean function(s) it has to implement.
        params: Parameters; kinks are rejected regardless of
                `params.op_condition`.

    Returns:
        `true` if the layout is non-operational because of kinks.
    """

@overload
def is_kink_induced_non_operational(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: is_operational_params,
    input_bdl_wire: Sequence[bdl_wire],
    output_bdl_wire: Sequence[bdl_wire],
    canvas_lyt: mnt.pyfiction.sidb.sidb_layout | None = None,
) -> bool:
    """
    Like the overload above, with the BDL wires and, optionally, the
    canvas given by the caller.

    Args:
        lyt: The layout to check.
        spec: The Boolean function(s) it has to implement.
        params: Parameters; kinks are rejected regardless of
                `params.op_condition`.
        input_bdl_wire: The input BDL wires of `lyt`.
        output_bdl_wire: The output BDL wires of `lyt`.
        canvas_lyt: The canvas; defaults to none.

    Returns:
        `true` if the layout is non-operational because of kinks.
    """

class parameter_point:
    """The parameter point holds one parameter value per sweep dimension."""

    @overload
    def __init__(self) -> None:
        """Default constructor."""

    @overload
    def __init__(self, values: Sequence[float]) -> None:
        """
        Standard constructor.

        Args:
            values: Parameter values for each dimension.
        """

    def get_parameters(self) -> list[float]:
        """
        Returns the parameter values for each dimension.

        Returns:
            The parameter values for each dimension.
        """

    def __eq__(self, other: parameter_point) -> bool:
        """
        Equality operator. Checks if this parameter point is equal to another
        point within a specified tolerance. The tolerance is defined by
        `constants::ERROR_MARGIN`.

        Args:
            other: Other parameter point to compare with.

        Returns:
            `true` iff the parameter points are equal.
        """

    def __ne__(self, other: parameter_point) -> bool:
        """
        Inequality operator. Checks if this parameter point is not equal to another point within the tolerance defined by `constants::ERROR_MARGIN`.

        :param other: Other parameter point to compare with.
        :return: ``True`` iff the parameter points are not equal.
        """

    def __hash__(self) -> int:
        """Returns a hash value of the parameter point."""

    def __getitem__(self, arg: int, /) -> float:
        """
        Returns the value of the parameter at the given index. Raises `IndexError` if the index is out of range.
        """

class sweep_parameter(enum.Enum):
    """Possible sweep parameters for the operational domain computation."""

    EPSILON_R = 0
    """The relative permittivity of the dielectric material."""

    LAMBDA_TF = 1
    """The Thomas-Fermi screening length."""

    MU_MINUS = 2
    """The energy transition level."""

class critical_temperature_domain:
    """
    The `critical_temperature_domain` class collects the critical
    temperature and the operational status for a range of different
    physical parameters of a given SiDB layout. It allows for the
    evaluation of how the critical temperature depends on variations in
    the underlying parameter points. This enables simulations to explore
    the critical temperature's behavior across different conditions and
    configurations.

    It was proposed in \\"The Operational Domain Explorer: A Comprehensive
    Framework to Unveil the Thermal Landscape of Silicon Dangling Bond
    Logic Beyond Conventional Operability\\" by M. Walter, J. Drewniok, and
    R. Wille in IEEE-NANO 2025
    (https://ieeexplore.ieee.org/abstract/document/11113672).
    """

    @overload
    def __init__(self) -> None:
        """Default constructor."""

    @overload
    def __init__(self, dims: Sequence[sweep_parameter]) -> None:
        """
        Constructs a critical temperature domain with the given sweep dimensions.
        """

    def get_dimension(self, index: int) -> sweep_parameter:
        """
        Returns a specific dimension by index.

        Args:
            index: The index of the dimension to return.

        Returns:
            The dimension at the specified index.

        Raises:
            std::out_of_range: if the index is out of range.
        """

    def get_number_of_dimensions(self) -> int:
        """
        Returns the number of dimensions to sweep over.

        Returns:
            The number of dimensions to sweep over.
        """

    def minimum_ct(self) -> float:
        """
        Finds the minimum critical temperature in the domain.

        Returns:
            The minimum critical temperature.
        """

    def maximum_ct(self) -> float:
        """
        Finds the maximum critical temperature in the domain.

        Returns:
            The maximum critical temperature.
        """

    def __getitem__(self, arg: parameter_point, /) -> tuple[operational_status, float]:
        """
        Returns the value stored for the given parameter point, raising a KeyError if it does not exist.
        """

    def __setitem__(self, arg0: parameter_point, arg1: tuple[operational_status, float], /) -> None:
        """Sets the value stored for the given parameter point."""

    def __contains__(self, arg: parameter_point, /) -> bool:
        """Checks whether the given parameter point is contained in the domain."""

    def __len__(self) -> int:
        """Returns the number of parameter points stored in the domain."""

    def __iter__(self) -> Iterator:
        """Returns an iterator over the parameter points stored in the domain."""

    def keys(self) -> list[parameter_point]: ...
    def values(self) -> list[tuple[operational_status, float]]: ...
    def items(self) -> list[tuple[parameter_point, tuple[operational_status, float]]]: ...

class operational_domain:
    """
    An operational domain is a set of simulation parameter values for
    which a given SiDB layout is logically operational. This means that a
    layout is deemed operational if the layout's ground state corresponds
    with a given Boolean function at the layout's outputs for all possible
    input combinations. In this implementation, :math:`n` BDL input wires
    and a single BDL output wire are assumed for a given layout. Any
    operational domain computation algorithm toggles through all
    :math:`2^n` input combinations and evaluates the layout's output
    behavior in accordance with the given Boolean function. The layout is
    only considered operational for a certain parameter combination, if
    the output behavior is correct for all input combinations. The
    operational domain can be computed by sweeping over specified
    simulation parameters and checking the operational status of the
    layout for each parameter combination. The operational domain is then
    defined as the set of all parameter combinations for which the layout
    is operational. Different techniques for performing these sweep are
    implemented.
    """

    @overload
    def __init__(self) -> None:
        """Default constructor."""

    @overload
    def __init__(self, dims: Sequence[sweep_parameter]) -> None:
        """
        Standard constructor.

        Args:
            dims: Dimensions.
        """

    def add_dimension(self, dim: sweep_parameter) -> None:
        """
        Adds a dimension to sweep over. The first dimension is the x
        dimension, the second dimension is the y dimension, etc.

        Args:
            dim: The dimension to add.
        """

    def get_dimension(self, index: int) -> sweep_parameter:
        """
        Returns a specific dimension by index.

        Args:
            index: The index of the dimension to return.

        Returns:
            The dimension at the specified index.

        Raises:
            std::out_of_range: if the index is out of range.
        """

    def get_number_of_dimensions(self) -> int:
        """
        Returns the number of dimensions to sweep over.

        Returns:
            The number of dimensions to sweep over.
        """

    def __getitem__(self, arg: parameter_point, /) -> operational_status:
        """
        Returns the operational status stored for the given parameter point, raising a KeyError if it does not exist.
        """

    def __setitem__(self, arg0: parameter_point, arg1: operational_status, /) -> None:
        """Sets the operational status stored for the given parameter point."""

    def __contains__(self, arg: parameter_point, /) -> bool:
        """Checks whether the given parameter point is contained in the domain."""

    def __len__(self) -> int:
        """Returns the number of parameter points stored in the domain."""

    def __iter__(self) -> Iterator:
        """Returns an iterator over the parameter points stored in the domain."""

    def keys(self) -> list[parameter_point]: ...
    def values(self) -> list[operational_status]: ...
    def items(self) -> list[tuple[parameter_point, operational_status]]: ...

class operational_domain_value_range:
    """
    A range of values for a dimension sweep. The range is defined by a
    minimum value, a maximum value and a step size.
    """

    @overload
    def __init__(self, dimension: sweep_parameter) -> None: ...
    @overload
    def __init__(self, dimension: sweep_parameter, min: float, max: float, step: float) -> None: ...
    @property
    def dimension(self) -> sweep_parameter:
        """The sweep parameter of the dimension."""

    @dimension.setter
    def dimension(self, arg: sweep_parameter, /) -> None: ...
    @property
    def min(self) -> float:
        """The minimum value of the dimension sweep."""

    @min.setter
    def min(self, arg: float, /) -> None: ...
    @property
    def max(self) -> float:
        """The maximum value of the dimension sweep."""

    @max.setter
    def max(self, arg: float, /) -> None: ...
    @property
    def step(self) -> float:
        """The step size of the dimension sweep."""

    @step.setter
    def step(self, arg: float, /) -> None: ...

class operational_domain_params:
    """
    Parameters for the operational domain computation. The parameters are
    used across the different operational domain computation algorithms.
    """

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def operational_params(self) -> is_operational_params:
        """
        Operational parameters. Their timeout bounds the entire domain
        calculation across all parameter points and workers. Finite budgets
        reject ClusterComplete and throw `utils::timeout_error` on expiration.
        """

    @operational_params.setter
    def operational_params(self, arg: is_operational_params, /) -> None: ...
    @property
    def sweep_dimensions(self) -> list[operational_domain_value_range]:
        """
        Dimensions to sweep over together with their value ranges, ordered by
        priority.

        The first dimension is the x dimension, the second dimension is the y
        dimension, etc. The default sweeps relative permittivity and screening
        distance from 1.0 to 10.0 in steps of 0.1.
        """

    @sweep_dimensions.setter
    def sweep_dimensions(self, arg: Sequence[operational_domain_value_range], /) -> None: ...
    @property
    def number_of_threads(self) -> int:
        """
        Number of worker threads to distribute the parameter points over.

        Defaults to the number of hardware threads, or `1` when that count is
        unavailable. Values below `1` are treated as `1`.

        Pinning it makes wall-clock comparisons reproducible across runs and
        machines, and allows an operational domain computation to leave cores
        free for other work.
        """

    @number_of_threads.setter
    def number_of_threads(self, arg: int, /) -> None: ...
    @property
    def on_progress(self, /) -> Callable[[str, int, int], None] | None:
        """
        Callback that receives the number of evaluated parameter points. The
        total is known for grid search and random sampling only.
        """

    @on_progress.setter
    def on_progress(self, value: Callable[[str, int, int], None] | None) -> None: ...
    @property
    def on_worker_progress(self, /) -> Callable[[int, int, str, int, int, bool], None] | None:
        """
        Reports logical worker activity with a fixed worker count for each
        invocation.
        """

    @on_worker_progress.setter
    def on_worker_progress(self, value: Callable[[int, int, str, int, int, bool], None] | None) -> None: ...

class operational_domain_stats:
    """
    Statistics for the operational domain computation. The statistics are
    used across the different operational domain computation algorithms.
    """

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def time_total(self) -> datetime.timedelta:
        """The total runtime of the operational domain computation."""

    @property
    def num_simulator_invocations(self) -> int:
        """Number of simulator invocations."""

    @property
    def num_evaluated_parameter_combinations(self) -> int:
        """Number of evaluated parameter combinations."""

    @property
    def num_operational_parameter_combinations(self) -> int:
        """Number of parameter combinations, for which the layout is operational."""

    @property
    def num_non_operational_parameter_combinations(self) -> int:
        """
        Number of parameter combinations, for which the layout is non-
        operational.
        """

    @property
    def num_total_parameter_points(self) -> int:
        """Total number of parameter points in the parameter space."""

def operational_domain_grid_search(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: operational_domain_params = ...,
    stats: operational_domain_stats | None = None,
) -> operational_domain:
    """
    Computes the operational domain of the given SiDB layout. The
    operational domain is the set of all parameter combinations for which
    the layout is logically operational. Logical operation is defined as
    the layout implementing the given truth table. The input BDL pairs of
    the layout are assumed to be in the same order as the inputs of the
    truth table.

    This algorithm uses a grid search to find the operational domain. The
    grid search is performed by exhaustively sweeping all sweep
    dimensions. Since grid search is exhaustive, the algorithm is
    guaranteed to find the operational domain, if it exists within the
    parameter range. However, the algorithm performs one operational check
    per parameter combination, i.e., the product of the step counts of all
    sweep dimensions, where each operational check consists of up to
    :math:`2^n` exact ground state simulations, where :math:`n` is the
    number of inputs of the layout. Each exact ground state simulation has
    exponential complexity in of itself. Therefore, the algorithm is only
    feasible for small layouts with few inputs.

    Args:
        lyt: Layout to compute the operational domain for.
        spec: Expected Boolean functions, one dynamic truth table per
              output.
        params: Parameters for the operational domain computation.
        stats: Statistics of the process.

    Returns:
        The operational domain of the layout.

    Raises:
        std::invalid_argument: if the given sweep parameters are invalid,
                               or if the operational domain sketch is
                               requested without rejecting kinks or on a
                               layout without `LOGIC` dots. Any number of
                               sweep dimensions is accepted.
    """

def operational_domain_random_sampling(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    samples: int,
    params: operational_domain_params = ...,
    stats: operational_domain_stats | None = None,
) -> operational_domain:
    """
    Computes the operational domain of the given SiDB layout. The
    operational domain is the set of all parameter combinations for which
    the layout is logically operational. Logical operation is defined as
    the layout implementing the given truth table. The input BDL pairs of
    the layout are assumed to be in the same order as the inputs of the
    truth table.

    This algorithm uses random sampling to find a part of the operational
    domain that might not be complete. It performs a total of `samples`
    uniformly-distributed random samples within the parameter range. For
    each sample, the algorithm performs one operational check on the
    layout, where each operational check consists of up to :math:`2^n`
    exact ground state simulations, where :math:`n` is the number of
    inputs of the layout. Each exact ground state simulation has
    exponential complexity in of itself. Therefore, the algorithm is only
    feasible for small layouts with few inputs.

    Args:
        lyt: Layout to compute the operational domain for.
        spec: Expected Boolean function of the layout given as a multi-
              output truth table.
        samples: Number of samples to perform.
        params: Operational domain computation parameters.
        stats: Operational domain computation statistics.

    Returns:
        The operational domain of the layout.

    Raises:
        std::invalid_argument: if the given sweep parameters are invalid,
                               or if the operational domain sketch is
                               requested without rejecting kinks or on a
                               layout without `LOGIC` dots. Any number of
                               sweep dimensions is accepted.
    """

def operational_domain_flood_fill(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    samples: int,
    params: operational_domain_params = ...,
    stats: operational_domain_stats | None = None,
) -> operational_domain:
    """
    Computes the operational domain of the given SiDB layout. The
    operational domain is the set of all parameter combinations for which
    the layout is logically operational. Logical operation is defined as
    the layout implementing the given truth table. The input BDL pairs of
    the layout are assumed to be in the same order as the inputs of the
    truth table.

    This algorithm first uses random sampling to find several operational
    points within the parameter range. From there, it employs the "flood
    fill" algorithm to explore the operational domain. The algorithm is
    guaranteed to determine all operational "islands" in their entirety if
    the initial random sampling found at least one operational point
    within them. Thereby, this algorithm works for disconnected
    operational domains.

    It performs `samples` uniformly-distributed random samples within the
    parameter range. From there, it performs another number of samples
    equal to the number of points within the operational domain plus the
    first non-operational point in each direction. For each sample, the
    algorithm performs one operational check on the layout, where each
    operational check consists of up to :math:`2^n` exact ground state
    simulations, where :math:`n` is the number of inputs of the layout.
    Each exact ground state simulation has exponential complexity in of
    itself. Therefore, the algorithm is only feasible for small layouts
    with few inputs.

    This flavor of operational domain computation was proposed in
    \\"Reducing the Complexity of Operational Domain Computation in Silicon
    Dangling Bond Logic\\" by M. Walter, J. Drewniok, S. S. H. Ng, K.
    Walus, and R. Wille in NANOARCH 2023.

    Args:
        lyt: Layout to compute the operational domain for.
        spec: Expected Boolean function of the layout given as a multi-
              output truth table.
        samples: Number of samples to perform.
        params: Operational domain computation parameters.
        stats: Operational domain computation statistics.

    Returns:
        The operational domain of the layout.

    Raises:
        std::invalid_argument: if the given sweep parameters are invalid,
                               or if the operational domain sketch is
                               requested without rejecting kinks or on a
                               layout without `LOGIC` dots. Flood fill and
                               contour tracing additionally require at
                               least two sweep dimensions; grid search and
                               random sampling accept any number.
    """

def operational_domain_contour_tracing(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    samples: int,
    params: operational_domain_params = ...,
    stats: operational_domain_stats | None = None,
) -> operational_domain:
    """
    Computes the operational domain of the given SiDB layout. The
    operational domain is the set of all parameter combinations for which
    the layout is logically operational. Logical operation is defined as
    the layout implementing the given truth table. The input BDL pairs of
    the layout are assumed to be in the same order as the inputs of the
    truth table.

    This algorithm first uses random sampling to find a set of operational
    point within the parameter range. From there, it traverses outwards to
    find the edge of the operational area and performs Moore neighborhood
    contour tracing to explore the contour of the operational domain. This
    is repeated for all initially sampled points that do not lie within a
    contour. The algorithm is guaranteed to determine the contours of all
    operational "islands" if the initial random sampling found at least
    one operational point within them. Thereby, this algorithm works for
    disconnected operational domains.

    It performs `samples` uniformly-distributed random samples within the
    parameter range. For each thusly discovered operational island, it
    performs another number of samples equal to the distance to an edge of
    each operational area. Finally, it performs up to 8 samples for each
    contour point (however, the actual number is usually lower). For each
    sample, the algorithm performs one operational check on the layout,
    where each operational check consists of up to :math:`2^n` exact
    ground state simulations, where :math:`n` is the number of inputs of
    the layout. Each exact ground state simulation has exponential
    complexity in of itself. Therefore, the algorithm is only feasible for
    small layouts with few inputs.

    Args:
        lyt: Layout to compute the operational domain for.
        spec: Expected Boolean function of the layout given as a multi-
              output truth table.
        samples: Number of samples to perform.
        params: Operational domain computation parameters.
        stats: Operational domain computation statistics.

    Returns:
        The operational domain of the layout.

    Raises:
        std::invalid_argument: if the given sweep parameters are invalid,
                               or if the operational domain sketch is
                               requested without rejecting kinks or on a
                               layout without `LOGIC` dots. Flood fill and
                               contour tracing additionally require at
                               least two sweep dimensions; grid search and
                               random sampling accept any number.
    """

def critical_temperature_domain_grid_search(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    params: operational_domain_params = ...,
    stats: operational_domain_stats | None = None,
) -> critical_temperature_domain:
    """
    Computes the critical temperature domain of the given SiDB layout. The
    critical temperature domain consists of all parameter combinations for
    which the layout is logically operational, along with the critical
    temperature for each specific parameter point.

    This algorithm uses a grid search to find the operational domain. The
    grid search is performed by exhaustively sweeping all sweep
    dimensions. Since grid search is exhaustive, the algorithm is
    guaranteed to find the operational domain, if it exists within the
    parameter range. However, the algorithm performs one operational check
    per parameter combination, i.e., the product of the step counts of all
    sweep dimensions, where each operational check consists of up to
    :math:`2^n` exact ground state simulations, where :math:`n` is the
    number of inputs of the layout. Each exact ground state simulation has
    exponential complexity in of itself. Therefore, the algorithm is only
    feasible for small layouts with few inputs.

    Args:
        lyt: Layout to compute the operational domain for.
        spec: Expected vector of truth tables of the layout. Each truth
              table represents an output of the Boolean function.
        params: Operational domain computation parameters.
        stats: Operational domain computation statistics.

    Returns:
        The critical temperature domain of the layout.

    Raises:
        std::invalid_argument: if the given sweep parameters are invalid,
                               or if the operational domain sketch is
                               requested without rejecting kinks or on a
                               layout without `LOGIC` dots. Any number of
                               sweep dimensions is accepted.
    """

def critical_temperature_domain_random_sampling(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    samples: int,
    params: operational_domain_params = ...,
    stats: operational_domain_stats | None = None,
) -> critical_temperature_domain:
    """
    Computes the critical temperature domain of the given SiDB layout. The
    critical temperature domain consists of all parameter combinations for
    which the layout is logically operational, along with the critical
    temperature for each specific parameter point.

    This algorithm uses random sampling to find a part of the operational
    domain that might not be complete. It performs a total of `samples`
    uniformly-distributed random samples within the parameter range. For
    each sample, the algorithm performs one operational check on the
    layout, where each operational check consists of up to :math:`2^n`
    exact ground state simulations, where :math:`n` is the number of
    inputs of the layout. Each exact ground state simulation has
    exponential complexity in of itself. Therefore, the algorithm is only
    feasible for small layouts with few inputs.

    Args:
        lyt: Layout to compute the operational domain for.
        spec: Expected Boolean function of the layout given as a multi-
              output truth table.
        samples: Number of samples to perform.
        params: Operational domain computation parameters.
        stats: Operational domain computation statistics.

    Returns:
        The critical temperature domain of the layout.

    Raises:
        std::invalid_argument: if the given sweep parameters are invalid,
                               or if the operational domain sketch is
                               requested without rejecting kinks or on a
                               layout without `LOGIC` dots. Any number of
                               sweep dimensions is accepted.
    """

def critical_temperature_domain_flood_fill(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    samples: int,
    params: operational_domain_params = ...,
    stats: operational_domain_stats | None = None,
) -> critical_temperature_domain:
    """
    Computes the critical temperature domain of the given SiDB layout. The
    critical temperature domain consists of all parameter combinations for
    which the layout is logically operational, along with the critical
    temperature for each specific parameter point.

    This algorithm first uses random sampling to find several operational
    points within the parameter range. From there, it employs the "flood
    fill" algorithm to explore the operational domain. The algorithm is
    guaranteed to determine all operational "islands" in their entirety if
    the initial random sampling found at least one operational point
    within them. Thereby, this algorithm works for disconnected
    operational domains.

    It performs `samples` uniformly-distributed random samples within the
    parameter range. From there, it performs another number of samples
    equal to the number of points within the operational domain plus the
    first non-operational point in each direction. For each sample, the
    algorithm performs one operational check on the layout, where each
    operational check consists of up to :math:`2^n` exact ground state
    simulations, where :math:`n` is the number of inputs of the layout.
    Each exact ground state simulation has exponential complexity in of
    itself. Therefore, the algorithm is only feasible for small layouts
    with few inputs.

    Args:
        lyt: Layout to compute the operational domain for.
        spec: Expected Boolean function of the layout given as a multi-
              output truth table.
        samples: Number of samples to perform.
        params: Operational domain computation parameters.
        stats: Operational domain computation statistics.

    Returns:
        The critical temperature domain of the layout.

    Raises:
        std::invalid_argument: if the given sweep parameters are invalid,
                               or if the operational domain sketch is
                               requested without rejecting kinks or on a
                               layout without `LOGIC` dots. Flood fill and
                               contour tracing additionally require at
                               least two sweep dimensions; grid search and
                               random sampling accept any number.
    """

def critical_temperature_domain_contour_tracing(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    samples: int,
    params: operational_domain_params = ...,
    stats: operational_domain_stats | None = None,
) -> critical_temperature_domain:
    """
    Computes the critical temperature domain of the given SiDB layout. The
    critical temperature domain consists of all parameter combinations for
    which the layout is logically operational, along with the critical
    temperature for each specific parameter point.

    This algorithm first uses random sampling to find a set of operational
    point within the parameter range. From there, it traverses outwards to
    find the edge of the operational area and performs Moore neighborhood
    contour tracing to explore the contour of the operational domain. This
    is repeated for all initially sampled points that do not lie within a
    contour. The algorithm is guaranteed to determine the contours of all
    operational "islands" if the initial random sampling found at least
    one operational point within them. Thereby, this algorithm works for
    disconnected operational domains. The critical temperature is computed
    for each operational point.

    It performs `samples` uniformly-distributed random samples within the
    parameter range. For each thusly discovered operational island, it
    performs another number of samples equal to the distance to an edge of
    each operational area. Finally, it performs up to 8 samples for each
    contour point (however, the actual number is usually lower). For each
    sample, the algorithm performs one operational check on the layout,
    where each operational check consists of up to :math:`2^n` exact
    ground state simulations, where :math:`n` is the number of inputs of
    the layout. Each exact ground state simulation has exponential
    complexity in of itself. Therefore, the algorithm is only feasible for
    small layouts with few inputs.

    Args:
        lyt: Layout to compute the operational domain for.
        spec: Expected Boolean function of the layout given as a multi-
              output truth table.
        samples: Number of samples to perform.
        params: Operational domain computation parameters.
        stats: Operational domain computation statistics.

    Returns:
        The critical temperature domain of the layout.

    Raises:
        std::invalid_argument: if the given sweep parameters are invalid,
                               or if the operational domain sketch is
                               requested without rejecting kinks or on a
                               layout without `LOGIC` dots. Flood fill and
                               contour tracing additionally require at
                               least two sweep dimensions; grid search and
                               random sampling accept any number.
    """

class operational_domain_ratio_params:
    """
    Parameters for computing the ratio of operational parameter points
    around a specified parameter point to the total number of parameter
    points in the given parameter space.
    """

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def op_domain_params(self) -> operational_domain_params:
        """Parameters for the operational domain computation."""

    @op_domain_params.setter
    def op_domain_params(self, arg: operational_domain_params, /) -> None: ...

def operational_domain_ratio(
    lyt: mnt.pyfiction.sidb.sidb_layout,
    spec: Sequence[mnt.pyfiction.synthesis.dynamic_truth_table],
    pp: parameter_point,
    params: operational_domain_ratio_params = ...,
) -> float:
    """
    Calculates the ratio of operational parameter points surrounding a
    specified parameter point to the total number of parameter points in
    the given parameter space. This function is useful for assessing how
    robust a gate design is to variations in its parameters.

    A ratio close to 1 indicates that the gate is robust, meaning it
    functions correctly across a broad range of parameter values. A ratio
    close to 0 indicates that the gate is highly sensitive to parameter
    variations and may fail to operate correctly.

    Args:
        lyt: The SiDB layout for which to compute the ratio of operational
             parameter points surrounding a specified parameter point to
             the total number of parameter points.
        spec: The expected Boolean function of the layout, provided as a
              multi-output truth table.
        params: Parameters.
        pp: The specific parameter point around which the operational
            ratio is computed.

    Returns:
        The ratio of operational parameter points to the total number of
        parameter points in the parameter space.

    Raises:
        std::invalid_argument: if the sweep has fewer than two dimensions,
                               a range is invalid, or the seed is non-
                               finite, outside the grid, or has the wrong
                               dimension count.
    """
