/*
 * Copyright (c) 2018 - 2023 Marcel Walter
 * Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
 * All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License
 */

/**
 * @file
 * @author Jan Drewniok (Drewniok)
 * @author Marcel Walter (marcelwa)
 */

#include <catch2/catch_template_test_macros.hpp>
#include <catch2/catch_test_macros.hpp>

#include "fiction/utils/version_info.hpp"

#include <fiction/layouts/coordinates.hpp>
#include <fiction/technology/qca/io/write_qca_layout_svg.hpp>
#include <fiction/technology/qca/technology.hpp>
#include <fiction/types.hpp>

#include <fmt/format.h>

#include <cctype>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <sstream>
#include <string>

using namespace fiction;

/**
 * This function takes an SVG string as input and returns a new string with all
 * whitespace characters removed. The purpose is to create a compact representation
 * of the SVG content, which can be useful for comparisons, optimizations, or transmission.
 *
 * @param svg The input SVG string to be normalized.
 * @return A string with all whitespace characters removed.
 */
[[nodiscard]] static std::string normalize_svg(const std::string& svg) noexcept
{
    std::string result = svg;

    // Remove all whitespace (spaces, tabs, newlines)
    std::erase_if(result, ::isspace);

    return result;
};

/**
 * Checks whether `text` contains `substring`.
 *
 * @param text Text to search.
 * @param substring Substring to find.
 * @return `true` iff `substring` appears in `text`.
 */
[[nodiscard]] static bool contains(const std::string& text, const std::string& substring) noexcept
{
    return text.find(substring) != std::string::npos;
}

inline const std::string EXPECTED_SVG_MOL_QCA_DETAILED =
    fmt::format(R"SVG(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by {} ({}) -->

<svg
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:cc="http://creativecommons.org/ns#"
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
xmlns:svg="http://www.w3.org/2000/svg"
xmlns="http://www.w3.org/2000/svg"
viewBox="0 0 102.5 33.5"
version="1.1">
<metadata>
<rdf:RDF>
<cc:Work
rdf:about="">
<dc:format>image/svg+xml</dc:format>
<dc:type
rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
<dc:title></dc:title>
</cc:Work>
</rdf:RDF>
</metadata>
<g>
<g
    style="fill:#ffe700;"
    transform="translate(-78.56596,-41.78984)">

  <rect
    style="fill:#ffe700;stroke:#ffe700;"
    width="10"
    height="10"
    x="92.93404"
    y="56.46016" />

  <g style="stroke:#000000;stroke-width:0.5;fill:#ffe700;">
    <!-- left molecule -->
    <line x1="95.43404" y1="58.96016" x2="95.43404" y2="63.96016" />
    <circle r="0.97553" cx="95.43404" cy="58.96016" />
    <circle r="0.50000" cx="95.43404" cy="61.46016" />
    <circle r="0.97553" cx="95.43404" cy="63.96016" />

    <!-- right molecule -->
    <line x1="100.43404" y1="58.96016" x2="100.43404" y2="63.96016" />
    <circle r="0.97553" cx="100.43404" cy="58.96016" />
    <circle r="0.50000" cx="100.43404" cy="61.46016" />
    <circle r="0.97553" cx="100.43404" cy="63.96016" />
  </g>
</g><g
    style="fill:#cccccc;"
    transform="translate(-67.06596,-41.78984)">

  <rect
    style="fill:#cccccc;stroke:#cccccc;"
    width="10"
    height="10"
    x="92.93404"
    y="56.46016" />

  <g style="stroke:#000000;stroke-width:0.5;fill:#cccccc;">
    <!-- left molecule -->
    <line x1="95.43404" y1="58.96016" x2="95.43404" y2="63.96016" />
    <circle r="0.97553" cx="95.43404" cy="58.96016" />
    <circle r="0.50000" cx="95.43404" cy="61.46016" />
    <circle r="0.97553" cx="95.43404" cy="63.96016" />

    <!-- right molecule -->
    <line x1="100.43404" y1="58.96016" x2="100.43404" y2="63.96016" />
    <circle r="0.97553" cx="100.43404" cy="58.96016" />
    <circle r="0.50000" cx="100.43404" cy="61.46016" />
    <circle r="0.97553" cx="100.43404" cy="63.96016" />
  </g>
</g><g
    style="fill:#4a4a4a;"
    transform="translate(-55.565960000000004,-41.78984)">

  <rect
    style="fill:#4a4a4a;stroke:#4a4a4a;"
    width="10"
    height="10"
    x="92.93404"
    y="56.46016" />

  <g style="stroke:#000000;stroke-width:0.5;fill:#4a4a4a;">
    <!-- left molecule -->
    <line x1="95.43404" y1="58.96016" x2="95.43404" y2="63.96016" />
    <circle r="0.97553" cx="95.43404" cy="58.96016" />
    <circle r="0.50000" cx="95.43404" cy="61.46016" />
    <circle r="0.97553" cx="95.43404" cy="63.96016" />

    <!-- right molecule -->
    <line x1="100.43404" y1="58.96016" x2="100.43404" y2="63.96016" />
    <circle r="0.97553" cx="100.43404" cy="58.96016" />
    <circle r="0.50000" cx="100.43404" cy="61.46016" />
    <circle r="0.97553" cx="100.43404" cy="63.96016" />
  </g>
</g><g
    transform="translate(-44.065960000000004,-41.78984)">

  <rect
    style="fill:#000000;stroke:#000000;"
    width="10"
    height="10"
    x="92.93404"
    y="56.46016" />

  <text
    x="97.93404"
    y="63.46016"
    style="font-family:Arial, sans-serif;font-size:6px;fill:#ffffff;"
    text-anchor="middle"
    alignment-baseline="central">
    C0
  </text>
</g><g
    transform="translate(-32.565960000000004,-41.78984)">

  <rect
    style="fill:#000000;stroke:#000000;"
    width="10"
    height="10"
    x="92.93404"
    y="56.46016" />

  <text
    x="97.93404"
    y="63.46016"
    style="font-family:Arial, sans-serif;font-size:6px;fill:#ffffff;"
    text-anchor="middle"
    alignment-baseline="central">
    C1
  </text>
</g><g
    style="fill:#f800ff;"
    transform="translate(-21.065960000000004,-41.78984)">
  <g>
    <rect
      transform="rotate(90)"
      ry="1.07143"
      y="-102.93404"
      x="56.46016"
      width="10"
      height="10"
      style="fill:#f800ff;stroke:#000000;" />
    <circle
      r="5.31886"
      transform="rotate(90)"
      cx="61.46016"
      cy="-97.93404"
      style="fill:none;stroke:#000000;" />
  </g>
</g>
</g>
</svg>)SVG",
                FICTION_VERSION, FICTION_REPO);

inline const std::string EXPECTED_SVG_MOL_QCA_SIMPLE =
    fmt::format(R"SVG(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by {} ({}) -->

<svg
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:cc="http://creativecommons.org/ns#"
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
xmlns:svg="http://www.w3.org/2000/svg"
xmlns="http://www.w3.org/2000/svg"
viewBox="0 0 102.5 33.5"
version="1.1">
<metadata>
<rdf:RDF>
<cc:Work
rdf:about="">
<dc:format>image/svg+xml</dc:format>
<dc:type
rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
<dc:title></dc:title>
</cc:Work>
</rdf:RDF>
</metadata>
<g>
<g
transform="translate(-78.56596,-41.78984)">
<rect
ry="0.75"
y="56.46016"
x="92.93404"
height="10"
width="10"
style="fill:#ffe700;stroke:#000000;" />
</g><g
transform="translate(-67.06596,-41.78984)">
<rect
ry="0.75"
y="56.46016"
x="92.93404"
height="10"
width="10"
style="fill:#cccccc;stroke:#000000;" />
</g><g
transform="translate(-55.565960000000004,-41.78984)">
<rect
ry="0.75"
y="56.46016"
x="92.93404"
height="10"
width="10"
style="fill:#4a4a4a;stroke:#000000;" />
</g><g
transform="translate(-44.065960000000004,-41.78984)">
<rect
ry="0.75"
y="56.46016"
x="92.93404"
height="10"
width="10"
style="fill:#000000;stroke:#000000;" />
</g><g
transform="translate(-32.565960000000004,-41.78984)">
<rect
ry="0.75"
y="56.46016"
x="92.93404"
height="10"
width="10"
style="fill:#000000;stroke:#000000;" />
</g><g
    style="fill:#f800ff;"
    transform="translate(-21.065960000000004,-41.78984)">
  <g>
    <rect
      transform="rotate(90)"
      ry="1.07143"
      y="-102.93404"
      x="56.46016"
      width="10"
      height="10"
      style="fill:#f800ff;stroke:#000000;" />
    <circle
      r="5.31886"
      transform="rotate(90)"
      cx="61.46016"
      cy="-97.93404"
      style="fill:none;stroke:#000000;" />
  </g>
</g>
</g>
</svg>)SVG",
                FICTION_VERSION, FICTION_REPO);

TEST_CASE("Reject molQCA crossings in simple SVG mode", "[write-mol-qca-layout-svg]")
{
    mol_qca_cell_clk_lyt layout{{0, 0, 1}, "unsupported molQCA crossing"};
    layout.assign_cell_type({0, 0, 0}, qca::mol_qca_technology::cell_type::NORMAL1);
    layout.assign_cell_type({0, 0, 1}, qca::mol_qca_technology::cell_type::NORMAL2);

    std::ostringstream                         layout_stream{};
    const qca::io::write_qca_layout_svg_params params{.simple = true};

    CHECK_THROWS_AS(qca::io::write_mol_qca_layout_svg(layout, layout_stream, params),
                    qca::io::unsupported_cell_type_exception<layouts::coords::offset>);
}

TEST_CASE("Generate MolQCA layout in SVG", "[write-mol-qca-layout-svg]")
{
    mol_qca_cell_clk_lyt layout{{6, 0, 1}, "molQCA SVG"};
    layout.assign_cell_type({0, 0, 0}, qca::mol_qca_technology::cell_type::NORMAL1);
    layout.assign_cell_type({1, 0, 0}, qca::mol_qca_technology::cell_type::INPUT);
    layout.assign_cell_type({2, 0, 0}, qca::mol_qca_technology::cell_type::OUTPUT);
    layout.assign_cell_type({3, 0, 0}, qca::mol_qca_technology::cell_type::CONST_0);
    layout.assign_cell_type({4, 0, 0}, qca::mol_qca_technology::cell_type::CONST_1);
    layout.assign_cell_type({5, 0, 1}, qca::mol_qca_technology::cell_type::NORMAL4);
    layout.assign_cell_mode({5, 0, 1}, qca::mol_qca_technology::cell_mode::VERTICAL);
    layout.assign_cell_type({6, 0, 1}, qca::mol_qca_technology::cell_type::NORMAL2);

    SECTION("detailed mode")
    {
        std::ostringstream layout_stream{};

        qca::io::write_mol_qca_layout_svg(layout, layout_stream);

        const auto svg = layout_stream.str();

        CHECK(normalize_svg(svg) == normalize_svg(EXPECTED_SVG_MOL_QCA_DETAILED));
    }

    SECTION("simple mode")
    {
        std::ostringstream                         layout_stream{};
        const qca::io::write_qca_layout_svg_params params{.simple = true};

        qca::io::write_mol_qca_layout_svg(layout, layout_stream, params);

        const auto svg = layout_stream.str();

        CHECK(normalize_svg(svg) == normalize_svg(EXPECTED_SVG_MOL_QCA_SIMPLE));
    }

    SECTION("file overload")
    {
        const auto filename = std::filesystem::temp_directory_path() / "fiction_mol_qca_layout.svg";

        qca::io::write_mol_qca_layout_svg(layout, filename.string());

        std::ifstream file{filename};
        REQUIRE(file.is_open());

        const std::string svg{std::istreambuf_iterator<char>{file}, std::istreambuf_iterator<char>{}};

        CHECK(contains(svg, "Generated by"));
        CHECK(contains(svg, "C0"));

        file.close();
        std::filesystem::remove(filename);
    }
}

TEST_CASE("Reject invalid MolQCA SVG output files", "[write-mol-qca-layout-svg]")
{
    const mol_qca_cell_clk_lyt layout{{0, 0}, "molQCA SVG"};

    CHECK_THROWS_AS(qca::io::write_mol_qca_layout_svg(layout, "/this/path/does/not/exist/mol_qca.svg"),
                    std::ofstream::failure);
}

TEST_CASE("Generate QCA layout in simple SVG mode with constant cells", "[write-qca-layout-svg]")
{
    qca_cell_clk_lyt layout{{1, 0}, "QCA constant cells"};
    layout.assign_cell_type({0, 0}, qca::qca_technology::cell_type::CONST_0);
    layout.assign_cell_type({1, 0}, qca::qca_technology::cell_type::CONST_1);

    std::ostringstream                         layout_stream{};
    const qca::io::write_qca_layout_svg_params params{.simple = true};

    qca::io::write_qca_layout_svg(layout, layout_stream, params);

    const auto svg = layout_stream.str();

    CHECK(contains(svg, "fill:#000000"));
    CHECK_FALSE(contains(svg, "fill:##"));
}
