/*
 * Copyright (c) 2018 - 2023 Marcel Walter
 * Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
 * All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License
 */

/**
 * @file
 * @brief Tests for `fiction/networks/io/dot_drawers.hpp`.
 * @author Marcel Walter (marcelwa)
 */

#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generators.hpp>

#include "fiction/utils/version_info.hpp"
#include "utils/blueprints/layout_blueprints.hpp"

#include <fiction/layouts/arrangement.hpp>
#include <fiction/layouts/cartesian_layout.hpp>
#include <fiction/layouts/gate_level_layout.hpp>
#include <fiction/layouts/hexagonal_layout.hpp>
#include <fiction/layouts/io/layout_drawers.hpp>
#include <fiction/networks/io/dot_drawers.hpp>

#include <fmt/format.h>
#include <kitty/dynamic_truth_table.hpp>
#include <mockturtle/networks/aig.hpp>
#include <mockturtle/traits.hpp>

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <ios>
#include <iterator>
#include <limits>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>

using namespace fiction;
using namespace fiction::layouts;
using namespace fiction::layouts::io;
using namespace fiction::networks::io;

namespace
{

/**
 * @brief Raises a serialization error after DOT output has started.
 */
class failing_dot_drawer : public technology_dot_drawer<mockturtle::aig_network>
{
  public:
    /**
     * @brief Reject a node label to exercise failed serialization.
     * @param ntk Network being drawn.
     * @param n Node being drawn.
     * @return No label; always throws.
     * @throws std::runtime_error On every call.
     */
    [[nodiscard]] std::string node_label(const mockturtle::aig_network&                   ntk,
                                         const mockturtle::node<mockturtle::aig_network>& n) const override
    {
        static_cast<void>(ntk);
        static_cast<void>(n);
        throw std::runtime_error("drawing failed");
    }
};

template <typename Lyt, typename Drawer>
void compare_dot_layout(const Lyt& lyt, const std::string_view& layout_print)
{
    std::stringstream dot_stream{};

    write_dot_layout<Lyt, Drawer>(lyt, dot_stream);

    CHECK(dot_stream.str() == layout_print);
}

}  // namespace

TEST_CASE("Draw empty Cartesian layout", "[dot-drawers]")
{
    using gate_layout = gate_level_layout<cartesian_layout>;

    const gate_layout layout{gate_layout::extent{3, 3}};

    static const std::string layout_print =
        fmt::format("digraph layout {{  // Generated by {} ({})\n"
                    "splines=ortho;\n"
                    "nodesep=0.25;\n"
                    "ranksep=0.25;\n"
                    "rankdir=TB;\n"
                    "\n"
                    "node [fixedsize=true, width=0.5, height=0.5, shape=square, style=filled];\n"
                    "x0y0 [label=\"\", fillcolor=white];\n"
                    "x1y0 [label=\"\", fillcolor=white];\n"
                    "x2y0 [label=\"\", fillcolor=white];\n"
                    "x0y1 [label=\"\", fillcolor=white];\n"
                    "x1y1 [label=\"\", fillcolor=white];\n"
                    "x2y1 [label=\"\", fillcolor=white];\n"
                    "x0y2 [label=\"\", fillcolor=white];\n"
                    "x1y2 [label=\"\", fillcolor=white];\n"
                    "x2y2 [label=\"\", fillcolor=white];\n"
                    "\n"
                    "edge [constraint=false];\n"
                    "\n"
                    "edge [constraint=true, style=invis];\n"
                    "x0y0 -> x0y1 -> x0y2;\n"
                    "x1y0 -> x1y1 -> x1y2;\n"
                    "x2y0 -> x2y1 -> x2y2;\n"
                    "rank = same {{ x0y0 -> x1y0 -> x2y0 }};\n"
                    "rank = same {{ x0y1 -> x1y1 -> x2y1 }};\n"
                    "rank = same {{ x0y2 -> x1y2 -> x2y2 }};\n"
                    "}}\n",
                    FICTION_VERSION, FICTION_REPO);

    compare_dot_layout<gate_layout, gate_layout_cartesian_drawer<gate_layout, false, false>>(layout, layout_print);
}

TEST_CASE("Draw Cartesian layout blueprints", "[dot-drawers]")
{
    using gate_layout = gate_level_layout<cartesian_layout>;

    SECTION("AND-OR Layout")
    {
        const auto layout = blueprints::and_or_gate_layout<gate_layout>();

        static const std::string layout_print =
            fmt::format("digraph layout {{  // Generated by {} ({})\n"
                        "splines=ortho;\n"
                        "nodesep=0.25;\n"
                        "ranksep=0.25;\n"
                        "rankdir=TB;\n"
                        "\n"
                        "node [fixedsize=true, width=0.5, height=0.5, shape=square, style=filled];\n"
                        "x0y0 [label=\"f1\", fillcolor=snow2];\n"
                        "x1y0 [label=\"AND\", fillcolor=lightcoral];\n"
                        "x2y0 [label=\"x1\", fillcolor=snow2];\n"
                        "x3y0 [label=\"\", fillcolor=white];\n"
                        "x0y1 [label=\"\", fillcolor=white];\n"
                        "x1y1 [label=\"x2\", fillcolor=snow2];\n"
                        "x2y1 [label=\"OR\", fillcolor=palegreen2];\n"
                        "x3y1 [label=\"f2\", fillcolor=snow2];\n"
                        "\n"
                        "edge [constraint=false];\n"
                        "x2y0 -> x1y0 [style=solid];\n"
                        "x1y1 -> x1y0 [style=solid];\n"
                        "x1y1 -> x2y1 [style=solid];\n"
                        "x2y0 -> x2y1 [style=solid];\n"
                        "x1y0 -> x0y0 [style=solid];\n"
                        "x2y1 -> x3y1 [style=solid];\n"
                        "\n"
                        "edge [constraint=true, style=invis];\n"
                        "x0y0 -> x0y1;\n"
                        "x1y0 -> x1y1;\n"
                        "x2y0 -> x2y1;\n"
                        "x3y0 -> x3y1;\n"
                        "rank = same {{ x0y0 -> x1y0 -> x2y0 -> x3y0 }};\n"
                        "rank = same {{ x0y1 -> x1y1 -> x2y1 -> x3y1 }};\n"
                        "}}\n",
                        FICTION_VERSION, FICTION_REPO);

        compare_dot_layout<gate_layout, gate_layout_cartesian_drawer<gate_layout, false, false>>(layout, layout_print);
    }
    SECTION("XOR-MAJ Layout")
    {
        const auto layout = blueprints::xor_maj_gate_layout<gate_layout>();

        static const std::string layout_print =
            fmt::format("digraph layout {{  // Generated by {} ({})\n"
                        "splines=ortho;\n"
                        "nodesep=0.25;\n"
                        "ranksep=0.25;\n"
                        "rankdir=TB;\n"
                        "\n"
                        "node [fixedsize=true, width=0.5, height=0.5, shape=square, style=filled];\n"
                        "x0y0 [label=\"f2\", fillcolor=snow2];\n"
                        "x1y0 [label=\"XOR\", fillcolor=lightskyblue];\n"
                        "x2y0 [label=\"b\", fillcolor=snow2];\n"
                        "x3y0 [label=\"\", fillcolor=white];\n"
                        "x0y1 [label=\"\", fillcolor=white];\n"
                        "x1y1 [label=\"a\", fillcolor=snow2];\n"
                        "x2y1 [label=\"MAJ\", fillcolor=lightsalmon];\n"
                        "x3y1 [label=\"c\", fillcolor=snow2];\n"
                        "x0y2 [label=\"\", fillcolor=white];\n"
                        "x1y2 [label=\"\", fillcolor=white];\n"
                        "x2y2 [label=\"f1\", fillcolor=snow2];\n"
                        "x3y2 [label=\"\", fillcolor=white];\n"
                        "\n"
                        "edge [constraint=false];\n"
                        "x1y1 -> x2y1 [style=solid];\n"
                        "x2y0 -> x2y1 [style=solid];\n"
                        "x3y1 -> x2y1 [style=solid];\n"
                        "x1y1 -> x1y0 [style=solid];\n"
                        "x2y0 -> x1y0 [style=solid];\n"
                        "x2y1 -> x2y2 [style=solid];\n"
                        "x1y0 -> x0y0 [style=solid];\n"
                        "\n"
                        "edge [constraint=true, style=invis];\n"
                        "x0y0 -> x0y1 -> x0y2;\n"
                        "x1y0 -> x1y1 -> x1y2;\n"
                        "x2y0 -> x2y1 -> x2y2;\n"
                        "x3y0 -> x3y1 -> x3y2;\n"
                        "rank = same {{ x0y0 -> x1y0 -> x2y0 -> x3y0 }};\n"
                        "rank = same {{ x0y1 -> x1y1 -> x2y1 -> x3y1 }};\n"
                        "rank = same {{ x0y2 -> x1y2 -> x2y2 -> x3y2 }};\n"
                        "}}\n",
                        FICTION_VERSION, FICTION_REPO);

        compare_dot_layout<gate_layout, gate_layout_cartesian_drawer<gate_layout, false, false>>(layout, layout_print);
    }
    SECTION("Crossing Layout")
    {
        const auto layout = blueprints::crossing_layout<gate_layout>();

        static const std::string layout_print =
            fmt::format("digraph layout {{  // Generated by {} ({})\n"
                        "splines=ortho;\n"
                        "nodesep=0.25;\n"
                        "ranksep=0.25;\n"
                        "rankdir=TB;\n"
                        "\n"
                        "node [fixedsize=true, width=0.5, height=0.5, shape=square, style=filled];\n"
                        "x0y0 [label=\"\", fillcolor=white];\n"
                        "x1y0 [label=\"x1\", fillcolor=snow2];\n"
                        "x2y0 [label=\"x3\", fillcolor=snow2];\n"
                        "x3y0 [label=\"\", fillcolor=white];\n"
                        "x0y1 [label=\"x2\", fillcolor=snow2];\n"
                        "x1y1 [label=\"AND\", fillcolor=lightcoral];\n"
                        "x2y1 [label=\"+\", fillcolor=palegoldenrod];\n"
                        "x3y1 [label=\"f1\", fillcolor=snow2];\n"
                        "x0y2 [label=\"x4\", fillcolor=snow2];\n"
                        "x1y2 [label=\"BUF\", fillcolor=palegoldenrod];\n"
                        "x2y2 [label=\"AND\", fillcolor=lightcoral];\n"
                        "x3y2 [label=\"f2\", fillcolor=snow2];\n"
                        "\n"
                        "edge [constraint=false];\n"
                        "x1y0 -> x1y1 [style=solid];\n"
                        "x0y1 -> x1y1 [style=solid];\n"
                        "x2y0 -> x2y1 [style=solid];\n"
                        "x0y2 -> x1y2 [style=solid];\n"
                        "x2y1 -> x2y2 [style=solid];\n"
                        "x1y2 -> x2y2 [style=solid];\n"
                        "x1y1 -> x2y1 [style=solid];\n"
                        "x2y1 -> x3y1 [style=solid];\n"
                        "x2y2 -> x3y2 [style=solid];\n"
                        "\n"
                        "edge [constraint=true, style=invis];\n"
                        "x0y0 -> x0y1 -> x0y2;\n"
                        "x1y0 -> x1y1 -> x1y2;\n"
                        "x2y0 -> x2y1 -> x2y2;\n"
                        "x3y0 -> x3y1 -> x3y2;\n"
                        "rank = same {{ x0y0 -> x1y0 -> x2y0 -> x3y0 }};\n"
                        "rank = same {{ x0y1 -> x1y1 -> x2y1 -> x3y1 }};\n"
                        "rank = same {{ x0y2 -> x1y2 -> x2y2 -> x3y2 }};\n"
                        "}}\n",
                        FICTION_VERSION, FICTION_REPO);

        compare_dot_layout<gate_layout, gate_layout_cartesian_drawer<gate_layout, false, false>>(layout, layout_print);
    }
}

TEST_CASE("Draw empty hexagonal layouts", "[dot-drawers]")
{
    SECTION("odd row")
    {
        using gate_layout  = gate_level_layout<hexagonal_layout>;
        constexpr auto arr = arrangement::ODD_ROW;

        const gate_layout layout{arr, gate_layout::extent{3, 3}};

        static const std::string layout_print =
            fmt::format("digraph layout {{  // Generated by {} ({})\n"
                        "splines=ortho;\n"
                        "nodesep=0.25;\n"
                        "ranksep=0.125;\n"
                        "rankdir=TB;\n"
                        "\n"
                        "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, orientation=30, style=filled];\n"
                        "x0y0 [label=\"\", fillcolor=white];\n"
                        "x1y0 [label=\"\", fillcolor=white];\n"
                        "x2y0 [label=\"\", fillcolor=white];\n"
                        "x0y1 [label=\"\", fillcolor=white];\n"
                        "x1y1 [label=\"\", fillcolor=white];\n"
                        "x2y1 [label=\"\", fillcolor=white];\n"
                        "x0y2 [label=\"\", fillcolor=white];\n"
                        "x1y2 [label=\"\", fillcolor=white];\n"
                        "x2y2 [label=\"\", fillcolor=white];\n"
                        "\n"
                        "edge [constraint=false];\n"
                        "\n"
                        "edge [constraint=true, style=invis];\n"
                        "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                        "rank = same {{ x0y0 -> x1y0 -> x2y0 }};\n"
                        "rank = same {{ x0y1 -> x1y1 -> x2y1 }};\n"
                        "rank = same {{ x0y2 -> x1y2 -> x2y2 }};\n"
                        "rank = same {{ invis1 -> x0y1 }};\n"
                        "invis1 -> x0y0;\n"
                        "invis1 -> x0y2;\n"
                        "x0y0 -> x0y1;\n"
                        "x1y0 -> x0y1;\n"
                        "x1y0 -> x1y1;\n"
                        "x2y0 -> x1y1;\n"
                        "x2y0 -> x2y1;\n"
                        "x0y1 -> x0y2;\n"
                        "x0y1 -> x1y2;\n"
                        "x1y1 -> x1y2;\n"
                        "x1y1 -> x2y2;\n"
                        "x2y1 -> x2y2;\n"
                        "}}\n",
                        FICTION_VERSION, FICTION_REPO);

        compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout, layout_print);
    }
    SECTION("even row")
    {
        using gate_layout  = gate_level_layout<hexagonal_layout>;
        constexpr auto arr = arrangement::EVEN_ROW;

        const gate_layout layout{arr, gate_layout::extent{3, 3}};

        static const std::string layout_print =
            fmt::format("digraph layout {{  // Generated by {} ({})\n"
                        "splines=ortho;\n"
                        "nodesep=0.25;\n"
                        "ranksep=0.125;\n"
                        "rankdir=TB;\n"
                        "\n"
                        "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, orientation=30, style=filled];\n"
                        "x0y0 [label=\"\", fillcolor=white];\n"
                        "x1y0 [label=\"\", fillcolor=white];\n"
                        "x2y0 [label=\"\", fillcolor=white];\n"
                        "x0y1 [label=\"\", fillcolor=white];\n"
                        "x1y1 [label=\"\", fillcolor=white];\n"
                        "x2y1 [label=\"\", fillcolor=white];\n"
                        "x0y2 [label=\"\", fillcolor=white];\n"
                        "x1y2 [label=\"\", fillcolor=white];\n"
                        "x2y2 [label=\"\", fillcolor=white];\n"
                        "\n"
                        "edge [constraint=false];\n"
                        "\n"
                        "edge [constraint=true, style=invis];\n"
                        "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                        "rank = same {{ x0y0 -> x1y0 -> x2y0 }};\n"
                        "rank = same {{ x0y1 -> x1y1 -> x2y1 }};\n"
                        "rank = same {{ x0y2 -> x1y2 -> x2y2 }};\n"
                        "rank = same {{ invis0 -> x0y0 }};\n"
                        "invis0 -> x0y1;\n"
                        "rank = same {{ invis2 -> x0y2 }};\n"
                        "invis2 -> x0y1;\n"
                        "x0y0 -> x0y1;\n"
                        "x0y0 -> x1y1;\n"
                        "x1y0 -> x1y1;\n"
                        "x1y0 -> x2y1;\n"
                        "x2y0 -> x2y1;\n"
                        "x0y1 -> x0y2;\n"
                        "x1y1 -> x0y2;\n"
                        "x1y1 -> x1y2;\n"
                        "x2y1 -> x1y2;\n"
                        "x2y1 -> x2y2;\n"
                        "}}\n",
                        FICTION_VERSION, FICTION_REPO);

        compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout, layout_print);
    }
    SECTION("odd column")
    {
        using gate_layout  = gate_level_layout<hexagonal_layout>;
        constexpr auto arr = arrangement::ODD_COLUMN;

        const gate_layout layout{arr, gate_layout::extent{3, 3}};

        static const std::string layout_print =
            fmt::format("digraph layout {{  // Generated by {} ({})\n"
                        "splines=ortho;\n"
                        "nodesep=0.25;\n"
                        "ranksep=0.125;\n"
                        "rankdir=LR;\n"
                        "\n"
                        "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, style=filled];\n"
                        "x0y0 [label=\"\", fillcolor=white];\n"
                        "x1y0 [label=\"\", fillcolor=white];\n"
                        "x2y0 [label=\"\", fillcolor=white];\n"
                        "x0y1 [label=\"\", fillcolor=white];\n"
                        "x1y1 [label=\"\", fillcolor=white];\n"
                        "x2y1 [label=\"\", fillcolor=white];\n"
                        "x0y2 [label=\"\", fillcolor=white];\n"
                        "x1y2 [label=\"\", fillcolor=white];\n"
                        "x2y2 [label=\"\", fillcolor=white];\n"
                        "\n"
                        "edge [constraint=false];\n"
                        "\n"
                        "edge [constraint=true, style=invis];\n"
                        "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                        "rank = same {{ x0y0 -> x0y1 -> x0y2 }};\n"
                        "rank = same {{ x1y0 -> x1y1 -> x1y2 }};\n"
                        "rank = same {{ x2y0 -> x2y1 -> x2y2 }};\n"
                        "rank = same {{ invis1 -> x1y0 }};\n"
                        "invis1 -> x0y0;\n"
                        "invis1 -> x2y0;\n"
                        "x0y0 -> x1y0;\n"
                        "x1y0 -> x2y1;\n"
                        "x1y0 -> x2y0;\n"
                        "x1y0 -> x0y1;\n"
                        "x0y1 -> x1y1;\n"
                        "x1y1 -> x2y2;\n"
                        "x1y1 -> x2y1;\n"
                        "x1y1 -> x0y2;\n"
                        "x0y2 -> x1y2;\n"
                        "x1y2 -> x2y2;\n"
                        "}}\n",
                        FICTION_VERSION, FICTION_REPO);

        compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout, layout_print);
    }
    SECTION("even column")
    {
        using gate_layout  = gate_level_layout<hexagonal_layout>;
        constexpr auto arr = arrangement::EVEN_COLUMN;

        const gate_layout layout{arr, gate_layout::extent{3, 3}};

        static const std::string layout_print =
            fmt::format("digraph layout {{  // Generated by {} ({})\n"
                        "splines=ortho;\n"
                        "nodesep=0.25;\n"
                        "ranksep=0.125;\n"
                        "rankdir=LR;\n"
                        "\n"
                        "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, style=filled];\n"
                        "x0y0 [label=\"\", fillcolor=white];\n"
                        "x1y0 [label=\"\", fillcolor=white];\n"
                        "x2y0 [label=\"\", fillcolor=white];\n"
                        "x0y1 [label=\"\", fillcolor=white];\n"
                        "x1y1 [label=\"\", fillcolor=white];\n"
                        "x2y1 [label=\"\", fillcolor=white];\n"
                        "x0y2 [label=\"\", fillcolor=white];\n"
                        "x1y2 [label=\"\", fillcolor=white];\n"
                        "x2y2 [label=\"\", fillcolor=white];\n"
                        "\n"
                        "edge [constraint=false];\n"
                        "\n"
                        "edge [constraint=true, style=invis];\n"
                        "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                        "rank = same {{ x0y0 -> x0y1 -> x0y2 }};\n"
                        "rank = same {{ x1y0 -> x1y1 -> x1y2 }};\n"
                        "rank = same {{ x2y0 -> x2y1 -> x2y2 }};\n"
                        "rank = same {{ invis0 -> x0y0 }};\n"
                        "invis0 -> x1y0;\n"
                        "rank = same {{ invis2 -> x2y0 }};\n"
                        "invis2 -> x1y0;\n"
                        "x0y0 -> x1y1;\n"
                        "x0y0 -> x1y0;\n"
                        "x1y0 -> x2y0;\n"
                        "x2y0 -> x1y1;\n"
                        "x0y1 -> x1y2;\n"
                        "x0y1 -> x1y1;\n"
                        "x1y1 -> x2y1;\n"
                        "x2y1 -> x1y2;\n"
                        "x0y2 -> x1y2;\n"
                        "x1y2 -> x2y2;\n"
                        "}}\n",
                        FICTION_VERSION, FICTION_REPO);

        compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout, layout_print);
    }
}

TEST_CASE("Draw hexagonal layout blueprints", "[dot-drawers]")
{
    SECTION("odd row")
    {
        using gate_layout  = gate_level_layout<hexagonal_layout>;
        constexpr auto arr = arrangement::ODD_ROW;

        SECTION("AND-OR Layout")
        {
            const auto layout = blueprints::and_or_gate_layout<gate_layout>(arr);

            static const std::string layout_print = fmt::format(
                "digraph layout {{  // Generated by {} ({})\n"
                "splines=ortho;\n"
                "nodesep=0.25;\n"
                "ranksep=0.125;\n"
                "rankdir=TB;\n"
                "\n"
                "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, orientation=30, style=filled];\n"
                "x0y0 [label=\"f1\", fillcolor=snow2];\n"
                "x1y0 [label=\"AND\", fillcolor=lightcoral];\n"
                "x2y0 [label=\"x1\", fillcolor=snow2];\n"
                "x3y0 [label=\"\", fillcolor=white];\n"
                "x0y1 [label=\"\", fillcolor=white];\n"
                "x1y1 [label=\"x2\", fillcolor=snow2];\n"
                "x2y1 [label=\"OR\", fillcolor=palegreen2];\n"
                "x3y1 [label=\"f2\", fillcolor=snow2];\n"
                "\n"
                "edge [constraint=false];\n"
                "x2y0 -> x1y0 [style=solid];\n"
                "x1y1 -> x1y0 [style=solid];\n"
                "x1y1 -> x2y1 [style=solid];\n"
                "x2y0 -> x2y1 [style=solid];\n"
                "x1y0 -> x0y0 [style=solid];\n"
                "x2y1 -> x3y1 [style=solid];\n"
                "\n"
                "edge [constraint=true, style=invis];\n"
                "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                "rank = same {{ x0y0 -> x1y0 -> x2y0 -> x3y0 }};\n"
                "rank = same {{ x0y1 -> x1y1 -> x2y1 -> x3y1 }};\n"
                "rank = same {{ invis1 -> x0y1 }};\n"
                "invis1 -> x0y0;\n"
                "x0y0 -> x0y1;\n"
                "x1y0 -> x0y1;\n"
                "x1y0 -> x1y1;\n"
                "x2y0 -> x1y1;\n"
                "x2y0 -> x2y1;\n"
                "x3y0 -> x2y1;\n"
                "x3y0 -> x3y1;\n"
                "}}\n",
                FICTION_VERSION, FICTION_REPO);

            compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout,
                                                                                                     layout_print);
        }
        SECTION("Crossing Layout")
        {
            const auto layout = blueprints::crossing_layout<gate_layout>(arr);

            static const std::string layout_print = fmt::format(
                "digraph layout {{  // Generated by {} ({})\n"
                "splines=ortho;\n"
                "nodesep=0.25;\n"
                "ranksep=0.125;\n"
                "rankdir=TB;\n"
                "\n"
                "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, orientation=30, style=filled];\n"
                "x0y0 [label=\"\", fillcolor=white];\n"
                "x1y0 [label=\"x1\", fillcolor=snow2];\n"
                "x2y0 [label=\"x3\", fillcolor=snow2];\n"
                "x3y0 [label=\"\", fillcolor=white];\n"
                "x0y1 [label=\"x2\", fillcolor=snow2];\n"
                "x1y1 [label=\"AND\", fillcolor=lightcoral];\n"
                "x2y1 [label=\"+\", fillcolor=palegoldenrod];\n"
                "x3y1 [label=\"f1\", fillcolor=snow2];\n"
                "x0y2 [label=\"x4\", fillcolor=snow2];\n"
                "x1y2 [label=\"BUF\", fillcolor=palegoldenrod];\n"
                "x2y2 [label=\"AND\", fillcolor=lightcoral];\n"
                "x3y2 [label=\"f2\", fillcolor=snow2];\n"
                "\n"
                "edge [constraint=false];\n"
                "x1y0 -> x1y1 [style=solid];\n"
                "x0y1 -> x1y1 [style=solid];\n"
                "x2y0 -> x2y1 [style=solid];\n"
                "x0y2 -> x1y2 [style=solid];\n"
                "x2y1 -> x2y2 [style=solid];\n"
                "x1y2 -> x2y2 [style=solid];\n"
                "x1y1 -> x2y1 [style=solid];\n"
                "x2y1 -> x3y1 [style=solid];\n"
                "x2y2 -> x3y2 [style=solid];\n"
                "\n"
                "edge [constraint=true, style=invis];\n"
                "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                "rank = same {{ x0y0 -> x1y0 -> x2y0 -> x3y0 }};\n"
                "rank = same {{ x0y1 -> x1y1 -> x2y1 -> x3y1 }};\n"
                "rank = same {{ x0y2 -> x1y2 -> x2y2 -> x3y2 }};\n"
                "rank = same {{ invis1 -> x0y1 }};\n"
                "invis1 -> x0y0;\n"
                "invis1 -> x0y2;\n"
                "x0y0 -> x0y1;\n"
                "x1y0 -> x0y1;\n"
                "x1y0 -> x1y1;\n"
                "x2y0 -> x1y1;\n"
                "x2y0 -> x2y1;\n"
                "x3y0 -> x2y1;\n"
                "x3y0 -> x3y1;\n"
                "x0y1 -> x0y2;\n"
                "x0y1 -> x1y2;\n"
                "x1y1 -> x1y2;\n"
                "x1y1 -> x2y2;\n"
                "x2y1 -> x2y2;\n"
                "x2y1 -> x3y2;\n"
                "x3y1 -> x3y2;\n"
                "}}\n",
                FICTION_VERSION, FICTION_REPO);

            compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout,
                                                                                                     layout_print);
        }
    }
    SECTION("even row")
    {
        using gate_layout  = gate_level_layout<hexagonal_layout>;
        constexpr auto arr = arrangement::EVEN_ROW;

        SECTION("AND-OR Layout")
        {
            const auto layout = blueprints::and_or_gate_layout<gate_layout>(arr);

            static const std::string layout_print = fmt::format(
                "digraph layout {{  // Generated by {} ({})\n"
                "splines=ortho;\n"
                "nodesep=0.25;\n"
                "ranksep=0.125;\n"
                "rankdir=TB;\n"
                "\n"
                "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, orientation=30, style=filled];\n"
                "x0y0 [label=\"f1\", fillcolor=snow2];\n"
                "x1y0 [label=\"AND\", fillcolor=lightcoral];\n"
                "x2y0 [label=\"x1\", fillcolor=snow2];\n"
                "x3y0 [label=\"\", fillcolor=white];\n"
                "x0y1 [label=\"\", fillcolor=white];\n"
                "x1y1 [label=\"x2\", fillcolor=snow2];\n"
                "x2y1 [label=\"OR\", fillcolor=palegreen2];\n"
                "x3y1 [label=\"f2\", fillcolor=snow2];\n"
                "\n"
                "edge [constraint=false];\n"
                "x2y0 -> x1y0 [style=solid];\n"
                "x1y1 -> x1y0 [style=solid];\n"
                "x1y1 -> x2y1 [style=solid];\n"
                "x2y0 -> x2y1 [style=solid];\n"
                "x1y0 -> x0y0 [style=solid];\n"
                "x2y1 -> x3y1 [style=solid];\n"
                "\n"
                "edge [constraint=true, style=invis];\n"
                "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                "rank = same {{ x0y0 -> x1y0 -> x2y0 -> x3y0 }};\n"
                "rank = same {{ x0y1 -> x1y1 -> x2y1 -> x3y1 }};\n"
                "rank = same {{ invis0 -> x0y0 }};\n"
                "invis0 -> x0y1;\n"
                "x0y0 -> x0y1;\n"
                "x0y0 -> x1y1;\n"
                "x1y0 -> x1y1;\n"
                "x1y0 -> x2y1;\n"
                "x2y0 -> x2y1;\n"
                "x2y0 -> x3y1;\n"
                "x3y0 -> x3y1;\n"
                "}}\n",
                FICTION_VERSION, FICTION_REPO);

            compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout,
                                                                                                     layout_print);
        }
        SECTION("Crossing Layout")
        {
            const auto layout = blueprints::crossing_layout<gate_layout>(arr);

            static const std::string layout_print = fmt::format(
                "digraph layout {{  // Generated by {} ({})\n"
                "splines=ortho;\n"
                "nodesep=0.25;\n"
                "ranksep=0.125;\n"
                "rankdir=TB;\n"
                "\n"
                "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, orientation=30, style=filled];\n"
                "x0y0 [label=\"\", fillcolor=white];\n"
                "x1y0 [label=\"x1\", fillcolor=snow2];\n"
                "x2y0 [label=\"x3\", fillcolor=snow2];\n"
                "x3y0 [label=\"\", fillcolor=white];\n"
                "x0y1 [label=\"x2\", fillcolor=snow2];\n"
                "x1y1 [label=\"AND\", fillcolor=lightcoral];\n"
                "x2y1 [label=\"+\", fillcolor=palegoldenrod];\n"
                "x3y1 [label=\"f1\", fillcolor=snow2];\n"
                "x0y2 [label=\"x4\", fillcolor=snow2];\n"
                "x1y2 [label=\"BUF\", fillcolor=palegoldenrod];\n"
                "x2y2 [label=\"AND\", fillcolor=lightcoral];\n"
                "x3y2 [label=\"f2\", fillcolor=snow2];\n"
                "\n"
                "edge [constraint=false];\n"
                "x1y0 -> x1y1 [style=solid];\n"
                "x0y1 -> x1y1 [style=solid];\n"
                "x2y0 -> x2y1 [style=solid];\n"
                "x0y2 -> x1y2 [style=solid];\n"
                "x2y1 -> x2y2 [style=solid];\n"
                "x1y2 -> x2y2 [style=solid];\n"
                "x1y1 -> x2y1 [style=solid];\n"
                "x2y1 -> x3y1 [style=solid];\n"
                "x2y2 -> x3y2 [style=solid];\n"
                "\n"
                "edge [constraint=true, style=invis];\n"
                "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                "rank = same {{ x0y0 -> x1y0 -> x2y0 -> x3y0 }};\n"
                "rank = same {{ x0y1 -> x1y1 -> x2y1 -> x3y1 }};\n"
                "rank = same {{ x0y2 -> x1y2 -> x2y2 -> x3y2 }};\n"
                "rank = same {{ invis0 -> x0y0 }};\n"
                "invis0 -> x0y1;\n"
                "rank = same {{ invis2 -> x0y2 }};\n"
                "invis2 -> x0y1;\n"
                "x0y0 -> x0y1;\n"
                "x0y0 -> x1y1;\n"
                "x1y0 -> x1y1;\n"
                "x1y0 -> x2y1;\n"
                "x2y0 -> x2y1;\n"
                "x2y0 -> x3y1;\n"
                "x3y0 -> x3y1;\n"
                "x0y1 -> x0y2;\n"
                "x1y1 -> x0y2;\n"
                "x1y1 -> x1y2;\n"
                "x2y1 -> x1y2;\n"
                "x2y1 -> x2y2;\n"
                "x3y1 -> x2y2;\n"
                "x3y1 -> x3y2;\n"
                "}}\n",
                FICTION_VERSION, FICTION_REPO);

            compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout,
                                                                                                     layout_print);
        }
    }
    SECTION("odd column")
    {
        using gate_layout  = gate_level_layout<hexagonal_layout>;
        constexpr auto arr = arrangement::ODD_COLUMN;

        SECTION("AND-OR Layout")
        {
            const auto layout = blueprints::and_or_gate_layout<gate_layout>(arr);

            static const std::string layout_print =
                fmt::format("digraph layout {{  // Generated by {} ({})\n"
                            "splines=ortho;\n"
                            "nodesep=0.25;\n"
                            "ranksep=0.125;\n"
                            "rankdir=LR;\n"
                            "\n"
                            "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, style=filled];\n"
                            "x0y0 [label=\"f1\", fillcolor=snow2];\n"
                            "x1y0 [label=\"AND\", fillcolor=lightcoral];\n"
                            "x2y0 [label=\"x1\", fillcolor=snow2];\n"
                            "x3y0 [label=\"\", fillcolor=white];\n"
                            "x0y1 [label=\"\", fillcolor=white];\n"
                            "x1y1 [label=\"x2\", fillcolor=snow2];\n"
                            "x2y1 [label=\"OR\", fillcolor=palegreen2];\n"
                            "x3y1 [label=\"f2\", fillcolor=snow2];\n"
                            "\n"
                            "edge [constraint=false];\n"
                            "x2y0 -> x1y0 [style=solid];\n"
                            "x1y1 -> x1y0 [style=solid];\n"
                            "x1y1 -> x2y1 [style=solid];\n"
                            "x2y0 -> x2y1 [style=solid];\n"
                            "x1y0 -> x0y0 [style=solid];\n"
                            "x2y1 -> x3y1 [style=solid];\n"
                            "\n"
                            "edge [constraint=true, style=invis];\n"
                            "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                            "rank = same {{ x0y0 -> x0y1 }};\n"
                            "rank = same {{ x1y0 -> x1y1 }};\n"
                            "rank = same {{ x2y0 -> x2y1 }};\n"
                            "rank = same {{ x3y0 -> x3y1 }};\n"
                            "rank = same {{ invis1 -> x1y0 }};\n"
                            "invis1 -> x0y0;\n"
                            "invis1 -> x2y0;\n"
                            "rank = same {{ invis3 -> x3y0 }};\n"
                            "invis3 -> x2y0;\n"
                            "x0y0 -> x1y0;\n"
                            "x1y0 -> x2y1;\n"
                            "x1y0 -> x2y0;\n"
                            "x1y0 -> x0y1;\n"
                            "x2y0 -> x3y0;\n"
                            "x3y0 -> x2y1;\n"
                            "x0y1 -> x1y1;\n"
                            "x1y1 -> x2y1;\n"
                            "x2y1 -> x3y1;\n"
                            "}}\n",
                            FICTION_VERSION, FICTION_REPO);

            compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout,
                                                                                                     layout_print);
        }
        SECTION("Crossing Layout")
        {
            const auto layout = blueprints::crossing_layout<gate_layout>(arr);

            static const std::string layout_print =
                fmt::format("digraph layout {{  // Generated by {} ({})\n"
                            "splines=ortho;\n"
                            "nodesep=0.25;\n"
                            "ranksep=0.125;\n"
                            "rankdir=LR;\n"
                            "\n"
                            "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, style=filled];\n"
                            "x0y0 [label=\"\", fillcolor=white];\n"
                            "x1y0 [label=\"x1\", fillcolor=snow2];\n"
                            "x2y0 [label=\"x3\", fillcolor=snow2];\n"
                            "x3y0 [label=\"\", fillcolor=white];\n"
                            "x0y1 [label=\"x2\", fillcolor=snow2];\n"
                            "x1y1 [label=\"AND\", fillcolor=lightcoral];\n"
                            "x2y1 [label=\"+\", fillcolor=palegoldenrod];\n"
                            "x3y1 [label=\"f1\", fillcolor=snow2];\n"
                            "x0y2 [label=\"x4\", fillcolor=snow2];\n"
                            "x1y2 [label=\"BUF\", fillcolor=palegoldenrod];\n"
                            "x2y2 [label=\"AND\", fillcolor=lightcoral];\n"
                            "x3y2 [label=\"f2\", fillcolor=snow2];\n"
                            "\n"
                            "edge [constraint=false];\n"
                            "x1y0 -> x1y1 [style=solid];\n"
                            "x0y1 -> x1y1 [style=solid];\n"
                            "x2y0 -> x2y1 [style=solid];\n"
                            "x0y2 -> x1y2 [style=solid];\n"
                            "x2y1 -> x2y2 [style=solid];\n"
                            "x1y2 -> x2y2 [style=solid];\n"
                            "x1y1 -> x2y1 [style=solid];\n"
                            "x2y1 -> x3y1 [style=solid];\n"
                            "x2y2 -> x3y2 [style=solid];\n"
                            "\n"
                            "edge [constraint=true, style=invis];\n"
                            "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                            "rank = same {{ x0y0 -> x0y1 -> x0y2 }};\n"
                            "rank = same {{ x1y0 -> x1y1 -> x1y2 }};\n"
                            "rank = same {{ x2y0 -> x2y1 -> x2y2 }};\n"
                            "rank = same {{ x3y0 -> x3y1 -> x3y2 }};\n"
                            "rank = same {{ invis1 -> x1y0 }};\n"
                            "invis1 -> x0y0;\n"
                            "invis1 -> x2y0;\n"
                            "rank = same {{ invis3 -> x3y0 }};\n"
                            "invis3 -> x2y0;\n"
                            "x0y0 -> x1y0;\n"
                            "x1y0 -> x2y1;\n"
                            "x1y0 -> x2y0;\n"
                            "x1y0 -> x0y1;\n"
                            "x2y0 -> x3y0;\n"
                            "x3y0 -> x2y1;\n"
                            "x0y1 -> x1y1;\n"
                            "x1y1 -> x2y2;\n"
                            "x1y1 -> x2y1;\n"
                            "x1y1 -> x0y2;\n"
                            "x2y1 -> x3y1;\n"
                            "x3y1 -> x2y2;\n"
                            "x0y2 -> x1y2;\n"
                            "x1y2 -> x2y2;\n"
                            "x2y2 -> x3y2;\n"
                            "}}\n",
                            FICTION_VERSION, FICTION_REPO);

            compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout,
                                                                                                     layout_print);
        }
    }
    SECTION("even column")
    {
        using gate_layout  = gate_level_layout<hexagonal_layout>;
        constexpr auto arr = arrangement::EVEN_COLUMN;

        SECTION("AND-OR Layout")
        {
            const auto layout = blueprints::and_or_gate_layout<gate_layout>(arr);

            static const std::string layout_print =
                fmt::format("digraph layout {{  // Generated by {} ({})\n"
                            "splines=ortho;\n"
                            "nodesep=0.25;\n"
                            "ranksep=0.125;\n"
                            "rankdir=LR;\n"
                            "\n"
                            "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, style=filled];\n"
                            "x0y0 [label=\"f1\", fillcolor=snow2];\n"
                            "x1y0 [label=\"AND\", fillcolor=lightcoral];\n"
                            "x2y0 [label=\"x1\", fillcolor=snow2];\n"
                            "x3y0 [label=\"\", fillcolor=white];\n"
                            "x0y1 [label=\"\", fillcolor=white];\n"
                            "x1y1 [label=\"x2\", fillcolor=snow2];\n"
                            "x2y1 [label=\"OR\", fillcolor=palegreen2];\n"
                            "x3y1 [label=\"f2\", fillcolor=snow2];\n"
                            "\n"
                            "edge [constraint=false];\n"
                            "x2y0 -> x1y0 [style=solid];\n"
                            "x1y1 -> x1y0 [style=solid];\n"
                            "x1y1 -> x2y1 [style=solid];\n"
                            "x2y0 -> x2y1 [style=solid];\n"
                            "x1y0 -> x0y0 [style=solid];\n"
                            "x2y1 -> x3y1 [style=solid];\n"
                            "\n"
                            "edge [constraint=true, style=invis];\n"
                            "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                            "rank = same {{ x0y0 -> x0y1 }};\n"
                            "rank = same {{ x1y0 -> x1y1 }};\n"
                            "rank = same {{ x2y0 -> x2y1 }};\n"
                            "rank = same {{ x3y0 -> x3y1 }};\n"
                            "rank = same {{ invis0 -> x0y0 }};\n"
                            "invis0 -> x1y0;\n"
                            "rank = same {{ invis2 -> x2y0 }};\n"
                            "invis2 -> x1y0;\n"
                            "invis2 -> x3y0;\n"
                            "x0y0 -> x1y1;\n"
                            "x0y0 -> x1y0;\n"
                            "x1y0 -> x2y0;\n"
                            "x2y0 -> x3y1;\n"
                            "x2y0 -> x3y0;\n"
                            "x2y0 -> x1y1;\n"
                            "x0y1 -> x1y1;\n"
                            "x1y1 -> x2y1;\n"
                            "x2y1 -> x3y1;\n"
                            "}}\n",
                            FICTION_VERSION, FICTION_REPO);

            compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout,
                                                                                                     layout_print);
        }
        SECTION("Crossing Layout")
        {
            const auto layout = blueprints::crossing_layout<gate_layout>(arr);

            static const std::string layout_print =
                fmt::format("digraph layout {{  // Generated by {} ({})\n"
                            "splines=ortho;\n"
                            "nodesep=0.25;\n"
                            "ranksep=0.125;\n"
                            "rankdir=LR;\n"
                            "\n"
                            "node [fixedsize=true, width=0.5, height=0.5, shape=hexagon, style=filled];\n"
                            "x0y0 [label=\"\", fillcolor=white];\n"
                            "x1y0 [label=\"x1\", fillcolor=snow2];\n"
                            "x2y0 [label=\"x3\", fillcolor=snow2];\n"
                            "x3y0 [label=\"\", fillcolor=white];\n"
                            "x0y1 [label=\"x2\", fillcolor=snow2];\n"
                            "x1y1 [label=\"AND\", fillcolor=lightcoral];\n"
                            "x2y1 [label=\"+\", fillcolor=palegoldenrod];\n"
                            "x3y1 [label=\"f1\", fillcolor=snow2];\n"
                            "x0y2 [label=\"x4\", fillcolor=snow2];\n"
                            "x1y2 [label=\"BUF\", fillcolor=palegoldenrod];\n"
                            "x2y2 [label=\"AND\", fillcolor=lightcoral];\n"
                            "x3y2 [label=\"f2\", fillcolor=snow2];\n"
                            "\n"
                            "edge [constraint=false];\n"
                            "x1y0 -> x1y1 [style=solid];\n"
                            "x0y1 -> x1y1 [style=solid];\n"
                            "x2y0 -> x2y1 [style=solid];\n"
                            "x0y2 -> x1y2 [style=solid];\n"
                            "x2y1 -> x2y2 [style=solid];\n"
                            "x1y2 -> x2y2 [style=solid];\n"
                            "x1y1 -> x2y1 [style=solid];\n"
                            "x2y1 -> x3y1 [style=solid];\n"
                            "x2y2 -> x3y2 [style=solid];\n"
                            "\n"
                            "edge [constraint=true, style=invis];\n"
                            "node [label=\"\", width=0.5, height=0.5, style=invis];\n"
                            "rank = same {{ x0y0 -> x0y1 -> x0y2 }};\n"
                            "rank = same {{ x1y0 -> x1y1 -> x1y2 }};\n"
                            "rank = same {{ x2y0 -> x2y1 -> x2y2 }};\n"
                            "rank = same {{ x3y0 -> x3y1 -> x3y2 }};\n"
                            "rank = same {{ invis0 -> x0y0 }};\n"
                            "invis0 -> x1y0;\n"
                            "rank = same {{ invis2 -> x2y0 }};\n"
                            "invis2 -> x1y0;\n"
                            "invis2 -> x3y0;\n"
                            "x0y0 -> x1y1;\n"
                            "x0y0 -> x1y0;\n"
                            "x1y0 -> x2y0;\n"
                            "x2y0 -> x3y1;\n"
                            "x2y0 -> x3y0;\n"
                            "x2y0 -> x1y1;\n"
                            "x0y1 -> x1y2;\n"
                            "x0y1 -> x1y1;\n"
                            "x1y1 -> x2y1;\n"
                            "x2y1 -> x3y2;\n"
                            "x2y1 -> x3y1;\n"
                            "x2y1 -> x1y2;\n"
                            "x0y2 -> x1y2;\n"
                            "x1y2 -> x2y2;\n"
                            "x2y2 -> x3y2;\n"
                            "}}\n",
                            FICTION_VERSION, FICTION_REPO);

            compare_dot_layout<gate_layout, gate_layout_hexagonal_drawer<gate_layout, false, false>>(layout,
                                                                                                     layout_print);
        }
    }
}

TEST_CASE("Network DOT export preserves files and symbolic links", "[dot-drawers]")
{
    const auto directory =
        std::filesystem::temp_directory_path() / ("fiction-dot-test-" + std::to_string(std::random_device{}()));
    REQUIRE(std::filesystem::create_directory(directory));
    const auto target = directory / "network.dot";
    {
        std::ofstream stream{target};
        stream << "original";
    }
    auto       destination = target;
    const auto symbolic    = GENERATE(false, true);
    if (symbolic)
    {
        destination = directory / "latest.dot";
        std::error_code link_error{};
        std::filesystem::create_symlink(target.filename(), destination, link_error);
#ifdef _WIN32
        if (link_error.value() == 1314)  // Windows requires symbolic-link creation privileges.
        {
            std::filesystem::remove_all(directory);
            SKIP("Windows did not grant symbolic-link creation privileges");
        }
#endif
        REQUIRE_FALSE(link_error);
    }
#ifndef _WIN32
    const auto permissions = std::filesystem::perms::owner_read | std::filesystem::perms::owner_write;
    std::filesystem::permissions(target, permissions);
#endif
    mockturtle::aig_network network{};
    network.create_po(network.create_pi());
    CHECK_THROWS_AS(write_dot_network(network, destination.string(), failing_dot_drawer{}), std::runtime_error);
    {
        std::ifstream     stream{target};
        const std::string content{std::istreambuf_iterator<char>{stream}, std::istreambuf_iterator<char>{}};
        CHECK(content == "original");
    }
    write_dot_network(network, destination.string());
    {
        std::stringstream expected{};
        write_dot_network(network, expected);
        std::ifstream     stream{target};
        const std::string content{std::istreambuf_iterator<char>{stream}, std::istreambuf_iterator<char>{}};
        CHECK(content == expected.str());
    }
#ifndef _WIN32
    CHECK(std::filesystem::status(target).permissions() == permissions);
#endif
    if (destination != target)
    {
        CHECK(std::filesystem::is_symlink(destination));
        std::filesystem::remove(target);
        CHECK_THROWS_AS(write_dot_network(network, destination.string()), std::ios_base::failure);
        CHECK(std::filesystem::is_symlink(destination));
        CHECK_FALSE(std::filesystem::exists(target));
    }
    std::filesystem::remove_all(directory);
}

TEST_CASE("Draw object identities and constants", "[dot-drawers]")
{
    using gate_layout = gate_level_layout<cartesian_layout>;
    gate_layout layout{{2, 1}};
    const auto  constant = layout.create_node({}, kitty::dynamic_truth_table{0}, {0, 0});
    const auto  wire     = layout.create_buf(constant, {1, 0});
    const gate_layout_cartesian_drawer<gate_layout, false, true> drawer{};
    CHECK(drawer.tile_label(layout, {0, 0}) ==
          fmt::format("{}:{}: 0", constant.object.index, constant.object.generation));
    CHECK(drawer.tile_label(layout, {1, 0}) == fmt::format("{}:{}: BUF", wire.object.index, wire.object.generation));
    CHECK(drawer.tile_fillcolor(layout, {0, 0}) == "white");
}

TEST_CASE("Layout DOT identifiers serialize signed coordinate boundaries", "[dot-drawers]")
{
    /** Gate layout under test. */
    using gate_layout = gate_level_layout<cartesian_layout>;
    const gate_layout_cartesian_drawer<gate_layout> drawer{};
    // DOT permits bare identifiers, numerals, quoted strings, and HTML strings.
    const std::regex identifier{
        R"dot(([A-Za-z_][A-Za-z_0-9]*|-?([0-9]+(\.[0-9]*)?|\.[0-9]+)|"([^"\\]|\\.)*"|<.*>))dot"};
    const auto            minimum = std::numeric_limits<int32_t>::min();
    const auto            maximum = std::numeric_limits<int32_t>::max();
    std::set<std::string> ids{};
    for (const auto coordinate :
         {gate_layout::tile{minimum, maximum}, gate_layout::tile{maximum, minimum}, gate_layout::tile{-1, 0},
          gate_layout::tile{0, -1}, gate_layout::tile{1, 0}, gate_layout::tile{0, 1}})
    {
        const auto id = drawer.tile_id(coordinate);
        CHECK(std::regex_match(id, identifier));
        CHECK(ids.insert(id).second);
    }

    gate_layout       layout{{1, 1}};
    const auto        input  = layout.create_pi("a", {minimum, maximum});
    const auto        output = layout.create_buf(input, {0, 0});
    std::stringstream stream{};
    write_dot_layout<gate_layout, gate_layout_cartesian_drawer<gate_layout>>(layout, stream);
    const auto source_id = drawer.tile_id(layout.get_tile(input.object));
    const auto target_id = drawer.tile_id(layout.get_tile(output.object));
    CHECK(std::regex_match(source_id, identifier));
    CHECK(std::regex_match(target_id, identifier));
    CHECK(stream.str().find(source_id + " -> " + target_id + " [style=solid]") != std::string::npos);
    CHECK(stream.str().find(target_id + " [label=") != std::string::npos);
}

TEST_CASE("Layout DOT labels preserve terminal names", "[dot-drawers]")
{
    /** Gate layout under test. */
    using gate_layout = gate_level_layout<cartesian_layout>;
    gate_layout       layout{{1, 1}};
    const std::string name{"a\"\nb\\c"};
    layout.create_pi(name, {0, 0});
    std::stringstream stream{};
    write_dot_layout<gate_layout, gate_layout_cartesian_drawer<gate_layout>>(layout, stream);
    const auto label_start = stream.str().find(" [label=");
    REQUIRE(label_start != std::string::npos);
    std::istringstream label_stream{stream.str().substr(label_start + std::string_view{" [label="}.size())};
    std::string        restored_name{};
    label_stream >> std::quoted(restored_name);
    CHECK_FALSE(label_stream.fail());
    CHECK(restored_name == name);
}

TEST_CASE("Layout DOT progress retains areas above the unsigned 32-bit range", "[dot-drawers]")
{
    /** Gate layout under test. */
    using gate_layout = gate_level_layout<cartesian_layout>;
    /** Interrupts rendering after progress starts to avoid enumerating the large frame. */
    struct interrupted_drawer : gate_layout_cartesian_drawer<gate_layout>
    {
        /**
         * @brief Stops drawing at the first tile.
         * @throws std::runtime_error Always interrupts drawing.
         */
        [[nodiscard]] std::string tile_label(const gate_layout&, const gate_layout::tile&) const override
        {
            throw std::runtime_error{"drawing interrupted"};
        }
    };
    const gate_layout layout{{65536, 65536}};
    std::size_t       total{};
    std::stringstream stream{};
    const auto        progress = [&total](std::string_view, std::size_t, const std::size_t count) { total = count; };
    CHECK_THROWS_AS((write_dot_layout<gate_layout, interrupted_drawer>(layout, stream, {}, progress)),
                    std::runtime_error);
    CHECK(total == layout.area());
}
