version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    groups:
      submodules:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Berlin"
    assignees:
      - "marcelwa"

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Berlin"
    assignees:
      - "marcelwa"

  - package-ecosystem: "pip"
    directory: "/docs/"
    groups:
      documentation:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Berlin"
    assignees:
      - "marcelwa"

  - package-ecosystem: "docker"
    directory: "/"
    groups:
      docker:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Berlin"
    assignees:
      - "marcelwa"
