version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - cmake
  jobs:
    pre_build:
      - echo "Reinstall pyfiction with Z3 and ALGLIB enabled"
      - z3="ON" alglib="ON" python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .[docs]

sphinx:
  configuration: docs/conf.py

formats: []

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
