version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - cmake
  jobs:
    pre_create_environment:
      - echo "Setup ALGLIB"
      - git clone https://github.com/S-Dafarra/alglib-cmake.git
        && cd alglib-cmake && mkdir build && cd build
        && cmake .. && make -j4 && export DESTDIR="$PWD" && make install && cd ../..
    pre_build:
      - echo "Reinstall pyfiction with Z3 and ALGLIB enabled"
      - echo $PWD
      - ls ./alglib-cmake/build
      - z3="ON" alglib="ON" ALGLIB_DIR=$PWD/alglib-cmake/build/usr/local/lib/cmake/ALGLIB/ python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .[docs]

sphinx:
  configuration: docs/conf.py

formats: [ ]

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
