version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

  jobs:
    post_checkout:
      # Skip docs build if the commit message contains "skip ci"
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip ci") || exit 183
      # Skip docs build if there are no changes related to docs
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml include/fiction/ bindings/mnt/ .github/contributing* .github/support*;
        then
          exit 183;
        fi
      # Unshallow the git clone and fetch tags to get proper version information
      - git fetch --unshallow --tags
      # Ensure submodules are checked out
      - git submodule update --init --recursive
    pre_build:
      # Set up uv
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    build:
      html:
        - uv run --frozen --no-dev --group docs -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
