version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-24.04
  apt_packages:
    - mold
  tools:
    python: "3.12"

  jobs:
    post_checkout:
      # Skip docs build if the commit message contains "skip ci"
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip ci") || exit 183
      # Skip docs build if there are no changes related to docs
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml pyproject.toml include/fiction/ bindings/mnt/;
        then
          exit 183;
        fi
      # Unshallow the git clone and fetch tags to get proper version information
      - git fetch --unshallow --tags
    pre_build:
      # Set up uv
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    build:
      html:
        - SKBUILD_LOGGING_LEVEL=INFO SKBUILD_CMAKE_DEFINE="FICTION_ENABLE_IPO=OFF" SKBUILD_CMAKE_ARGS="-DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_MODULE_LINKER_FLAGS=-fuse-ld=mold -DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=mold -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=mold" uv run -v --frozen --no-dev --group docs -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
