# Copyright (c) 2018 - 2023 Marcel Walter
# Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

"""Truth tables and logic network transformations."""

from __future__ import annotations

from mnt.pyfiction._native.synthesis import (
    all_standard_2_input_functions,
    all_standard_3_input_functions,
    all_supported_standard_functions,
    and_or_not,
    and_or_not_maj,
    convert_network,
    create_and3_tt,
    create_and_tt,
    create_and_xor_tt,
    create_crossing_wire_tt,
    create_dot_tt,
    create_double_wire_tt,
    create_fan_out_tt,
    create_gamble_tt,
    create_ge_tt,
    create_gt_tt,
    create_half_adder_tt,
    create_id_tt,
    create_ite_tt,
    create_le_tt,
    create_lt_tt,
    create_maj_tt,
    create_nand_tt,
    create_nor_tt,
    create_not_tt,
    create_onehot_tt,
    create_or_and_tt,
    create_or_tt,
    create_xnor_tt,
    create_xor3_tt,
    create_xor_and_tt,
    create_xor_tt,
    dynamic_truth_table,
    fanout_substitution,
    fanout_substitution_params,
    is_balanced,
    is_fanout_substituted,
    mapper_stats,
    missing_required_gates_exception,
    network_balancing,
    network_balancing_params,
    network_target,
    substitution_strategy,
    technology_mapping,
    technology_mapping_params,
    technology_mapping_stats,
)

__all__ = [
    "all_standard_2_input_functions",
    "all_standard_3_input_functions",
    "all_supported_standard_functions",
    "and_or_not",
    "and_or_not_maj",
    "convert_network",
    "create_and3_tt",
    "create_and_tt",
    "create_and_xor_tt",
    "create_crossing_wire_tt",
    "create_dot_tt",
    "create_double_wire_tt",
    "create_fan_out_tt",
    "create_gamble_tt",
    "create_ge_tt",
    "create_gt_tt",
    "create_half_adder_tt",
    "create_id_tt",
    "create_ite_tt",
    "create_le_tt",
    "create_lt_tt",
    "create_maj_tt",
    "create_nand_tt",
    "create_nor_tt",
    "create_not_tt",
    "create_onehot_tt",
    "create_or_and_tt",
    "create_or_tt",
    "create_xnor_tt",
    "create_xor3_tt",
    "create_xor_and_tt",
    "create_xor_tt",
    "dynamic_truth_table",
    "fanout_substitution",
    "fanout_substitution_params",
    "is_balanced",
    "is_fanout_substituted",
    "mapper_stats",
    "missing_required_gates_exception",
    "network_balancing",
    "network_balancing_params",
    "network_target",
    "substitution_strategy",
    "technology_mapping",
    "technology_mapping_params",
    "technology_mapping_stats",
]
