/*
 * Copyright (c) 2018 - 2023 Marcel Walter
 * Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
 * All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License
 */

/**
 * @file
 * @brief Iterates a BDL layout over all of its input patterns.
 * @author Marcel Walter (marcelwa)
 * @author Jan Drewniok (Drewniok)
 */

#pragma once

#include "fiction/technology/sidb/lattice.hpp"
#include "fiction/technology/sidb/layout.hpp"
#include "fiction/technology/sidb/simulation/logic/detect_bdl_pairs.hpp"
#include "fiction/technology/sidb/simulation/logic/detect_bdl_wires.hpp"
#include "fiction/technology/sidb/technology.hpp"
#include "fiction/traits.hpp"

#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <vector>

namespace fiction::sidb::simulation::logic
{

/**
 * Parameters for the BDL input iterator.
 */
struct bdl_input_iterator_params
{
    /**
     * This enum defines how BDL inputs are manipulated within the algorithm.
     * According to existing literature, there are two main approaches for handling BDL inputs:
     *
     * 1. Distance Encoding, in which an input of `1` is generated by placing a perturber closer to the target, whereas
     * a `0` is produced by positioning the perturber farther away (as described in
     * https://dl.acm.org/doi/10.1145/3489517.3530525).
     * 2. Absence Encoding, in which a perturber is used to set the input to `1`, while the absence of a perturber
     * represents a `0` (as described in https://ieeexplore.ieee.org/abstract/document/8963859).
     */
    enum class input_bdl_configuration : uint8_t
    {
        /**
         * An input of `1` is generated by placing a perturber closer to the BDL wire, whereas a `0` is produced
         * by positioning the perturber farther away (as described in https://dl.acm.org/doi/10.1145/3489517.3530525).
         */
        PERTURBER_DISTANCE_ENCODED,
        /**
         * A perturber is used to set the input to `1`, while the absence of a perturber represents a `0`
         * (as described in https://ieeexplore.ieee.org/abstract/document/8963859).
         */
        PERTURBER_ABSENCE_ENCODED
    };
    /**
     * Parameters to detect BDL wires.
     */
    detect_bdl_wires_params bdl_wire_params{};
    /**
     * The `input_bdl_config` member allows selection between different modes for handling input BDLs.
     */
    input_bdl_configuration input_bdl_config{input_bdl_configuration::PERTURBER_DISTANCE_ENCODED};
};

/**
 * Iterator that assigns the input patterns to the input BDL pairs of an SiDB layout. Incrementing the iterator
 * advances the input pattern; dereferencing it yields the layout with that pattern applied. Every input BDL pair
 * encodes one bit: a `1` keeps the SiDB closer to the wire's end, a `0` keeps the other one (perturber-distance
 * encoding) or none (perturber-absence encoding). Bit `i` of the pattern belongs to the `i`-th input pair in
 * layout order, with the first pair as the most significant bit.
 */
class bdl_input_iterator
{
  public:
    /**
     * Detects the input BDL pairs and wires of `source_layout` and applies input pattern `0`.
     *
     * @param source_layout The layout to iterate over.
     * @param ps Parameters for the BDL pair and wire detection and the input encoding.
     */
    explicit bdl_input_iterator(const layout& source_layout, const bdl_input_iterator_params& ps = {}) noexcept :
            bdl_input_iterator{source_layout, ps,
                               detect_bdl_wires(source_layout, ps.bdl_wire_params, bdl_wire_selection::INPUT)}
    {}
    /**
     * Like the constructor above but with input wires that are already known.
     *
     * @param source_layout The layout to iterate over.
     * @param ps Parameters for the BDL pair detection and the input encoding.
     * @param source_input_wires The input wires of `source_layout`.
     */
    bdl_input_iterator(const layout& source_layout, const bdl_input_iterator_params& ps,
                       const std::vector<bdl_wire>& source_input_wires) noexcept :
            sidb_layout{source_layout},
            input_pairs{detect_bdl_pairs(source_layout, sidb_technology::cell_type::INPUT,
                                         ps.bdl_wire_params.bdl_pairs_params)},
            detected_input_wires{source_input_wires},
            last_bdl_for_each_wire{determine_last_bdl_for_each_wire()},
            upper_input_closer_to_wire_end{determine_upper_input_closer_to_wire_end()},
            params{ps}
    {
        set_all_inputs();
    }
    /**
     * The layout with the current input pattern applied.
     *
     * @return The layout.
     */
    [[nodiscard]] const layout& operator*() const noexcept
    {
        return sidb_layout;
    }
    /**
     * Advances to the next input pattern.
     *
     * @return Reference to `this`.
     */
    bdl_input_iterator& operator++() noexcept
    {
        ++current_input_index;
        set_all_inputs();

        return *this;
    }
    /**
     * Advances to the next input pattern.
     *
     * @return Copy of `this` before the increment.
     */
    bdl_input_iterator operator++(int) noexcept
    {
        auto result{*this};
        ++(*this);

        return result;
    }
    /**
     * Returns an iterator `m` patterns ahead.
     *
     * @param m The number of patterns to advance.
     * @return The advanced iterator.
     */
    [[nodiscard]] bdl_input_iterator operator+(const int m) const noexcept
    {
        auto result{*this};
        result += m;

        return result;
    }
    /**
     * Advances by `m` patterns.
     *
     * @param m The number of patterns to advance.
     * @return Reference to `this`.
     */
    bdl_input_iterator& operator+=(const int m) noexcept
    {
        current_input_index = static_cast<uint64_t>(static_cast<int64_t>(current_input_index) + m);
        set_all_inputs();

        return *this;
    }
    /**
     * Returns an iterator `m` patterns behind.
     *
     * @param m The number of patterns to go back.
     * @return The iterator.
     */
    [[nodiscard]] bdl_input_iterator operator-(const int m) const noexcept
    {
        auto result{*this};
        result -= m;

        return result;
    }
    /**
     * Goes back to the previous input pattern.
     *
     * @return Reference to `this`.
     */
    bdl_input_iterator& operator--() noexcept
    {
        --current_input_index;
        set_all_inputs();

        return *this;
    }
    /**
     * Goes back to the previous input pattern.
     *
     * @return Copy of `this` before the decrement.
     */
    bdl_input_iterator operator--(int) noexcept
    {
        auto result{*this};
        --(*this);

        return result;
    }
    /**
     * Goes back by `m` patterns.
     *
     * @param m The number of patterns to go back.
     * @return Reference to `this`.
     */
    bdl_input_iterator& operator-=(const int m) noexcept
    {
        current_input_index = static_cast<uint64_t>(static_cast<int64_t>(current_input_index) - m);
        set_all_inputs();

        return *this;
    }
    /**
     * Jumps to input pattern `m`.
     *
     * @param m The input pattern.
     * @return Reference to `this`.
     */
    bdl_input_iterator& operator=(const uint64_t m) noexcept
    {
        current_input_index = m;
        set_all_inputs();

        return *this;
    }
    /**
     * Returns an iterator `m` patterns ahead.
     *
     * @param m The number of patterns to advance.
     * @return The advanced iterator.
     */
    [[nodiscard]] bdl_input_iterator operator[](const int m) const noexcept
    {
        return *this + m;
    }
    /**
     * Distance between two iterators in input patterns.
     *
     * @param other The other iterator.
     * @return `this` pattern minus `other`'s pattern.
     */
    [[nodiscard]] int64_t operator-(const bdl_input_iterator& other) const noexcept
    {
        return static_cast<int64_t>(current_input_index) - static_cast<int64_t>(other.current_input_index);
    }
    /**
     * Compares the current input pattern with `m`.
     *
     * @param m The pattern to compare with.
     * @return The three-way comparison result.
     */
    [[nodiscard]] auto operator<=>(const uint64_t m) const noexcept
    {
        return current_input_index <=> m;
    }
    /**
     * Whether the current input pattern is `m`.
     *
     * @param m The pattern to compare with.
     * @return `true` if the patterns are equal.
     */
    [[nodiscard]] bool operator==(const uint64_t m) const noexcept
    {
        return current_input_index == m;
    }
    /**
     * Number of input BDL pairs.
     *
     * @return The number of input pairs.
     */
    [[nodiscard]] uint64_t num_input_pairs() const noexcept
    {
        return input_pairs.size();
    }
    /**
     * Whether every input BDL pair belongs to a complete detected wire.
     *
     * @return `true` if input patterns can be applied.
     */
    [[nodiscard]] bool is_valid() const noexcept
    {
        return input_pairs.size() == detected_input_wires.size() &&
               input_pairs.size() == last_bdl_for_each_wire.size() &&
               input_pairs.size() == upper_input_closer_to_wire_end.size();
    }
    /**
     * The current input pattern.
     *
     * @return The pattern.
     */
    [[nodiscard]] uint64_t get_current_input_index() const noexcept
    {
        return current_input_index;
    }

  private:
    /**
     * The layout with the current input pattern applied.
     */
    layout sidb_layout;
    /**
     * The input BDL pairs in layout order.
     */
    std::vector<bdl_pair<lattice_site>> input_pairs;
    /**
     * The input wires.
     */
    std::vector<bdl_wire> detected_input_wires;
    /**
     * For each input wire, the BDL pair farthest from its input pair.
     */
    std::vector<bdl_pair<lattice_site>> last_bdl_for_each_wire;
    /**
     * For each input pair, whether its upper SiDB is the one closer to the wire's end.
     */
    std::vector<bool> upper_input_closer_to_wire_end;
    /**
     * The current input pattern.
     */
    uint64_t current_input_index{0};
    /**
     * Parameters.
     */
    bdl_input_iterator_params params;
    /**
     * Finds, for each input wire, the BDL pair farthest from the wire's input pair.
     *
     * @return One pair per wire.
     */
    [[nodiscard]] std::vector<bdl_pair<lattice_site>> determine_last_bdl_for_each_wire() const noexcept
    {
        const auto& lat = sidb_layout.get_lattice();

        std::vector<bdl_pair<lattice_site>> end_bdls{};
        end_bdls.reserve(detected_input_wires.size());

        for (const auto& wire : detected_input_wires)
        {
            const auto start = std::ranges::find_if(wire.pairs, [](const auto& bdl)
                                                    { return bdl.type == sidb_technology::cell_type::INPUT; });

            if (start == wire.pairs.cend())
            {
                continue;
            }

            const auto farthest = std::ranges::max_element(
                wire.pairs, [&lat, &start](const auto& a, const auto& b)
                { return lat.nm_distance(start->upper, a.upper) < lat.nm_distance(start->upper, b.upper); });

            if (farthest != wire.pairs.cend())
            {
                end_bdls.push_back(*farthest);
            }
        }

        return end_bdls;
    }
    /**
     * Determines for each input pair whether its upper SiDB is closer to the end of its wire than its lower one.
     *
     * @return One flag per input pair.
     */
    [[nodiscard]] std::vector<bool> determine_upper_input_closer_to_wire_end() const noexcept
    {
        const auto& lat = sidb_layout.get_lattice();

        std::vector<bool> upper_is_closer{};
        upper_is_closer.reserve(input_pairs.size());

        if (input_pairs.size() != last_bdl_for_each_wire.size())
        {
            return upper_is_closer;
        }

        for (std::size_t i = 0; i < input_pairs.size(); ++i)
        {
            const auto& input_i = input_pairs[i];
            // both distances are measured against the upper dot of the wire's last BDL pair
            const auto to_upper = lat.nm_distance(input_i.upper, last_bdl_for_each_wire[i].upper);
            const auto to_lower = lat.nm_distance(input_i.lower, last_bdl_for_each_wire[i].upper);

            upper_is_closer.push_back(to_upper < to_lower);
        }

        return upper_is_closer;
    }
    /**
     * Applies the current input pattern to the input pairs.
     */
    void set_all_inputs() noexcept
    {
        if (!is_valid())
        {
            return;
        }

        const auto num_inputs = input_pairs.size();

        for (std::size_t i = 0; i < num_inputs; ++i)
        {
            const auto& input_i = input_pairs[i];

            const bool bit_set = (current_input_index & (uint64_t{1} << (num_inputs - 1 - i))) != 0;

            if (bit_set)
            {
                if (upper_input_closer_to_wire_end[i])
                {
                    sidb_layout.assign_cell_type(input_i.lower, sidb_technology::cell_type::EMPTY);
                    sidb_layout.assign_cell_type(input_i.upper, sidb_technology::cell_type::INPUT);
                }
                else
                {
                    sidb_layout.assign_cell_type(input_i.lower, sidb_technology::cell_type::INPUT);
                    sidb_layout.assign_cell_type(input_i.upper, sidb_technology::cell_type::EMPTY);
                }
            }
            else if (params.input_bdl_config ==
                     bdl_input_iterator_params::input_bdl_configuration::PERTURBER_DISTANCE_ENCODED)
            {
                if (upper_input_closer_to_wire_end[i])
                {
                    sidb_layout.assign_cell_type(input_i.lower, sidb_technology::cell_type::INPUT);
                    sidb_layout.assign_cell_type(input_i.upper, sidb_technology::cell_type::EMPTY);
                }
                else
                {
                    sidb_layout.assign_cell_type(input_i.lower, sidb_technology::cell_type::EMPTY);
                    sidb_layout.assign_cell_type(input_i.upper, sidb_technology::cell_type::INPUT);
                }
            }
            else
            {
                sidb_layout.assign_cell_type(input_i.upper, sidb_technology::cell_type::EMPTY);
                sidb_layout.assign_cell_type(input_i.lower, sidb_technology::cell_type::EMPTY);
            }
        }
    }
};

/**
 * Applies every input pattern to the input BDL pairs of a layout and returns the resulting layouts, pattern `0`
 * first, with the input wires given by the caller.
 *
 * @param lyt The layout.
 * @param ps Parameters for the BDL pair detection and the input encoding.
 * @param input_wires The input wires of `lyt`.
 * @return One layout per input pattern.
 */
[[nodiscard]] inline std::vector<layout>
generate_bdl_input_pattern_layouts(const layout& lyt, const bdl_input_iterator_params& ps,
                                   const std::vector<bdl_wire>& input_wires) noexcept
{
    bdl_input_iterator bii{lyt, ps, input_wires};

    if (!bii.is_valid())
    {
        return {};
    }

    assert(bii.num_input_pairs() < 64 && "too many input BDL pairs to enumerate");

    const auto num_input_patterns = uint64_t{1} << bii.num_input_pairs();

    std::vector<layout> layouts{};
    layouts.reserve(num_input_patterns);

    for (bii = 0; bii < num_input_patterns; ++bii)
    {
        layouts.push_back(*bii);
    }

    return layouts;
}
/**
 * Applies every input pattern to the input BDL pairs of a layout and returns the resulting layouts, pattern `0`
 * first; the input wires are detected first.
 *
 * @param lyt The layout.
 * @param ps Parameters for the BDL detection and the input encoding.
 * @return One layout per input pattern.
 */
[[nodiscard]] inline std::vector<layout>
generate_bdl_input_pattern_layouts(const layout& lyt, const bdl_input_iterator_params& ps = {}) noexcept
{
    return generate_bdl_input_pattern_layouts(lyt, ps,
                                              detect_bdl_wires(lyt, ps.bdl_wire_params, bdl_wire_selection::INPUT));
}

namespace detail
{}  // namespace detail

}  // namespace fiction::sidb::simulation::logic
// make the input iterators compatible with STL iterator categories
namespace std
{
template <>
struct iterator_traits<fiction::sidb::simulation::logic::bdl_input_iterator>
{
    using iterator_category = std::random_access_iterator_tag;
    using difference_type   = int64_t;
    using value_type        = fiction::sidb::layout;
};
}  // namespace std
