/*
 * Copyright (c) 2018 - 2023 Marcel Walter
 * Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
 * All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License
 */

/**
 * @file
 * @brief Tests for `fiction/technology/sidb/io/write_sidb_layout_svg.hpp`.
 * @author Jan Drewniok (Drewniok)
 * @author Marcel Walter (marcelwa)
 * @author Benjamin Hien (hibenj)
 */

#include <catch2/catch_test_macros.hpp>

#include "fiction/utils/version_info.hpp"

#include <fiction/technology/sidb/charge_distribution.hpp>
#include <fiction/technology/sidb/io/write_sidb_layout_svg.hpp>
#include <fiction/technology/sidb/lattice.hpp>
#include <fiction/technology/sidb/layout.hpp>
#include <fiction/technology/sidb/model/charge_state.hpp>
#include <fiction/technology/sidb/technology.hpp>

#include <fmt/format.h>

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

using namespace fiction;
using namespace fiction::sidb;
using namespace fiction::sidb::io;
using namespace fiction::sidb::model;

/**
 * Removes whitespace from an SVG string for comparison.
 *
 * @param svg SVG string.
 * @return SVG without whitespace.
 */
[[nodiscard]] static std::string normalize_svg(const std::string& svg)
{
    std::string result = svg;
    std::erase_if(result, [](const unsigned char c) { return std::isspace(c) != 0; });
    return result;
}

/**
 * Separates charge-marker elements from an SVG document and sorts them for order-independent comparison.
 *
 * @param svg SVG document.
 * @return The normalized document without charge markers and the sorted charge-marker elements.
 * @throws std::invalid_argument if a charge-marker element is not closed.
 */
[[nodiscard]] static std::pair<std::string, std::vector<std::string>> parse_svg_charge_elements(const std::string& svg)
{
    constexpr std::string_view marker{R"(<use xlink:href="#sidb_color")"};

    std::string              document = normalize_svg(svg);
    std::vector<std::string> elements{};

    for (auto begin = document.find(marker); begin != std::string::npos; begin = document.find(marker))
    {
        const auto end = document.find("/>", begin);
        if (end == std::string::npos)
        {
            throw std::invalid_argument{"unclosed SiDB charge marker"};
        }

        elements.emplace_back(document.substr(begin, end + 2 - begin));
        document.erase(begin, end + 2 - begin);
    }

    std::ranges::sort(elements);

    return {std::move(document), std::move(elements)};
}

inline const std::string EXPECTED_SVG_LIGHT_CELL_LEVEL =
    fmt::format(R"(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by {} ({}) -->
<svg
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:cc="http://creativecommons.org/ns#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 19.2 23.04"
    version="1.1">
    <metadata>
        <rdf:RDF>
            <cc:Work rdf:about="">
                <dc:format>image/svg+xml</dc:format>
                <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
                <dc:title></dc:title>
            </cc:Work>
        </rdf:RDF>
    </metadata>

<defs>
    <!-- lattice point -->
    <circle id="lattice_point" cx="0" cy="0" r="0.3"/>
    <!-- SiDB -->
    <circle id="sidb_color" cx="0" cy="0" r="0.9"/>
</defs>
 <!-- PATH_DEFINITION placeholder -->
    <rect x="0" y="0" width="19.2" height="23.04" style="fill:#ffffff;"/> <!-- Background rectangle placeholder -->
    <g>
        <use xlink:href="#lattice_point" x="3.84" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="7.68" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="11.52" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="15.36" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="3.84" y="9.93" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="7.68" y="9.93" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="11.52" y="9.93" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="15.36" y="9.93" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="3.84" y="15.36" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="7.68" y="15.36" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="11.52" y="15.36" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="15.36" y="15.36" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="3.84" y="17.61" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="7.68" y="17.61" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="11.52" y="17.61" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="15.36" y="17.61" style="fill:#6e7175;"/><use xlink:href="#sidb_color" x="3.84" y="7.68" style="fill:#ffffff; fill-opacity:1; stroke:#C8C8C8; stroke-width:0.3;"/><use xlink:href="#sidb_color" x="7.68" y="7.68" style="fill:#ffffff; fill-opacity:1; stroke:#C8C8C8; stroke-width:0.3;"/><use xlink:href="#sidb_color" x="7.68" y="9.93" style="fill:#ffffff; fill-opacity:1; stroke:#C8C8C8; stroke-width:0.3;"/><use xlink:href="#sidb_color" x="15.36" y="17.61" style="fill:#ffffff; fill-opacity:1; stroke:#C8C8C8; stroke-width:0.3;"/> <!-- SVG content placeholder -->
    </g>
</svg>)",
                FICTION_VERSION, FICTION_REPO);

inline const std::string EXPECTED_SVG_LIGHT_CELL_LEVEL_111 =
    fmt::format(R"(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by {} ({}) -->
<svg
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:cc="http://creativecommons.org/ns#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 33.25 11.52"
    version="1.1">
    <metadata>
        <rdf:RDF>
            <cc:Work rdf:about="">
                <dc:format>image/svg+xml</dc:format>
                <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
                <dc:title></dc:title>
            </cc:Work>
        </rdf:RDF>
    </metadata>

<defs>
    <!-- lattice point -->
    <circle id="lattice_point" cx="0" cy="0" r="0.3"/>
    <!-- SiDB -->
    <circle id="sidb_color" cx="0" cy="0" r="0.9"/>
</defs>
 <!-- PATH_DEFINITION placeholder -->
    <rect x="0" y="0" width="33.25" height="11.52" style="fill:#ffffff;"/> <!-- Background rectangle placeholder -->
    <g>
        <use xlink:href="#lattice_point" x="6.65" y="3.84" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="13.3" y="3.84" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="19.950000000000003" y="3.84" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="26.6" y="3.84" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="9.9755" y="5.76" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="16.625500000000002" y="5.76" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="23.2755" y="5.76" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="29.9255" y="5.76" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="6.65" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="13.3" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="19.950000000000003" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="26.6" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="9.9755" y="9.6" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="16.625500000000002" y="9.6" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="23.2755" y="9.6" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="29.9255" y="9.6" style="fill:#6e7175;"/><use xlink:href="#sidb_color" x="6.65" y="3.84" style="fill:#ffffff; fill-opacity:1; stroke:#C8C8C8; stroke-width:0.3;"/><use xlink:href="#sidb_color" x="13.3" y="3.84" style="fill:#ffffff; fill-opacity:1; stroke:#C8C8C8; stroke-width:0.3;"/><use xlink:href="#sidb_color" x="16.625500000000002" y="5.76" style="fill:#ffffff; fill-opacity:1; stroke:#C8C8C8; stroke-width:0.3;"/><use xlink:href="#sidb_color" x="29.9255" y="9.6" style="fill:#ffffff; fill-opacity:1; stroke:#C8C8C8; stroke-width:0.3;"/> <!-- SVG content placeholder -->
    </g>
</svg>)",
                FICTION_VERSION, FICTION_REPO);

inline const std::string EXPECTED_SVG_DARK_CELL_LEVEL =
    fmt::format(R"(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
            <!-- Generated by {} ({}) -->
            <svg
                xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:cc="http://creativecommons.org/ns#"
                xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
                xmlns:svg="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 19.2 23.04"
                version="1.1">
                <metadata>
                    <rdf:RDF>
                        <cc:Work rdf:about="">
                            <dc:format>image/svg+xml</dc:format>
                            <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
                            <dc:title></dc:title>
                        </cc:Work>
                    </rdf:RDF>
                </metadata>

            <defs>
                <!-- lattice point -->
                <circle id="lattice_point" cx="0" cy="0" r="0.3"/>
                <!-- SiDB -->
                <circle id="sidb_color" cx="0" cy="0" r="0.9"/>
            </defs>
             <!-- PATH_DEFINITION placeholder -->
                <rect x="0" y="0" width="19.2" height="23.04" style="fill:#25323D;"/> <!-- Background rectangle placeholder -->
                <g>
                    <use xlink:href="#lattice_point" x="3.84" y="7.68" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="7.68" y="7.68" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="11.52" y="7.68" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="15.36" y="7.68" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="3.84" y="9.93" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="7.68" y="9.93" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="11.52" y="9.93" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="15.36" y="9.93" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="3.84" y="15.36" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="7.68" y="15.36" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="11.52" y="15.36" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="15.36" y="15.36" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="3.84" y="17.61" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="7.68" y="17.61" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="11.52" y="17.61" style="fill:#6e7175;"/>
            <use xlink:href="#lattice_point" x="15.36" y="17.61" style="fill:#6e7175;"/>
            <use xlink:href="#sidb_color" x="3.84" y="7.68" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/>
            <use xlink:href="#sidb_color" x="7.68" y="7.68" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/>
            <use xlink:href="#sidb_color" x="7.68" y="9.93" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/>
            <use xlink:href="#sidb_color" x="15.36" y="17.61" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/> <!-- SVG content placeholder -->
                </g>
            </svg>)",
                FICTION_VERSION, FICTION_REPO);

inline const std::string EXPECTED_SVG_DARK_CELL_LEVEL_HIDE_LATTICE =
    fmt::format(R"(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by {} ({}) -->
<svg
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:cc="http://creativecommons.org/ns#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 19.2 23.04"
    version="1.1">
    <metadata>
        <rdf:RDF>
            <cc:Work rdf:about="">
                <dc:format>image/svg+xml</dc:format>
                <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
                <dc:title></dc:title>
            </cc:Work>
        </rdf:RDF>
    </metadata>

<defs>
    <!-- lattice point -->
    <circle id="lattice_point" cx="0" cy="0" r="0.3"/>
    <!-- SiDB -->
    <circle id="sidb_color" cx="0" cy="0" r="0.9"/>
</defs>
 <!-- PATH_DEFINITION placeholder -->
    <rect x="0" y="0" width="19.2" height="23.04" style="fill:#25323D;"/> <!-- Background rectangle placeholder -->
    <g>
        <use xlink:href="#sidb_color" x="3.84" y="7.68" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/>
        <use xlink:href="#sidb_color" x="7.68" y="7.68" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/>
        <use xlink:href="#sidb_color" x="7.68" y="9.93" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/>
        <use xlink:href="#sidb_color" x="15.36" y="17.61" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/>
        <!-- SVG content placeholder -->
    </g>
</svg>
)",
                FICTION_VERSION, FICTION_REPO);

inline const std::string EXPECTED_SVG_DARK_CELL_LEVEL_111 =
    fmt::format(R"(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by {} ({}) -->
<svg
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:cc="http://creativecommons.org/ns#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 33.25 11.52"
    version="1.1">
    <metadata>
        <rdf:RDF>
            <cc:Work rdf:about="">
                <dc:format>image/svg+xml</dc:format>
                <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
                <dc:title></dc:title>
            </cc:Work>
        </rdf:RDF>
    </metadata>

<defs>
    <!-- lattice point -->
    <circle id="lattice_point" cx="0" cy="0" r="0.3"/>
    <!-- SiDB -->
    <circle id="sidb_color" cx="0" cy="0" r="0.9"/>
</defs>
 <!-- PATH_DEFINITION placeholder -->
    <rect x="0" y="0" width="33.25" height="11.52" style="fill:#25323D;"/> <!-- Background rectangle placeholder -->
    <g>
        <use xlink:href="#lattice_point" x="6.65" y="3.84" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="13.3" y="3.84" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="19.950000000000003" y="3.84" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="26.6" y="3.84" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="9.9755" y="5.76" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="16.625500000000002" y="5.76" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="23.2755" y="5.76" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="29.9255" y="5.76" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="6.65" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="13.3" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="19.950000000000003" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="26.6" y="7.68" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="9.9755" y="9.6" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="16.625500000000002" y="9.6" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="23.2755" y="9.6" style="fill:#6e7175;"/><use xlink:href="#lattice_point" x="29.9255" y="9.6" style="fill:#6e7175;"/><use xlink:href="#sidb_color" x="6.65" y="3.84" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/><use xlink:href="#sidb_color" x="13.3" y="3.84" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/><use xlink:href="#sidb_color" x="16.625500000000002" y="5.76" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/><use xlink:href="#sidb_color" x="29.9255" y="9.6" style="fill:#C8C8C8; fill-opacity:1; stroke:#ffffff; stroke-width:0.3;"/> <!-- SVG content placeholder -->
    </g>
</svg>)",
                FICTION_VERSION, FICTION_REPO);

inline const std::string EXPECTED_SVG_LIGHT_CHARGE_DISTRIBUTION =
    fmt::format(R"(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by {} ({}) -->
<svg
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:cc="http://creativecommons.org/ns#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 19.2 23.04"
    version="1.1">
    <metadata>
        <rdf:RDF>
            <cc:Work rdf:about="">
                <dc:format>image/svg+xml</dc:format>
                <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
                <dc:title></dc:title>
            </cc:Work>
        </rdf:RDF>
    </metadata>

<defs>
    <!-- lattice point -->
    <circle id="lattice_point" cx="0" cy="0" r="0.3"/>
    <!-- SiDB -->
    <circle id="sidb_color" cx="0" cy="0" r="0.9"/>
</defs>
 <!-- PATH_DEFINITION placeholder -->
    <rect x="0" y="0" width="19.2" height="23.04" style="fill:#ffffff;"/> <!-- Background rectangle placeholder -->
    <g>
        <use xlink:href="#lattice_point" x="3.84" y="7.68" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="7.68" y="7.68" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="11.52" y="7.68" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="15.36" y="7.68" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="3.84" y="9.93" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="7.68" y="9.93" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="11.52" y="9.93" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="15.36" y="9.93" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="3.84" y="15.36" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="7.68" y="15.36" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="11.52" y="15.36" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="15.36" y="15.36" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="3.84" y="17.61" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="7.68" y="17.61" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="11.52" y="17.61" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="15.36" y="17.61" style="fill:#6e7175;"/>
<use xlink:href="#sidb_color" x="3.84" y="7.68" style="fill:#E34857; fill-opacity:1; stroke:#E34857; stroke-width:0.3;"/>
<use xlink:href="#sidb_color" x="7.68" y="7.68" style="fill:#ffffff; fill-opacity:0; stroke:#C8C8C8; stroke-width:0.3;"/>
<use xlink:href="#sidb_color" x="7.68" y="9.93" style="fill:#00ADAE; fill-opacity:1; stroke:#00ADAE; stroke-width:0.3;"/>
<use xlink:href="#sidb_color" x="15.36" y="17.61" style="fill:#ffffff; fill-opacity:0; stroke:#C8C8C8; stroke-width:0.3;"/> <!-- SVG content placeholder -->
    </g>
</svg>)",
                FICTION_VERSION, FICTION_REPO);

inline const std::string EXPECTED_SVG_DARK_CHARGE_DISTRIBUTION =
    fmt::format(R"(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by {} ({}) -->
<svg
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:cc="http://creativecommons.org/ns#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 19.2 23.04"
    version="1.1">
    <metadata>
        <rdf:RDF>
            <cc:Work rdf:about="">
                <dc:format>image/svg+xml</dc:format>
                <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
                <dc:title></dc:title>
            </cc:Work>
        </rdf:RDF>
    </metadata>

<defs>
    <!-- lattice point -->
    <circle id="lattice_point" cx="0" cy="0" r="0.3"/>
    <!-- SiDB -->
    <circle id="sidb_color" cx="0" cy="0" r="0.9"/>
</defs>
 <!-- PATH_DEFINITION placeholder -->
    <rect x="0" y="0" width="19.2" height="23.04" style="fill:#25323D;"/> <!-- Background rectangle placeholder -->
    <g>
        <use xlink:href="#lattice_point" x="3.84" y="7.68" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="7.68" y="7.68" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="11.52" y="7.68" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="15.36" y="7.68" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="3.84" y="9.93" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="7.68" y="9.93" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="11.52" y="9.93" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="15.36" y="9.93" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="3.84" y="15.36" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="7.68" y="15.36" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="11.52" y="15.36" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="15.36" y="15.36" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="3.84" y="17.61" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="7.68" y="17.61" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="11.52" y="17.61" style="fill:#6e7175;"/>
<use xlink:href="#lattice_point" x="15.36" y="17.61" style="fill:#6e7175;"/>
<use xlink:href="#sidb_color" x="3.84" y="7.68" style="fill:#E34857; fill-opacity:1; stroke:#E34857; stroke-width:0.3;"/>
<use xlink:href="#sidb_color" x="7.68" y="7.68" style="fill:#C8C8C8; fill-opacity:0; stroke:#ffffff; stroke-width:0.3;"/>
<use xlink:href="#sidb_color" x="7.68" y="9.93" style="fill:#00ADAE; fill-opacity:1; stroke:#00ADAE; stroke-width:0.3;"/>
<use xlink:href="#sidb_color" x="15.36" y="17.61" style="fill:#C8C8C8; fill-opacity:0; stroke:#ffffff; stroke-width:0.3;"/> <!-- SVG content placeholder -->
    </g>
</svg>)",
                FICTION_VERSION, FICTION_REPO);

TEST_CASE("Generate SVG for an sidb::layout", "[write-sidb-layout-svg]")
{
    sidb::layout lyt{};

    lyt.assign_cell_type({0, 0, 0}, sidb_technology::cell_type::NORMAL);
    lyt.assign_cell_type({1, 0, 1}, sidb_technology::cell_type::NORMAL);
    lyt.assign_cell_type({1, 0, 0}, sidb_technology::cell_type::NORMAL);
    lyt.assign_cell_type({3, 1, 1}, sidb_technology::cell_type::NORMAL);

    SECTION("light mode")
    {
        std::stringstream os{};

        write_sidb_layout_svg(lyt, os, {.color_background = write_sidb_layout_svg_params::color_mode::LIGHT});

        CHECK(normalize_svg(os.str()) == normalize_svg(EXPECTED_SVG_LIGHT_CELL_LEVEL));
    }
    SECTION("dark mode")
    {
        std::stringstream os{};

        write_sidb_layout_svg(lyt, os, {.color_background = write_sidb_layout_svg_params::color_mode::DARK});

        CHECK(normalize_svg(os.str()) == normalize_svg(EXPECTED_SVG_DARK_CELL_LEVEL));
    }
    SECTION("dark mode and hidden lattice")
    {
        std::stringstream os{};

        write_sidb_layout_svg(lyt, os,
                              {.color_background = write_sidb_layout_svg_params::color_mode::DARK,
                               .lattice_mode     = write_sidb_layout_svg_params::sidb_lattice_mode::HIDE_LATTICE});

        CHECK(normalize_svg(os.str()) == normalize_svg(EXPECTED_SVG_DARK_CELL_LEVEL_HIDE_LATTICE));
    }
}

TEST_CASE("Generate SVG for an sidb::layout on the H-Si(111)-1x1 surface", "[write-sidb-layout-svg]")
{
    sidb::layout lyt{sidb::lattice::si_111_1x1()};

    lyt.assign_cell_type({0, 0, 0}, sidb_technology::cell_type::NORMAL);
    lyt.assign_cell_type({1, 0, 1}, sidb_technology::cell_type::NORMAL);
    lyt.assign_cell_type({1, 0, 0}, sidb_technology::cell_type::NORMAL);
    lyt.assign_cell_type({3, 1, 1}, sidb_technology::cell_type::NORMAL);

    SECTION("light mode")
    {
        std::stringstream os{};

        write_sidb_layout_svg(lyt, os, {.color_background = write_sidb_layout_svg_params::color_mode::LIGHT});

        CHECK(normalize_svg(os.str()) == normalize_svg(EXPECTED_SVG_LIGHT_CELL_LEVEL_111));
    }
    SECTION("dark mode")
    {
        std::stringstream os{};

        write_sidb_layout_svg(lyt, os, {.color_background = write_sidb_layout_svg_params::color_mode::DARK});

        CHECK(normalize_svg(os.str()) == normalize_svg(EXPECTED_SVG_DARK_CELL_LEVEL_111));
    }
}

TEST_CASE("SVG padding rejects unrepresentable lattice sites", "[write-sidb-layout-svg]")
{
    constexpr auto max_coordinate = std::numeric_limits<int32_t>::max();
    for (const lattice_site site :
         {lattice_site{max_coordinate, 0, 0}, lattice_site{0, max_coordinate, 0}, lattice_site{0, max_coordinate, 1}})
    {
        sidb::layout lyt{};
        lyt.assign_cell_type(site, sidb_technology::cell_type::NORMAL);
        std::stringstream os{};
        CHECK_THROWS_AS(write_sidb_layout_svg(lyt, os), std::out_of_range);
        CHECK(os.str().empty());
    }
    sidb::layout lyt{};
    lyt.assign_cell_type({max_coordinate - 2, max_coordinate - 2, 1}, sidb_technology::cell_type::NORMAL);
    std::stringstream os{};
    CHECK_NOTHROW(write_sidb_layout_svg(lyt, os));
}

TEST_CASE("Generate SVG for an sidb::layout with a charge distribution", "[write-sidb-layout-svg]")
{
    sidb::layout lyt{};

    lyt.assign_cell_type({0, 0, 0}, sidb_technology::cell_type::NORMAL);
    lyt.assign_cell_type({1, 0, 1}, sidb_technology::cell_type::NORMAL);
    lyt.assign_cell_type({1, 0, 0}, sidb_technology::cell_type::NORMAL);
    lyt.assign_cell_type({3, 1, 1}, sidb_technology::cell_type::NORMAL);

    sidb::charge_distribution cd{lyt};
    cd.assign_charge_state({0, 0, 0}, charge_state::POSITIVE);
    cd.assign_charge_state({1, 0, 1}, charge_state::NEGATIVE);
    cd.assign_charge_state({1, 0, 0}, charge_state::NEUTRAL);
    cd.assign_charge_state({3, 1, 1}, charge_state::NEUTRAL);

    SECTION("light mode")
    {
        std::stringstream os{};

        write_sidb_layout_svg(lyt, cd, os, {.color_background = write_sidb_layout_svg_params::color_mode::LIGHT});

        CHECK(parse_svg_charge_elements(os.str()) == parse_svg_charge_elements(EXPECTED_SVG_LIGHT_CHARGE_DISTRIBUTION));
    }
    SECTION("dark mode")
    {
        std::stringstream os{};

        write_sidb_layout_svg(lyt, cd, os, {.color_background = write_sidb_layout_svg_params::color_mode::DARK});

        CHECK(parse_svg_charge_elements(os.str()) == parse_svg_charge_elements(EXPECTED_SVG_DARK_CHARGE_DISTRIBUTION));
    }
}
