//
// Created by marcel on 17.01.22.
//

#include "catch.hpp"
#include "utils/blueprints/layout_blueprints.hpp"
#include "utils/version_info.hpp"

#include <fiction/io/write_qcc_layout.hpp>
#include <fiction/technology/cell_technologies.hpp>
#include <fiction/types.hpp>

#include <fmt/format.h>

#include <sstream>
#include <string>

using namespace fiction;

TEST_CASE("Write empty layout", "[qcc]")
{
    static const std::string qcc_layout =
        fmt::format("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                    "<!--Generated by {} ({})-->\n"
                    "<qcacomponent Version=\"2\" tech=\"iNML\" lib=\"components_fiction\" name=\"empty layout\" "
                    "ID=\"1827092195390838063013182709219539083806303718270921953908380630\" function=\"\" maxX=\"0\" "
                    "maxY=\"0\" MagnetsCount=\"0\">\n"
                    "\t<entity>\n"
                    "\t</entity>\n"
                    "\t<components>\n"
                    "\t\t<item tech=\"iNML\" name=\"Magnet\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"Coupler\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"Cross Wire\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"And\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"Inverter\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"Or\"/>\n"
                    "\t</components>\n"
                    "\t<layout>\n"
                    "\t</layout>\n"
                    "</qcacomponent>\n",
                    FICTION_VERSION, FICTION_REPO);

    std::ostringstream layout_stream{};

    const inml_cell_clk_lyt layout{{2, 2, 1}, "empty layout"};

    write_qcc_layout(layout, layout_stream, {});

    CHECK(layout_stream.str() == qcc_layout);
}

TEST_CASE("Write single-layer MAJ gate", "[qcc]")
{
    static const std::string qcc_layout =
        fmt::format("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                    "<!--Generated by {} ({})-->\n"
                    "<qcacomponent Version=\"2\" tech=\"iNML\" lib=\"components_fiction\" name=\"MAJ\" "
                    "ID=\"1820773779804134406313182077377980413440633718207737798041344063\" function=\"\" maxX=\"4\" "
                    "maxY=\"4\" MagnetsCount=\"13\">\n"
                    "\t<entity>\n"
                    "\t\t<pin tech=\"iNML\" name=\"a\" direction=\"0\" x=\"0\" y=\"0\"/>\n"
                    "\t\t<pin tech=\"iNML\" name=\"b\" direction=\"0\" x=\"0\" y=\"2\"/>\n"
                    "\t\t<pin tech=\"iNML\" name=\"c\" direction=\"0\" x=\"0\" y=\"4\"/>\n"
                    "\t\t<pin tech=\"iNML\" name=\"f\" direction=\"1\" x=\"4\" y=\"2\"/>\n"
                    "\t</entity>\n"
                    "\t<components>\n"
                    "\t\t<item tech=\"iNML\" name=\"Magnet\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"Coupler\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"Cross Wire\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"And\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"Inverter\"/>\n"
                    "\t\t<item tech=\"iNML\" name=\"Or\"/>\n"
                    "\t</components>\n"
                    "\t<layout>\n"
                    "\t\t<item comp=\"0\" x=\"0\" y=\"0\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"1\" y=\"0\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"2\" y=\"0\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"2\" y=\"1\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"0\" y=\"2\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"1\" y=\"2\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"2\" y=\"2\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"3\" y=\"2\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"4\" y=\"2\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"2\" y=\"3\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"0\" y=\"4\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"1\" y=\"4\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t\t<item comp=\"0\" x=\"2\" y=\"4\">\n"
                    "\t\t\t<property name=\"phase\" value=\"0\"/>\n"
                    "\t\t</item>\n"
                    "\t</layout>\n"
                    "</qcacomponent>\n",
                    FICTION_VERSION, FICTION_REPO);

    std::ostringstream layout_stream{};

    const auto layout = blueprints::single_layer_inml_maj_gate<inml_cell_clk_lyt>();

    write_qcc_layout(layout, layout_stream, {});

    CHECK(layout_stream.str() == qcc_layout);
}