/*
 * Copyright (c) 2018 - 2023 Marcel Walter
 * Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
 * All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License
 */

/**
 * @file
 * @brief SVG building blocks shared by the QCA and molQCA layout writers.
 * @author Sophia Kuhn
 * @author Marcel Walter (marcelwa)
 * @author Benjamin Hien (hibenj)
 */

#pragma once

#include <exception>

namespace fiction::fcn::io
{

/**
 * Exception thrown when an SVG writer encounters a cell it cannot draw.
 *
 * @tparam Coordinate Cell coordinate type.
 */
template <typename Coordinate>
class unsupported_cell_type_exception : public std::exception
{
  public:
    /**
     * @param c Position of the cell that cannot be drawn.
     */
    explicit unsupported_cell_type_exception(const Coordinate& c) noexcept : std::exception(), coord{c} {}
    /**
     * @return Position of the cell that cannot be drawn.
     */
    [[nodiscard]] Coordinate where() const noexcept
    {
        return coord;
    }

  private:
    /**
     * Position of the cell that cannot be drawn.
     */
    const Coordinate coord;
};

namespace detail::svg
{

// General layout
inline constexpr const double VIEWBOX_DISTANCE       = 11;
inline constexpr const int    STARTING_OFFSET_TILE_X = -175;
inline constexpr const int    STARTING_OFFSET_TILE_Y = -58;
inline constexpr const double STARTING_OFFSET_CELL_X = 3.5;
inline constexpr const double STARTING_OFFSET_CELL_Y = -40.25;

/**
 * Fill color for constant-0/1 cells. Omits the leading `#`, like every other color in this group,
 * because the SVG templates that consume it (e.g. `SIMPLE_CELL`'s `fill:#{0}`) already supply one.
 */
inline constexpr const char* CONST_CELL = "000000";

// SVG document with placeholders for generator, version, viewbox width and height, and content
inline constexpr const char* HEADER = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
                                      "<!-- Generated by {} ({}) -->\n"
                                      "\n"
                                      "<svg\n"
                                      "xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
                                      "xmlns:cc=\"http://creativecommons.org/ns#\"\n"
                                      "xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                                      "xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
                                      "xmlns=\"http://www.w3.org/2000/svg\"\n"
                                      "viewBox=\"0 0 {} {}\"\n"
                                      "version=\"1.1\">\n"
                                      "<metadata>\n"
                                      "<rdf:RDF>\n"
                                      "<cc:Work\n"
                                      "rdf:about=\"\">\n"
                                      "<dc:format>image/svg+xml</dc:format>\n"
                                      "<dc:type\n"
                                      "rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
                                      "<dc:title></dc:title>\n"
                                      "</cc:Work>\n"
                                      "</rdf:RDF>\n"
                                      "</metadata>\n"
                                      "<g>\n"
                                      "{}\n"
                                      "</g>\n"
                                      "</svg>";

}  // namespace detail::svg

}  // namespace fiction::fcn::io
