/*
 * Copyright (c) 2018 - 2023 Marcel Walter
 * Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
 * All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License
 */

/**
 * @file
 * @brief Writer for QCA, molQCA, and iNML layouts in the QLL format of ToPoliNano and MagCAD.
 * @author Marcel Walter (marcelwa)
 * @author Benjamin Hien (hibenj)
 */

#pragma once

#include "fiction/layouts/bounding_box.hpp"
#include "fiction/technology/inml/io/magcad_components.hpp"
#include "fiction/technology/inml/layout.hpp"
#include "fiction/technology/mol_qca/layout.hpp"
#include "fiction/technology/qca/layout.hpp"
#include "fiction/utils/atomic_write.hpp"
#include "fiction/utils/progress.hpp"
#include "fiction/utils/version_info.hpp"

#include <fmt/format.h>

#include <algorithm>
#include <concepts>
#include <cstdint>
#include <iostream>
#include <ostream>
#include <stdexcept>
#include <string_view>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace fiction::fcn::io
{

namespace detail
{

namespace qll
{

inline constexpr const char* VERSION_HEADER = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                                              "<!--Generated by {} ({})-->\n";

inline constexpr const char* OPEN_QCA_LAYOUT  = "<qcalayout>\n";
inline constexpr const char* CLOSE_QCA_LAYOUT = "</qcalayout>\n";

inline constexpr const char* OPEN_TECHNOLOGIES  = "\t<technologies>\n";
inline constexpr const char* CLOSE_TECHNOLOGIES = "\t</technologies>\n";

inline constexpr const char* OPEN_SETTINGS = "\t\t<settings tech=\"{}\">\n";  // technology

inline constexpr const char* GENERAL_SETTINGS =
    "\t\t\t<property name=\"Layoutwidth\" value=\"{}\"/>\n"    // layout width
    "\t\t\t<property name=\"Layoutheight\" value=\"{}\"/>\n"   // layout height
    "\t\t\t<property name=\"layersEnabled\" value=\"{}\"/>\n"  // multi-layer design
    "\t\t\t<property name=\"PhaseNumber\" value=\"{}\"/>\n"    // num clocks
    "\t\t\t<property name=\"CZSequence\" value=\"4\"/>\n";

inline constexpr const char* INML_SETTINGS = "\t\t\t<property name=\"Width\" value=\"60\"/>\n"
                                             "\t\t\t<property name=\"Height\" value=\"90\"/>\n"
                                             "\t\t\t<property name=\"Thickness\" value=\"10\"/>\n"
                                             "\t\t\t<property name=\"VDistance\" value=\"10\"/>\n"
                                             "\t\t\t<property name=\"HDistance\" value=\"25\"/>\n"
                                             "\t\t\t<property name=\"DWEnabled\" value=\"true\"/>\n"
                                             "\t\t\t<property name=\"DWMaxSize\" value=\"6\"/>\n"
                                             "\t\t\t<property name=\"DWDefSize\" value=\"2\"/>\n"
                                             "\t\t\t<property name=\"InterlayerSpace\" value=\"10\"/>\n";

inline constexpr const char* MQCA_SETTINGS = "\t\t\t<property name=\"Intermolecular Distance\" value=\"1000\"/>\n";

inline constexpr const char* CLOSE_SETTINGS = "\t\t</settings>\n";

inline constexpr const char* OPEN_COMPONENTS  = "\t<components>\n";
inline constexpr const char* CLOSE_COMPONENTS = "\t</components>\n";
inline constexpr const char* OPEN_LAYOUT      = "\t<layout>\n";
inline constexpr const char* CLOSE_LAYOUT     = "\t</layout>\n";

inline constexpr const char* INML_COMPONENT_ITEM = "\t\t<item tech=\"{}\" name=\"{}\"/>\n";
inline constexpr const char* MQCA_COMPONENT_ITEM = "\t\t<item tech=\"MolFCN\" name=\"Bisferrocene\"/>\n";

inline constexpr const char* OPEN_INML_LAYOUT_ITEM = "\t\t<item comp=\"{}\" id=\"{}\" x=\"{}\" y=\"{}\">\n";
inline constexpr const char* OPEN_MQCA_LAYOUT_ITEM =
    "\t\t<item comp=\"{}\" id=\"{}\" x=\"{}\" y=\"{}\" layer=\"{}\">\n";

inline constexpr const char* CLOSE_LAYOUT_ITEM = "\t\t</item>\n";

inline constexpr const char* LAYOUT_ITEM_PROPERTY = "\t\t\t<property name=\"{}\" value=\"{}\"/>\n";
inline constexpr const char* PROPERTY_PHASE       = "phase";
inline constexpr const char* PROPERTY_LENGTH      = "length";

inline constexpr const char* PIN =
    "\t\t<pin tech=\"{}\" name=\"{}\" direction=\"{}\" id=\"{}\" x=\"{}\" y=\"{}\" layer=\"{}\"/>\n";

}  // namespace qll

template <typename Lyt>
class write_qll_layout_impl
{
  public:
    /**
     * @brief Creates a writer with optional serialization progress.
     * @param src Layout to write.
     * @param s Output stream.
     * @param callback Receives completed serialization work.
     */
    write_qll_layout_impl(const Lyt& src, std::ostream& s, utils::progress_callback callback = {}) :
            lyt{src},
            bb{lyt},
            sorted_pi_list{sorted_pis()},
            sorted_po_list{sorted_pos()},
            os{s},
            on_progress{std::move(callback)}
    {}

    void run()
    {
        if (std::is_same_v<Lyt, inml::layout> && !has_border_io_pins())
        {
            throw std::invalid_argument(
                "the layout does not fulfill all requirements to be written as a QLL file because it does not have "
                "designated I/O pins or they are not routed to the layout's borders");
        }

        write_header();

        os << qll::OPEN_QCA_LAYOUT;

        write_technology_settings();
        write_components();
        write_layout();

        // close component block and flush the file
        os << qll::CLOSE_QCA_LAYOUT << std::flush;
    }

  private:
    const Lyt& lyt;

    const layouts::bounding_box_2d<Lyt> bb;

    std::vector<typename Lyt::cell> sorted_pi_list, sorted_po_list;

    std::ostream& os;
    /** @brief Receives serialization progress. */
    utils::progress_callback on_progress;

    uint64_t cell_id{1};

    static constexpr auto tech_name = []
    {
        if constexpr (std::is_same_v<Lyt, inml::layout>)
        {
            return "iNML";
        }
        else
        {
            return "MolFCN";
        }
    }();

    [[nodiscard]] std::vector<typename Lyt::cell> sorted_pis() const noexcept
    {
        std::vector<typename Lyt::cell> pi_list{};
        lyt.foreach_pi([&pi_list](const auto& pi) { pi_list.push_back(pi); });
        std::ranges::sort(pi_list,
                          [](const auto& c1, const auto& c2) { return c1.y < c2.y || (c1.y == c2.y && c1.x < c2.x); });

        return pi_list;
    }

    [[nodiscard]] std::vector<typename Lyt::cell> sorted_pos() const noexcept
    {
        std::vector<typename Lyt::cell> po_list{};
        lyt.foreach_po([&po_list](const auto& po) { po_list.push_back(po); });
        std::ranges::sort(po_list,
                          [](const auto& c1, const auto& c2) { return c1.y < c2.y || (c1.y == c2.y && c1.x < c2.x); });

        return po_list;
    }

    [[nodiscard]] auto bb_x(const typename Lyt::cell& c) const noexcept
    {
        return static_cast<decltype(c.x)>(c.x - bb.get_min().x);
    }

    [[nodiscard]] auto bb_y(const typename Lyt::cell& c) const noexcept
    {
        return static_cast<decltype(c.y)>(c.y - bb.get_min().y);
    }

    [[nodiscard]] bool has_border_io_pins() const noexcept
    {
        auto all_border_pins = true;

        // check PI border cells
        lyt.foreach_pi(
            [this, &all_border_pins](const auto& pi)
            {
                if (bb_x(pi) != 0)
                {
                    all_border_pins = false;
                    return false;  // break iteration
                }
                return true;  // keep iterating
            });
        // check PO border cells
        lyt.foreach_po(
            [this, &all_border_pins](const auto& po)
            {
                if (bb_x(po) != lyt.x())
                {
                    all_border_pins = false;
                    return false;  // break iteration
                }
                return true;  // keep iterating
            });

        return all_border_pins;
    }

    /**
     * @brief Number of clock phases: the layout's, or 4 for molQCA, whose cells name one of four phases themselves.
     * @return Number of clock phases.
     */
    [[nodiscard]] uint32_t num_clocks() const noexcept
    {
        if constexpr (std::is_same_v<Lyt, mol_qca::layout>)
        {
            return 4u;
        }
        else
        {
            return static_cast<uint32_t>(lyt.num_clocks());
        }
    }

    void write_header()
    {
        os << fmt::format(qll::VERSION_HEADER, FICTION_VERSION, FICTION_REPO);
    }

    void write_technology_settings()
    {
        os << qll::OPEN_TECHNOLOGIES;

        os << fmt::format(qll::OPEN_SETTINGS, tech_name);

        os << fmt::format(qll::GENERAL_SETTINGS, lyt.x(), lyt.y(), (lyt.z() > 0 ? "true" : "false"), num_clocks());

        if constexpr (std::is_same_v<Lyt, inml::layout>)
        {
            os << qll::INML_SETTINGS;
        }
        else
        {
            os << qll::MQCA_SETTINGS;
        }

        os << qll::CLOSE_SETTINGS;
        os << qll::CLOSE_TECHNOLOGIES;
    }

    void write_components()
    {
        os << qll::OPEN_COMPONENTS;

        if constexpr (std::is_same_v<Lyt, inml::layout>)
        {
            for (const auto& comp : inml::io::detail::COMPONENTS)
            {
                os << fmt::format(qll::INML_COMPONENT_ITEM, tech_name, comp);
            }
        }
        else
        {
            os << qll::MQCA_COMPONENT_ITEM;
        }

        os << qll::CLOSE_COMPONENTS;
    }

    void write_pins()
    {
        for (const auto& pi : sorted_pi_list)
        {
            os << fmt::format(qll::PIN, tech_name, lyt.get_cell_name(pi), 0, cell_id++, bb_x(pi), bb_y(pi), pi.z);
        }
        for (const auto& po : sorted_po_list)
        {
            os << fmt::format(qll::PIN, tech_name, lyt.get_cell_name(po), 1, cell_id++, bb_x(po), bb_y(po), po.z);
        }
    }

    void write_layout()
    {
        utils::progress_reporter               progress{on_progress, "writing rows", (lyt.y() + 1) * (lyt.z() + 1)};
        std::unordered_set<typename Lyt::cell> skip{};

        os << qll::OPEN_LAYOUT;

        for (decltype(lyt.z()) layer = 0; layer <= lyt.z(); ++layer)
        {
            for (decltype(lyt.y()) row = 0; row <= lyt.y(); ++row)
            {
                for (decltype(lyt.x()) col = 0; col <= lyt.x(); ++col)
                {
                    const auto c    = typename Lyt::cell{col, row, layer};
                    const auto type = lyt.get_cell_type(c);

                    // skip empty cells and cells marked as to be skipped as well (duh...)
                    if (lyt.is_empty_cell(c) || skip.count(c) > 0u)
                    {
                        continue;
                    }

                    // write iNML cell
                    if constexpr (std::is_same_v<Lyt, inml::layout>)
                    {
                        inml::io::detail::skip_component_magnets(type, c, skip);

                        if (const auto it = inml::io::detail::COMPONENT_SELECTOR.find(type);
                            it != inml::io::detail::COMPONENT_SELECTOR.end())
                        {
                            os << fmt::format(qll::OPEN_INML_LAYOUT_ITEM, it->second, cell_id++, bb_x(c), bb_y(c));
                        }
                        else
                        {
                            std::cout << fmt::format("[w] cell at position {} has an unsupported type", c) << std::endl;
                        }

                        os << fmt::format(qll::LAYOUT_ITEM_PROPERTY, qll::PROPERTY_PHASE, lyt.get_clock_number(c));

                        if (type == inml::magnet_type::INVERTER_MAGNET)
                        {
                            os << fmt::format(qll::LAYOUT_ITEM_PROPERTY, qll::PROPERTY_LENGTH, 4);
                        }

                        os << qll::CLOSE_LAYOUT_ITEM;
                    }
                    // write mQCA cell
                    else if constexpr (std::is_same_v<Lyt, qca::layout>)
                    {
                        const auto mode = lyt.get_cell_mode(c);

                        // write normal cell
                        if (type == qca::cell_type::NORMAL)
                        {
                            os << fmt::format(qll::OPEN_MQCA_LAYOUT_ITEM, 0, cell_id++, bb_x(c), bb_y(c), c.z * 2);
                            os << fmt::format(qll::LAYOUT_ITEM_PROPERTY, qll::PROPERTY_PHASE, lyt.get_clock_number(c));
                            os << qll::CLOSE_LAYOUT_ITEM;
                        }
                        // constant cells are handled as input pins
                        else if (qca::is_constant(type))
                        {
                            const auto const_name = (type == qca::cell_type::CONST_0) ? "const0" : "const1";
                            os << fmt::format(qll::PIN, tech_name, const_name, 0, cell_id++, bb_x(c), bb_y(c), c.z * 2);
                        }

                        // write via cell
                        if (mode == qca::cell_mode::VERTICAL && c.z != lyt.z())
                        {
                            os << fmt::format(qll::OPEN_MQCA_LAYOUT_ITEM, 0, cell_id++, bb_x(c), bb_y(c),
                                              (c.z * 2) + 1);
                            os << fmt::format(qll::LAYOUT_ITEM_PROPERTY, qll::PROPERTY_PHASE, lyt.get_clock_number(c));
                            os << qll::CLOSE_LAYOUT_ITEM;
                        }
                    }
                    // write molQCA cell
                    else if constexpr (std::is_same_v<Lyt, mol_qca::layout>)
                    {
                        // write normal cell
                        if (mol_qca::is_normal(type))
                        {
                            // each regular molQCA cell names its own clock phase
                            const auto phase = mol_qca::clock_number(type);

                            os << fmt::format(qll::OPEN_MQCA_LAYOUT_ITEM, 0, cell_id++, bb_x(c), bb_y(c), c.z * 2);
                            os << fmt::format(qll::LAYOUT_ITEM_PROPERTY, qll::PROPERTY_PHASE, phase);
                            os << qll::CLOSE_LAYOUT_ITEM;
                        }
                        // constant cells are handled as input pins
                        else if (mol_qca::is_constant(type))
                        {
                            const auto const_name = (type == mol_qca::cell_type::CONST_0) ? "const0" : "const1";
                            os << fmt::format(qll::PIN, tech_name, const_name, 0, cell_id++, bb_x(c), bb_y(c), c.z * 2);
                        }
                    }
                }
                progress.advance();
            }
        }

        // I/O cells are not considered in the cases above because they need to be handled separately
        write_pins();

        os << qll::CLOSE_LAYOUT;
    }
};

}  // namespace detail

/**
 * Layouts that the QLL format describes: QCA, molQCA, and iNML layouts.
 */
template <typename Lyt>
concept qll_layout =
    std::same_as<Lyt, qca::layout> || std::same_as<Lyt, mol_qca::layout> || std::same_as<Lyt, inml::layout>;

/**
 * Writes a QCA, molQCA, or iNML layout to a qll file that is used by ToPoliNano & MagCAD
 * (https://topolinano.polito.it/), an EDA tool and a physical simulator for the iNML technology platform as well as
 * SCERPA (https://ieeexplore.ieee.org/document/8935211), a physical simulator for the molQCA (mQCA) technology
 * platform.
 *
 * This overload uses an output stream to write into.
 *
 * @tparam Lyt `qca::layout`, `mol_qca::layout`, or `inml::layout`.
 * @param lyt The layout to be written.
 * @param os The output stream to write into.
 * @param on_progress Receives completed serialization work.
 * @throws std::invalid_argument if an iNML layout has no I/O pins or they are not routed to the layout's borders.
 */
template <qll_layout Lyt>
void write_qll_layout(const Lyt& lyt, std::ostream& os, utils::progress_callback on_progress = {})
{
    detail::write_qll_layout_impl p{lyt, os, std::move(on_progress)};

    p.run();
}
/**
 * Writes a QCA, molQCA, or iNML layout to a qll file that is used by ToPoliNano & MagCAD
 * (https://topolinano.polito.it/), an EDA tool and a physical simulator for the iNML technology platform as well as
 * SCERPA (https://ieeexplore.ieee.org/document/8935211), a physical simulator for the molQCA (mQCA) technology
 * platform.
 *
 * This overload uses a file name to create and write into.
 *
 * @tparam Lyt `qca::layout`, `mol_qca::layout`, or `inml::layout`.
 * @param lyt The layout to be written.
 * @param filename The file name to create and write into. Should preferably use the `.qll` extension.
 * @param on_progress Receives completed serialization work.
 * @throws std::invalid_argument if an iNML layout has no I/O pins or they are not routed to the layout's borders.
 */
template <qll_layout Lyt>
void write_qll_layout(const Lyt& lyt, const std::string_view& filename, utils::progress_callback on_progress = {})
{
    fiction::detail::atomic_write(filename, [&](std::ostream& os) { write_qll_layout(lyt, os, on_progress); });
}

}  // namespace fiction::fcn::io
