# Copyright (c) 2018 - 2023 Marcel Walter
# Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

"""Logic networks and their simulation."""

from typing import overload

import mnt.pyfiction._native.inml
import mnt.pyfiction._native.layouts
import mnt.pyfiction._native.mol_qca
import mnt.pyfiction._native.qca
import mnt.pyfiction._native.sidb
from mnt.pyfiction._native.networks import io as io

class Signal:
    """A node reference and its edge polarity."""

    def __init__(self, node: int, complemented: bool = False) -> None: ...
    @property
    def node(self) -> int: ...
    @property
    def complemented(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class TechnologyNetwork:
    """
    A `mockturtle` logic network type that extends `klut_network`. It
    reimplements all node creation functions to disable structural
    hashing. Furthermore, `create_buf` is overwritten such that it creates
    real buffer nodes that count towards the size of the network and
    compute the identity function. In the same way, a buffer with more
    than one fanout node is considered a fanout node (or splitter in some
    contexts) that copies an incoming signal to two or more data paths.

    This network is used internally for most implemented FCN physical
    design algorithms and extends `klut_network` by some further
    convenience functions but is still fully compatible with the
    mockturtle network API. The function convert_network can be used to
    convert any other mockturtle network to this type.

    Most functions in this class are borrowed and reimplemented directly
    from `klut_network` and are, therefore, only sporadically documented
    where their behavior might differ. For information consider
    `mockturtle/networks/klut.hpp`.
    """

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def name(self) -> str:
        """The network's name."""

    @name.setter
    def name(self, arg: str, /) -> None: ...
    def __len__(self) -> int:
        """Returns the number of network nodes."""

    def size(self) -> int: ...
    def num_gates(self) -> int: ...
    def num_pis(self) -> int: ...
    def num_pos(self) -> int: ...
    def depth(self) -> int:
        """Returns the number of gates on the longest input-to-output path."""

    def nodes(self) -> list[int]: ...
    def gates(self) -> list[int]: ...
    def pis(self) -> list[int]: ...
    def pos(self) -> list[Signal]: ...
    def fanins(self, n: int) -> list[Signal]: ...
    def is_constant(self, n: int) -> bool: ...
    def is_pi(self, n: int) -> bool: ...
    def has_name(self, n: int) -> bool: ...
    def get_name(self, n: int) -> str: ...
    def set_name(self, n: int, name: str) -> None: ...
    def has_output_name(self, index: int) -> bool: ...
    def get_output_name(self, index: int) -> str: ...
    def set_output_name(self, index: int, name: str) -> None: ...
    def is_po(self, n: int) -> bool: ...
    def is_buf(self, n: int) -> bool:
        """
        Returns whether the given node `n` is a buffer node, i.e., whether `n`
        computes the identity function and is not a PI. This also returns
        `true` on fanout nodes.

        Args:
            n: Node to consider.

        Returns:
            `true` iff `n` is a buffer node.
        """

    def is_fanout(self, n: int) -> bool:
        """
        Returns whether the given node `n` is a fanout node, i.e., whether `n`
        is a buffer node and has more than one output signal.

        Args:
            n: Node to consider.

        Returns:
            `true` iff `n` is a fanout node.
        """

    def is_inv(self, n: int) -> bool:
        """
        Returns whether the given node `n` is an inverter node.

        Args:
            n: Node to consider.

        Returns:
            `true` iff `n` is an inverter node.
        """

    def is_and(self, n: int) -> bool: ...
    def is_or(self, n: int) -> bool: ...
    def is_xor(self, n: int) -> bool: ...
    def is_maj(self, n: int) -> bool: ...
    def is_nand(self, n: int) -> bool: ...
    def is_nor(self, n: int) -> bool: ...
    def is_xnor(self, n: int) -> bool: ...
    def po_index(self, n: int) -> int: ...
    def po_at(self, index: int) -> int: ...

class AigNetwork:
    """An AND-inverter graph (AIG) with node and output names."""

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def name(self) -> str:
        """The network's name."""

    @name.setter
    def name(self, arg: str, /) -> None: ...
    def __len__(self) -> int:
        """Returns the number of network nodes."""

    def size(self) -> int: ...
    def num_gates(self) -> int: ...
    def num_pis(self) -> int: ...
    def num_pos(self) -> int: ...
    def depth(self) -> int:
        """Returns the number of gates on the longest input-to-output path."""

    def nodes(self) -> list[int]: ...
    def gates(self) -> list[int]: ...
    def pis(self) -> list[int]: ...
    def pos(self) -> list[Signal]: ...
    def fanins(self, n: int) -> list[Signal]: ...
    def is_constant(self, n: int) -> bool: ...
    def is_pi(self, n: int) -> bool: ...
    def has_name(self, n: int) -> bool: ...
    def get_name(self, n: int) -> str: ...
    def set_name(self, n: int, name: str) -> None: ...
    def has_output_name(self, index: int) -> bool: ...
    def get_output_name(self, index: int) -> str: ...
    def set_output_name(self, index: int, name: str) -> None: ...
    def is_and(self, n: int) -> bool: ...
    def is_or(self, n: int) -> bool: ...
    def is_xor(self, n: int) -> bool: ...
    def is_maj(self, n: int) -> bool: ...

class XagNetwork:
    """An XOR-AND-inverter graph (XAG) with node and output names."""

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def name(self) -> str:
        """The network's name."""

    @name.setter
    def name(self, arg: str, /) -> None: ...
    def __len__(self) -> int:
        """Returns the number of network nodes."""

    def size(self) -> int: ...
    def num_gates(self) -> int: ...
    def num_pis(self) -> int: ...
    def num_pos(self) -> int: ...
    def depth(self) -> int:
        """Returns the number of gates on the longest input-to-output path."""

    def nodes(self) -> list[int]: ...
    def gates(self) -> list[int]: ...
    def pis(self) -> list[int]: ...
    def pos(self) -> list[Signal]: ...
    def fanins(self, n: int) -> list[Signal]: ...
    def is_constant(self, n: int) -> bool: ...
    def is_pi(self, n: int) -> bool: ...
    def has_name(self, n: int) -> bool: ...
    def get_name(self, n: int) -> str: ...
    def set_name(self, n: int, name: str) -> None: ...
    def has_output_name(self, index: int) -> bool: ...
    def get_output_name(self, index: int) -> str: ...
    def set_output_name(self, index: int, name: str) -> None: ...
    def is_and(self, n: int) -> bool: ...
    def is_or(self, n: int) -> bool: ...
    def is_xor(self, n: int) -> bool: ...
    def is_maj(self, n: int) -> bool: ...

class MigNetwork:
    """A majority-inverter graph (MIG) with node and output names."""

    def __init__(self) -> None:
        """Default constructor."""

    @property
    def name(self) -> str:
        """The network's name."""

    @name.setter
    def name(self, arg: str, /) -> None: ...
    def __len__(self) -> int:
        """Returns the number of network nodes."""

    def size(self) -> int: ...
    def num_gates(self) -> int: ...
    def num_pis(self) -> int: ...
    def num_pos(self) -> int: ...
    def depth(self) -> int:
        """Returns the number of gates on the longest input-to-output path."""

    def nodes(self) -> list[int]: ...
    def gates(self) -> list[int]: ...
    def pis(self) -> list[int]: ...
    def pos(self) -> list[Signal]: ...
    def fanins(self, n: int) -> list[Signal]: ...
    def is_constant(self, n: int) -> bool: ...
    def is_pi(self, n: int) -> bool: ...
    def has_name(self, n: int) -> bool: ...
    def get_name(self, n: int) -> str: ...
    def set_name(self, n: int, name: str) -> None: ...
    def has_output_name(self, index: int) -> bool: ...
    def get_output_name(self, index: int) -> str: ...
    def set_output_name(self, index: int, name: str) -> None: ...
    def is_and(self, n: int) -> bool: ...
    def is_or(self, n: int) -> bool: ...
    def is_xor(self, n: int) -> bool: ...
    def is_maj(self, n: int) -> bool: ...

@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.layouts.CartesianGateLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.layouts.ShiftedCartesianGateLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.layouts.HexagonalGateLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.layouts.OddRowCartesianGateLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.layouts.EvenRowCartesianGateLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.layouts.EvenColumnCartesianGateLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.layouts.OddRowHexGateLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.layouts.OddColumnHexGateLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.layouts.EvenColumnHexGateLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.qca.QCALayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.mol_qca.MolecularQCALayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.inml.INMLLayout) -> str: ...
@overload
def get_name(ntk_or_lyt: mnt.pyfiction._native.sidb.sidb_layout) -> str: ...
@overload
def get_name(ntk_or_lyt: TechnologyNetwork) -> str: ...
@overload
def get_name(ntk_or_lyt: AigNetwork) -> str: ...
@overload
def get_name(ntk_or_lyt: XagNetwork) -> str: ...
@overload
def get_name(ntk_or_lyt: MigNetwork) -> str:
    """
    Helper function to conveniently fetch the name from a layout or
    network as they use different function names for the same purpose.

    Args:
        ntk_or_lyt: Network or layout object.

    Template Args:
        NtkOrLyt: Network or layout type.

    Returns:
        Name of given network or layout.
    """

@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.layouts.CartesianGateLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.layouts.ShiftedCartesianGateLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.layouts.HexagonalGateLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.layouts.OddRowCartesianGateLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.layouts.EvenRowCartesianGateLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.layouts.EvenColumnCartesianGateLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.layouts.OddRowHexGateLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.layouts.OddColumnHexGateLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.layouts.EvenColumnHexGateLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.qca.QCALayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.mol_qca.MolecularQCALayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.inml.INMLLayout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: mnt.pyfiction._native.sidb.sidb_layout, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: TechnologyNetwork, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: AigNetwork, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: XagNetwork, name: str) -> None: ...
@overload
def set_name(ntk_or_lyt: MigNetwork, name: str) -> None:
    """
    Helper function to conveniently assign a name to a layout or network
    as they use different function names for the same purpose.

    Args:
        ntk_or_lyt: Network or layout object.
        name: Name to assign to given network or layout.

    Template Args:
        NtkOrLyt: Network or layout type.
    """

class high_degree_fanin_exception(ValueError): ...

def has_high_degree_fanin_nodes(ntk: TechnologyNetwork, threshold: int = 2) -> bool:
    """
    Checks if a given network exceeds a given fanin threshold in any of
    its nodes.

    Args:
        ntk: Network to check.
        threshold: Maximum number of legal fanins.

    Template Args:
        Ntk: `mockturtle` network type.

    Returns:
        `true` iff any node in `ntk` exceeds `threshold` fanins.
    """

def random_aig_network(inputs: int, gates: int, seed: int) -> AigNetwork:
    """Generate a native random AIG network."""

def random_xag_network(inputs: int, gates: int, seed: int) -> XagNetwork:
    """Generate a native random XAG network."""

def random_mig_network(inputs: int, gates: int, seed: int) -> MigNetwork:
    """Generate a native random MIG network."""

def random_tec_network(inputs: int, gates: int, seed: int) -> TechnologyNetwork:
    """Generate a native random TEC network."""

@overload
def simulate_outputs(network: TechnologyNetwork) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(network: AigNetwork) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(network: XagNetwork) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(network: MigNetwork) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(layout: mnt.pyfiction._native.layouts.CartesianGateLayout) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(
    layout: mnt.pyfiction._native.layouts.ShiftedCartesianGateLayout,
) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(layout: mnt.pyfiction._native.layouts.HexagonalGateLayout) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(
    layout: mnt.pyfiction._native.layouts.OddRowCartesianGateLayout,
) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(
    layout: mnt.pyfiction._native.layouts.EvenRowCartesianGateLayout,
) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(
    layout: mnt.pyfiction._native.layouts.EvenColumnCartesianGateLayout,
) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(layout: mnt.pyfiction._native.layouts.OddRowHexGateLayout) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(layout: mnt.pyfiction._native.layouts.OddColumnHexGateLayout) -> list[tuple[str, list[bool]]]: ...
@overload
def simulate_outputs(layout: mnt.pyfiction._native.layouts.EvenColumnHexGateLayout) -> list[tuple[str, list[bool]]]:
    """
    Return (name, bits) pairs in output declaration order, preserving duplicate labels. Truth-table storage grows exponentially with the input count; fewer than 38 inputs is a representation bound, not a memory guarantee.
    """

@overload
def simulate(network: TechnologyNetwork) -> dict[str, list[bool]]: ...
@overload
def simulate(network: AigNetwork) -> dict[str, list[bool]]: ...
@overload
def simulate(network: XagNetwork) -> dict[str, list[bool]]: ...
@overload
def simulate(network: MigNetwork) -> dict[str, list[bool]]: ...
@overload
def simulate(layout: mnt.pyfiction._native.layouts.CartesianGateLayout) -> dict[str, list[bool]]: ...
@overload
def simulate(layout: mnt.pyfiction._native.layouts.ShiftedCartesianGateLayout) -> dict[str, list[bool]]: ...
@overload
def simulate(layout: mnt.pyfiction._native.layouts.HexagonalGateLayout) -> dict[str, list[bool]]: ...
@overload
def simulate(layout: mnt.pyfiction._native.layouts.OddRowCartesianGateLayout) -> dict[str, list[bool]]: ...
@overload
def simulate(layout: mnt.pyfiction._native.layouts.EvenRowCartesianGateLayout) -> dict[str, list[bool]]: ...
@overload
def simulate(layout: mnt.pyfiction._native.layouts.EvenColumnCartesianGateLayout) -> dict[str, list[bool]]: ...
@overload
def simulate(layout: mnt.pyfiction._native.layouts.OddRowHexGateLayout) -> dict[str, list[bool]]: ...
@overload
def simulate(layout: mnt.pyfiction._native.layouts.OddColumnHexGateLayout) -> dict[str, list[bool]]: ...
@overload
def simulate(layout: mnt.pyfiction._native.layouts.EvenColumnHexGateLayout) -> dict[str, list[bool]]: ...
