/*
 * Copyright (c) 2018 - 2023 Marcel Walter
 * Copyright (c) 2023 - present Chair for Design Automation, Technical University of Munich
 * All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License
 */

/**
 * @file
 * @brief SVG writer for SiDB cell-level layouts.
 * @author Sophia Kuhn
 * @author Marcel Walter (marcelwa)
 */

#pragma once

#include "fiction/layouts/bounding_box.hpp"
#include "fiction/layouts/coordinates.hpp"
#include "fiction/layouts/layout_utils.hpp"
#include "fiction/technology/sidb/charge_distribution.hpp"
#include "fiction/technology/sidb/lattice.hpp"
#include "fiction/technology/sidb/layout.hpp"
#include "fiction/technology/sidb/model/charge_state.hpp"
#include "fiction/traits.hpp"
#include "fiction/utils/version_info.hpp"

#include <fmt/format.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <exception>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>
#include <string_view>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>

namespace fiction::sidb::io
{

/**
 * Parameters for writing SiDB layouts to SVG format.
 */
struct write_sidb_layout_svg_params
{
    /**
     * Enumeration to specify the color mode for the SVG output.
     */
    enum class color_mode : uint8_t
    {
        /**
         * Dark mode.
         */
        DARK,
        /**
         * Light mode.
         */
        LIGHT
    };
    /**
     * Enumeration to specify if the H-Si lattice is plotted in addition to SiDBs.
     */
    enum class sidb_lattice_mode : uint8_t
    {
        /**
         * Lattice is hidden. Only SiDBs are shown.
         */
        HIDE_LATTICE,
        /**
         * Lattice is shown.
         */
        SHOW_LATTICE
    };
    /**
     * Size of the H-Si lattice points in SVG units.
     */
    double lattice_point_size = 0.3;
    /**
     * Size of the SiDB in SVG units.
     */
    double sidb_size = 0.9;
    /**
     * Border width of the SiDB.
     */
    double sidb_border_width = 0.3;
    /**
     * The color mode of the background for the SVG output.
     */
    color_mode color_background = color_mode::DARK;
    /**
     * The lattice mode of the SiDB layout.
     */
    sidb_lattice_mode lattice_mode = sidb_lattice_mode::SHOW_LATTICE;
};

namespace detail
{

namespace svg
{

// Color definitions
inline constexpr const char* NEUTRAL_COLOR                   = "#6e7175";
inline constexpr const char* NEGATIVE_COLOR                  = "#00ADAE";
inline constexpr const char* POSITIVE_COLOR                  = "#E34857";
inline constexpr const char* BACKGROUND_COLOR_BRIGHT         = "#ffffff";
inline constexpr const char* BACKGROUND_COLOR_DARK           = "#25323D";
inline constexpr const char* SIDB_DOT_DARK_MODE              = "#C8C8C8";
inline constexpr const char* SIDB_DOT_BRIGHT_MODE            = "#ffffff";
inline constexpr const char* SIDB_DOT_LINE_COLOR_DARK_MODE   = "#ffffff";
inline constexpr const char* SIDB_DOT_LINE_COLOR_BRIGHT_MODE = "#C8C8C8";
inline constexpr const char* SI_LATTICE                      = "#6e7175";

// SVG Header with numbered placeholders
inline constexpr const char* HEADER_TEMPLATE = R"(<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by {0} ({1}) -->
<svg
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:cc="http://creativecommons.org/ns#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="{2} {3} {4} {5}"
    version="1.1">
    <metadata>
        <rdf:RDF>
            <cc:Work rdf:about="">
                <dc:format>image/svg+xml</dc:format>
                <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
                <dc:title></dc:title>
            </cc:Work>
        </rdf:RDF>
    </metadata>
    {6} <!-- PATH_DEFINITION placeholder -->
    {7} <!-- Background rectangle placeholder -->
    <g>
        {8} <!-- SVG content placeholder -->
    </g>
</svg>)";

// SVG path definitions for lattice points and SiDBs
static constexpr const char* PATH_DEFINITION_TEMPLATE = R"(
<defs>
    <!-- lattice point -->
    <circle id="lattice_point" cx="0" cy="0" r="{0}"/>
    <!-- SiDB -->
    <circle id="sidb_color" cx="0" cy="0" r="{1}"/>
</defs>
)";

}  // namespace svg

/**
 * Draws an `sidb::layout` as an SVG image: the lattice points of the layout's bounding box, if requested, and every
 * SiDB at its position on the layout's lattice.
 */
class sidb_layout_svg_writer
{
  public:
    /**
     * Creates an SVG writer for a lattice layout.
     *
     * @param layout Layout to draw.
     * @param stream Output stream.
     * @param p Drawing parameters.
     * @param charges Charge distribution to draw, or `nullptr` to use the default SiDB color.
     */
    sidb_layout_svg_writer(const layout& layout, std::ostream& stream, const write_sidb_layout_svg_params& p,
                           const charge_distribution* charges = nullptr) :
            lyt{layout},
            os{stream},
            ps{p},
            cd{charges}
    {
        if (ps.color_background == write_sidb_layout_svg_params::color_mode::LIGHT)
        {
            background_color = svg::BACKGROUND_COLOR_BRIGHT;
            sidb_color       = svg::SIDB_DOT_BRIGHT_MODE;
            sidb_edge_color  = svg::SIDB_DOT_LINE_COLOR_BRIGHT_MODE;
        }
        else
        {
            background_color = svg::BACKGROUND_COLOR_DARK;
            sidb_color       = svg::SIDB_DOT_DARK_MODE;
            sidb_edge_color  = svg::SIDB_DOT_LINE_COLOR_DARK_MODE;
        }
    }

    /**
     * Draws the lattice and SiDBs with padding around the bounding box.
     *
     * @throws std::out_of_range if padding exceeds the lattice-site coordinate range.
     */
    void run() const
    {
        std::stringstream svg_content{};

        const auto [min_site, max_site] = lyt.bounding_box();
        const auto padded_max           = max_site + lattice_site{2, 1, 1};

        // sites are drawn one column and one unit cell away from the top-left corner as padding
        const auto padded = [](const lattice_site& s) { return s + lattice_site{1, 1}; };

        if (ps.lattice_mode == write_sidb_layout_svg_params::sidb_lattice_mode::SHOW_LATTICE)
        {
            for (const auto& s : sites_in_area(min_site, max_site))
            {
                const auto [x, y] = lyt.get_lattice().nm_position(padded(s));

                svg_content << fmt::format(R"(<use xlink:href="#lattice_point" x="{0}" y="{1}" style="fill:{2};"/>)",
                                           x * 10, y * 10, svg::SI_LATTICE);
            }
        }

        lyt.foreach_cell(
            [&](const auto& s)
            {
                const auto [x, y] = lyt.get_lattice().nm_position(padded(s));

                std::string fill_color   = sidb_color;
                std::string border_color = sidb_edge_color;
                auto        fill_opacity = 1.0;

                if (cd != nullptr)
                {
                    switch (cd->get_charge_state(s))
                    {
                        case model::charge_state::POSITIVE:
                        {
                            fill_color   = svg::POSITIVE_COLOR;
                            border_color = svg::POSITIVE_COLOR;
                            break;
                        }
                        case model::charge_state::NEGATIVE:
                        {
                            fill_color   = svg::NEGATIVE_COLOR;
                            border_color = svg::NEGATIVE_COLOR;
                            break;
                        }
                        case model::charge_state::NEUTRAL:
                        {
                            fill_opacity = 0.0;
                            break;
                        }
                        default:
                        {
                            border_color = svg::NEUTRAL_COLOR;
                            fill_opacity = 0.0;
                            break;
                        }
                    }
                }

                svg_content << fmt::format(
                    R"(<use xlink:href="#sidb_color" x="{0}" y="{1}" style="fill:{2}; fill-opacity:{3}; stroke:{4}; stroke-width:{5};"/>)",
                    x * 10, y * 10, fill_color, fill_opacity, border_color, ps.sidb_border_width);
            });

        const auto [min_x, min_y] = lyt.get_lattice().nm_position(min_site);
        const auto [max_x, max_y] = lyt.get_lattice().nm_position(padded_max);

        const auto viewbox_x      = min_x * 10;
        const auto viewbox_y      = min_y * 10;
        const auto viewbox_width  = (max_x - min_x) * 10;
        const auto viewbox_height = (max_y - min_y) * 10;

        const auto background_rect =
            fmt::format(R"(<rect x="{0}" y="{1}" width="{2}" height="{3}" style="fill:{4};"/>)", viewbox_x, viewbox_y,
                        viewbox_width, viewbox_height, background_color);

        os << fmt::format(svg::HEADER_TEMPLATE, FICTION_VERSION, FICTION_REPO, viewbox_x, viewbox_y, viewbox_width,
                          viewbox_height,
                          fmt::format(svg::PATH_DEFINITION_TEMPLATE, ps.lattice_point_size, ps.sidb_size),
                          background_rect, svg_content.str());
    }

  private:
    /**
     * Layout to draw.
     */
    const layout& lyt;
    /**
     * Output stream.
     */
    std::ostream& os;
    /**
     * Drawing parameters.
     */
    const write_sidb_layout_svg_params ps;
    /**
     * Charge distribution to draw, or `nullptr` to use the default SiDB color.
     */
    const charge_distribution* cd;
    /**
     * Background color.
     */
    std::string background_color{};
    /**
     * SiDB fill color.
     */
    std::string sidb_color{};
    /**
     * SiDB border color.
     */
    std::string sidb_edge_color{};
};

}  // namespace detail

/**
 * Writes an `sidb::layout` as an SVG image to a stream: the lattice points of the layout's bounding box, if the
 * parameters ask for them, and every SiDB at its position on the layout's lattice. Surface defects are not drawn.
 *
 * @param lyt Layout to draw.
 * @param os Output stream to write into.
 * @param ps Drawing parameters.
 * @throws std::out_of_range if padding exceeds the lattice-site coordinate range.
 */
inline void write_sidb_layout_svg(const layout& lyt, std::ostream& os, const write_sidb_layout_svg_params& ps = {})
{
    const detail::sidb_layout_svg_writer p{lyt, os, ps};
    p.run();
}
/**
 * Writes an `sidb::layout` as an SVG image. See the stream overload for the image's content.
 *
 * @param lyt Layout to draw.
 * @param filename File to write into.
 * @param ps Drawing parameters.
 * @throws std::ofstream::failure if the file cannot be opened.
 * @throws std::out_of_range if padding exceeds the lattice-site coordinate range.
 */
inline void write_sidb_layout_svg(const layout& lyt, const std::string_view& filename,
                                  const write_sidb_layout_svg_params& ps = {})
{
    std::ofstream os{std::string{filename}, std::ofstream::out};

    if (!os.is_open())
    {
        throw std::ofstream::failure("Could not open file");
    }

    write_sidb_layout_svg(lyt, os, ps);
    os.close();
}

/**
 * Writes an `sidb::layout` with a charge distribution as an SVG image to a stream: as the layout overload, with every
 * SiDB colored by its charge state.
 *
 * @param lyt Layout to draw.
 * @param cd Charge distribution over the layout's SiDBs.
 * @param os Output stream to write into.
 * @param ps Drawing parameters.
 */
inline void write_sidb_layout_svg(const layout& lyt, const charge_distribution& cd, std::ostream& os,
                                  const write_sidb_layout_svg_params& ps = {})
{
    const detail::sidb_layout_svg_writer p{lyt, os, ps, &cd};
    p.run();
}
/**
 * Writes an `sidb::layout` with a charge distribution as an SVG image. See the stream overload for the image's
 * content.
 *
 * @param lyt Layout to draw.
 * @param cd Charge distribution over the layout's SiDBs.
 * @param filename File to write into.
 * @param ps Drawing parameters.
 * @throws std::ofstream::failure if the file cannot be opened.
 */
inline void write_sidb_layout_svg(const layout& lyt, const charge_distribution& cd, const std::string_view& filename,
                                  const write_sidb_layout_svg_params& ps = {})
{
    std::ofstream os{std::string{filename}, std::ofstream::out};

    if (!os.is_open())
    {
        throw std::ofstream::failure("Could not open file");
    }

    write_sidb_layout_svg(lyt, cd, os, ps);
    os.close();
}

}  // namespace fiction::sidb::io
