name: 🐍 • CI

on:
  push:
    branches: ["main"]
    paths:
      - "bindings/pyfiction/**"
      - "**/*.py"
      - "**/*.hpp"
      - "**/*.cpp"
      - "**/*.cmake"
      - "**/CMakeLists.txt"
      - "noxfile.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/python-bindings.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "bindings/pyfiction/**"
      - "**/*.py"
      - "**/*.hpp"
      - "**/*.cpp"
      - "**/*.cmake"
      - "**/CMakeLists.txt"
      - "noxfile.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/python-bindings.yml"
  workflow_run:
    workflows: ["pyfiction Docstring Generator"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  Z3_VERSION: 4.13.4

jobs:
  python-tests:
    name: 🐍 ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
    steps:
      - name: Clone Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup ccache
        if: matrix.runs-on != 'ubuntu-24.04-arm'
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2
        with:
          key: "${{matrix.runs-on}}-pyfiction"
          save: true
          max-size: 10G

      - if: runner.os == 'Linux'
        name: Setup mold
        uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1

      - name: Setup Z3 Solver
        id: z3
        uses: cda-tum/setup-z3@7bfe87519f27304460db44284cb8cc59f50f5fc9 # v1.7.2
        with:
          version: ${{env.Z3_VERSION}}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: "latest"
          enable-cache: true

      - name: Setup nox
        uses: wntrblm/nox@3284968a16fa5bd7fc0cc64a69a531404ccb4756 # 2026.07.11

      - name: 🐍 Test
        run: nox -s tests --verbose
