name: 🍎 • C++ Tests

on:
  workflow_call:
    inputs:
      runs-on:
        description: The runner to execute on
        required: true
        type: string
      compiler:
        description: The C++ compiler binary name
        required: true
        type: string

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-cpp-tests-${{
    inputs.runs-on }}-${{ inputs.compiler }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

env:
  Z3_VERSION: 4.13.4

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read # required to check out the repository

    steps:
      - name: Clone Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14.x"

      - name: Install building tools
        run: brew install autoconf

      # Setup TBB for parallel STL algorithms via Homebrew
      - name: Setup TBB
        run: brew install tbb

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2
        with:
          key: "${{ inputs.runs-on }}-${{ inputs.compiler }}"
          variant: ccache
          save: true
          max-size: 10G

      - name: Setup Z3 Solver
        id: z3
        uses: cda-tum/setup-z3@7bfe87519f27304460db44284cb8cc59f50f5fc9 # v1.7.2
        with:
          version: ${{ env.Z3_VERSION }}

      # Build and test pipeline for Debug mode

      - name: Configure CMake (Debug)
        env:
          COMPILER: ${{ inputs.compiler }}
        run: >
          cmake -S . --preset ci-debug
          -DCMAKE_CXX_COMPILER="$COMPILER"

      - name: Build (Debug)
        run: cmake --build --preset ci-debug --parallel 3

      - name: Test (Debug)
        run: ctest --preset ci-debug --output-on-failure --repeat until-pass:3 --parallel 3

      # Build and test pipeline for Release mode

      - name: Configure CMake (Release)
        env:
          COMPILER: ${{ inputs.compiler }}
        run: >
          cmake -S . --preset ci-release
          -DCMAKE_CXX_COMPILER="$COMPILER"
          -DFICTION_ENABLE_JEMALLOC=ON

      - name: Build (Release)
        run: cmake --build --preset ci-release --parallel 3

      - name: Test (Release)
        run: ctest --preset ci-release --output-on-failure --repeat until-pass:3 --parallel 3
