name: 🌈 • Zizmor

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: 🌈 Zizmor
    runs-on: ubuntu-slim
    permissions:
      security-events: write # required to upload results to the code scanning API

    steps:
      - name: Clone Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
        with:
          persona: pedantic
